HASPECT6: THSHipoTrigger Class Reference
THSHipoTrigger Class Reference
Definition at line 8 of file THSHipoTrigger.h.
#include <THSHipoTrigger.h>
Public Member Functions
THSHipoTrigger ()
virtual ~THSHipoTrigger ()
virtual Bool_t ReadEvent (Long64_t entry=0)
virtual void InitOutput (TString filename)
Public Member Functions inherited from THSHipoReader
THSHipoReader ()
virtual ~THSHipoReader ()
virtual Bool_t Init (TString filename, TString name="")
virtual void CloseReadTree ()
void SetUsePID (Bool_t use=kTRUE)
Public Member Functions inherited from THSDataManager
THSDataManager ()
virtual ~THSDataManager ()
Bool_t InitTreeReader (TString filename, TString name)
virtual void PrintEvent (Long64_t=0)
virtual void WriteParticles (TString filename)
Int_t GetN ()
THSParticle * GetParticle (Int_t i)
THSParticle * GetGenerated (Int_t i)
vector< THSParticle * > * GetParticles ()
vector< THSParticle * > * GetGenerated ()
void AddParticle (THSParticle *part)
void AddGenerated (THSParticle *part)
void ClearParticles ()
void SetReadBranch (TString name)
void SetReadGenBranch (TString name="")
void SetWriteGenBranch (TString name="")
void WriteEvent ()
void CloseOutput ()
void ReadWriteChain (TChain *chain, TString OutDirName, TString FileAppend)
void CloseReadTree ()
void AddUID (TString filename, TString treename="HSParticles")
void SetUID (Long64_t val)
Long64_t GetEntry ()
TTreeReaderArray< THSParticle > * GetReaderParticles ()
TTreeReaderArray< THSParticle > * GetReaderGenerated ()
void LoadWeights (TString fname, TString wname)
void GetWeightEvent ()
Double_t GetWeight (Int_t species)
THSWeights * GetWeights ()
TTree * GetReadTree ()
Additional Inherited Members
Protected Attributes inherited from THSHipoReader
THipo * fHipo =nullptr
THipoBank * fPBank =nullptr
THipoBank * fSBank =nullptr
THipoBank * fMCBank =nullptr
THipoBank * fFTBank =nullptr
THipoBank * fEvBank =nullptr
THipoItem * fPid =nullptr
THipoItem * fPx =nullptr
THipoItem * fPy =nullptr
THipoItem * fPz =nullptr
THipoItem * fVx =nullptr
THipoItem * fVy =nullptr
THipoItem * fVz =nullptr
THipoItem * fBeta =nullptr
THipoItem * fCharge =nullptr
THipoItem * fSPindex =nullptr
THipoItem * fSTime =nullptr
THipoItem * fSEnergy =nullptr
THipoItem * fSDet =nullptr
THipoItem * fSPath =nullptr
THipoItem * fFTPindex =nullptr
THipoItem * fFTTime =nullptr
THipoItem * fFTEnergy =nullptr
THipoItem * fFTDet =nullptr
THipoItem * fFTPath =nullptr
THipoItem * fEvTime =nullptr
THipoItem * fMCPid =nullptr
THipoItem * fMCPx =nullptr
THipoItem * fMCPy =nullptr
THipoItem * fMCPz =nullptr
THipoItem * fMCVx =nullptr
THipoItem * fMCVy =nullptr
THipoItem * fMCVz =nullptr
Bool_t fUsePID =kTRUE
Protected Attributes inherited from THSDataManager
vector< THSParticle * > fParticles
vector< THSParticle * > * fReadParticles =nullptr
vector< THSParticle * > fGenerated
vector< THSParticle * > * fReadGenerated =nullptr
UInt_t fNin =0
UInt_t fNgen =0
TFile * fReadFile =0
TTree * fReadTree =0
Long64_t fEntry =0
TString fReadBName ="Particles"
TString fReadGName =""
TString fWriteGName =""
TString fIDName ="UID"
Bool_t fAddGenerated =kFALSE
Bool_t fInGenerated =kFALSE
TFile * fWriteFile =0
TTree * fWriteTree =0
TTreeReader fTReader
TTreeReaderArray< THSParticle > fTParticles {fTReader, "Particles"}
TTreeReaderArray< THSParticle > * fTGenerated =nullptr
TTreeReaderValue< Double_t > * fTUID =nullptr
Double_t UID =0
THSWeights * fWeights =nullptr
Double_t fWeight =1
Constructor & Destructor Documentation
THSHipoTrigger::THSHipoTrigger ()
Ft Hodoscope
Definition at line 3 of file THSHipoTrigger.C.
References THSHipoReader::fHipo.
virtual THSHipoTrigger::~THSHipoTrigger () inline virtual
Definition at line 12 of file THSHipoTrigger.h.
References InitOutput(), and ReadEvent().
Member Function Documentation
void THSHipoTrigger::InitOutput (TString filename) virtual
Trigger:
Reimplemented from THSDataManager.
Definition at line 20 of file THSHipoTrigger.C.
References THSDataManager::fWriteTree, and THSDataManager::InitOutput().
Referenced by ~THSHipoTrigger().
Bool_t THSHipoTrigger::ReadEvent (Long64_t entry = 0) virtual
initalize variables:
///////////////////////////////////////////
Now do some trigger simulations:
FT Cal:
FT Hodo:
Reimplemented from THSHipoReader.
Definition at line 35 of file THSHipoTrigger.C.
References THSHipoReader::ReadEvent().
Referenced by ~THSHipoTrigger().
The documentation for this class was generated from the following files:
HaSpect/THSHipoTrigger.h
HaSpect/THSHipoTrigger.C