HASPECT6: THSParticleIter Class Reference
THSParticleIter Class Reference
Class to loop over THSParticle vectors Permuation, Rotation or Combination (Selection) done via THSCombinitorial class This class contains a pointer to another THSParticleIter to allow for recursive combinations. This class is used to control the permutating of particles in THSFinalState
Definition at line 9 of file THSParticleIter.h.
#include <THSParticleIter.h>
Public Member Functions
THSParticleIter ()
virtual ~THSParticleIter ()
THSCombitorial * GetCombi ()
void SetNSel (Int_t n)
void SetNIdentical (Int_t n)
Int_t GetNSel ()
Int_t GetNIdentical ()
vector< THSParticle * > * GetAllParticles ()
void SetParticles (vector< THSParticle * > *parts)
void SetSelParticles (vector< THSParticle * > parts)
void SetSelIter (THSParticleIter *com)
void SetRemIter (THSParticleIter *com)
void AddEventParticle (THSParticle *part)
void AddEventParticles (THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
void SetEventParticles (vector< THSParticle * > parts)
void SortEvent ()
void SetCombi (THSCombitorial combi)
THSParticle * NextParticle ()
In case all particle vector changes size need to redo selection map.
Bool_t NextCombitorial ()
void ConfigureIters ()
void SetNextInnerIter (THSParticleIter *_iter)
Add _iter to the end of the current iterator sequence.
void SelectXofY (Int_t _X, Int_t _Y, THSCombitorial *sel_iter=nullptr)
Bool_t Testing ()
Add function comments like this.
Constructor & Destructor Documentation
THSParticleIter::THSParticleIter () inline
Definition at line 12 of file THSParticleIter.h.
Referenced by SelectXofY().
virtual THSParticleIter::~THSParticleIter () inline virtual
Definition at line 13 of file THSParticleIter.h.
Member Function Documentation
void THSParticleIter::AddEventParticle (THSParticle * part) inline
Definition at line 52 of file THSParticleIter.h.
References AddEventParticles().
Referenced by AddEventParticles().
void THSParticleIter::AddEventParticles (THSParticle * part0 = nullptr, THSParticle * part1 = nullptr, THSParticle * part2 = nullptr, THSParticle * part3 = nullptr, THSParticle * part4 = nullptr, THSParticle * part5 = nullptr, THSParticle * part6 = nullptr, THSParticle * part7 = nullptr, THSParticle * part8 = nullptr, THSParticle * part9 = nullptr)
Set up to 10 event particle with 1 function call If you need more just call it again
Definition at line 247 of file THSParticleIter.C.
References AddEventParticle().
Referenced by AddEventParticle(), THSFinalState::AddPermutate(), and THSFinalState::AddSelectXofY().
void THSParticleIter::ConfigureIters ()
Set the order that the selected and remaining iterators will be called First Add selected then Remaining recursively
Definition at line 82 of file THSParticleIter.C.
References ConfigureIters(), and SetNextInnerIter().
Referenced by ConfigureIters(), NextCombitorial(), and SetCombi().
vector<THSParticle*>* THSParticleIter::GetAllParticles () inline
Definition at line 43 of file THSParticleIter.h.
THSCombitorial* THSParticleIter::GetCombi () inline
Definition at line 36 of file THSParticleIter.h.
Int_t THSParticleIter::GetNIdentical () inline
Definition at line 41 of file THSParticleIter.h.
Int_t THSParticleIter::GetNSel () inline
Definition at line 40 of file THSParticleIter.h.
Referenced by THSFinalState::AddSelectToSelected().
Bool_t THSParticleIter::NextCombitorial ()
Get the next combination of the iterator Returns kFALSE when all possible combinations have been given Returns kTRUE when still more combinations to go The new ordering can be accessed via NextParticle() Or if event particles have been set they can be updated by a call to SortEvent();
Definition at line 32 of file THSParticleIter.C.
References ConfigureIters(), THSCombitorial::GetType(), THSCombitorial::IsFinished(), THSCombitorial::Next(), NextCombitorial(), THSCombitorial::Remainder(), and SetParticles().
Referenced by NextCombitorial(), and SetCombi().
THSParticle * THSParticleIter::NextParticle ()
In case all particle vector changes size need to redo selection map.
Get the next particle in the current combination Returns a pointer to the next THSParticle If all particles done return null
Definition at line 116 of file THSParticleIter.C.
References NextParticle().
Referenced by NextParticle(), and SetCombi().
void THSParticleIter::SelectXofY (Int_t _X, Int_t _Y, THSCombitorial * sel_iter = nullptr)
Automates the recursive selection of Y identical particle types X times e.g. select 3pi0 from 6 photons == select 3 from 6; select 2 from remaining 4; use remaining 2 example usage : piterator.SelectXofY(3,2); An additional level of combinations sel_iter can be given and will be performed on all Y selections i.e.can add a permutation to the X selections example usage : piterator.SelectXofY(3,2, new THSPermutation());
Definition at line 171 of file THSParticleIter.C.
References SelectXofY(), SetCombi(), SetEventParticles(), SetNIdentical(), SetNSel(), THSCombitorial::SubSet(), and THSParticleIter().
Referenced by THSFinalState::AddSelectXofY(), SelectXofY(), and SetCombi().
void THSParticleIter::SetCombi (THSCombitorial combi) inline
Definition at line 57 of file THSParticleIter.h.
References ConfigureIters(), NextCombitorial(), NextParticle(), SelectXofY(), SetNextInnerIter(), and Testing().
Referenced by THSFinalState::AddPermutate(), THSFinalState::CreateParticleIter(), and SelectXofY().
void THSParticleIter::SetEventParticles (vector< THSParticle * > parts) inline
Definition at line 54 of file THSParticleIter.h.
References SortEvent().
Referenced by SelectXofY().
void THSParticleIter::SetNextInnerIter (THSParticleIter * _iter)
Add _iter to the end of the current iterator sequence.
Definition at line 96 of file THSParticleIter.C.
References SetNextInnerIter().
Referenced by ConfigureIters(), SetCombi(), and SetNextInnerIter().
void THSParticleIter::SetNIdentical (Int_t n) inline
Definition at line 39 of file THSParticleIter.h.
Referenced by SelectXofY().
void THSParticleIter::SetNSel (Int_t n) inline
Definition at line 38 of file THSParticleIter.h.
Referenced by THSFinalState::CreateParticleIter(), and SelectXofY().
void THSParticleIter::SetParticles (vector< THSParticle * > * parts) inline
Definition at line 45 of file THSParticleIter.h.
Referenced by THSFinalState::CreateParticleIter(), and NextCombitorial().
void THSParticleIter::SetRemIter (THSParticleIter * com) inline
Definition at line 50 of file THSParticleIter.h.
Referenced by THSFinalState::AddPermutateToRemainder(), and THSFinalState::AddSelectToRemainder().
void THSParticleIter::SetSelIter (THSParticleIter * com) inline
Definition at line 49 of file THSParticleIter.h.
Referenced by THSFinalState::AddPermutateToSelected(), and THSFinalState::AddSelectToSelected().
void THSParticleIter::SetSelParticles (vector< THSParticle * > parts) inline
Definition at line 46 of file THSParticleIter.h.
void THSParticleIter::SortEvent ()
If event particles have been given assign copy a HSParticle to them in the current combination order The particles have to have been assigned to the correct iterator
Definition at line 202 of file THSParticleIter.C.
References SortEvent().
Referenced by SetEventParticles(), and SortEvent().
Bool_t THSParticleIter::Testing ()
Add function comments like this.
Definition at line 17 of file THSParticleIter.C.
References THSParticle::Detector(), and THSCombitorial::GetType().
Referenced by SetCombi().
The documentation for this class was generated from the following files:
HaSpect/THSParticleIter.h
HaSpect/THSParticleIter.C