HASPECT6: THSLundReader Class Reference
THSLundReader Class Reference
Definition at line 12 of file THSLundReader.h.
#include <THSLundReader.h>
Public Member Functions
THSLundReader ()
~THSLundReader ()
virtual Bool_t Init (TString filename, TString name="")
virtual Bool_t ReadEvent (Long64_t entry=0)
virtual Bool_t ReadGenerated (Long64_t entry=0)
Public Member Functions inherited from THSDataManager
THSDataManager ()
virtual ~THSDataManager ()
Bool_t InitTreeReader (TString filename, TString name)
virtual void PrintEvent (Long64_t=0)
virtual void WriteParticles (TString filename)
Int_t GetN ()
THSParticle * GetParticle (Int_t i)
THSParticle * GetGenerated (Int_t i)
vector< THSParticle * > * GetParticles ()
vector< THSParticle * > * GetGenerated ()
void AddParticle (THSParticle *part)
void AddGenerated (THSParticle *part)
void ClearParticles ()
void SetReadBranch (TString name)
void SetReadGenBranch (TString name="")
void SetWriteGenBranch (TString name="")
virtual void InitOutput (TString filename)
void WriteEvent ()
void CloseOutput ()
void ReadWriteChain (TChain *chain, TString OutDirName, TString FileAppend)
void CloseReadTree ()
void AddUID (TString filename, TString treename="HSParticles")
void SetUID (Long64_t val)
Long64_t GetEntry ()
TTreeReaderArray< THSParticle > * GetReaderParticles ()
TTreeReaderArray< THSParticle > * GetReaderGenerated ()
void LoadWeights (TString fname, TString wname)
void GetWeightEvent ()
Double_t GetWeight (Int_t species)
THSWeights * GetWeights ()
TTree * GetReadTree ()
Additional Inherited Members
Protected Attributes inherited from THSDataManager
vector< THSParticle * > fParticles
vector< THSParticle * > * fReadParticles =nullptr
vector< THSParticle * > fGenerated
vector< THSParticle * > * fReadGenerated =nullptr
UInt_t fNin =0
UInt_t fNgen =0
TFile * fReadFile =0
TTree * fReadTree =0
Long64_t fEntry =0
TString fReadBName ="Particles"
TString fReadGName =""
TString fWriteGName =""
TString fIDName ="UID"
Bool_t fAddGenerated =kFALSE
Bool_t fInGenerated =kFALSE
TFile * fWriteFile =0
TTree * fWriteTree =0
TTreeReader fTReader
TTreeReaderArray< THSParticle > fTParticles {fTReader, "Particles"}
TTreeReaderArray< THSParticle > * fTGenerated =nullptr
TTreeReaderValue< Double_t > * fTUID =nullptr
Double_t UID =0
THSWeights * fWeights =nullptr
Double_t fWeight =1
Constructor & Destructor Documentation
THSLundReader::THSLundReader () inline
Definition at line 15 of file THSLundReader.h.
THSLundReader::~THSLundReader () inline
Definition at line 16 of file THSLundReader.h.
References Init(), ReadEvent(), and ReadGenerated().
Member Function Documentation
Bool_t THSLundReader::Init (TString filename, TString name = "") virtual
Reimplemented from THSDataManager.
Definition at line 5 of file THSLundReader.C.
References THSDataManager::fAddGenerated, THSDataManager::fNin, THSDataManager::fReadGenerated, and THSDataManager::fReadParticles.
Referenced by ~THSLundReader().
Bool_t THSLundReader::ReadEvent (Long64_t entry = 0) virtual
Reimplemented from THSDataManager.
Definition at line 25 of file THSLundReader.C.
References THSDataManager::fAddGenerated, THSDataManager::fNin, THSDataManager::fParticles, THSDataManager::fReadParticles, and ReadGenerated().
Referenced by ~THSLundReader().
Bool_t THSLundReader::ReadGenerated (Long64_t entry = 0) virtual
Definition at line 65 of file THSLundReader.C.
References THSDataManager::fGenerated, THSDataManager::fNin, and THSDataManager::fReadGenerated.
Referenced by ReadEvent(), and ~THSLundReader().
The documentation for this class was generated from the following files:
HaSpect/THSLundReader.h
HaSpect/THSLundReader.C