HASPECT6: THSSkeleton Class Reference
THSSkeleton Class Reference
Class to generate selector code based on TTree::MakeSelector()
Definition at line 20 of file THSSkeleton.h.
#include <THSSkeleton.h>
Public Member Functions
THSSkeleton ()
virtual ~THSSkeleton ()
void SetHisto (Bool_t is=kTRUE)
void SetAppendTree (Bool_t is=kTRUE)
void SetNewTree (Bool_t is=kTRUE)
void SetWeights (Bool_t is=kTRUE)
void SetLPS (Int_t is=0)
void SetFinalState (TString proj, Bool_t perm=kFALSE)
void SetFinalStateTopo (TString topos)
void SetFinalStateParts (TString finals)
void SetFileName (TString name)
void SetSelName (TString name)
void CreateSelector (TString selname, TString filename, TString treename, TString opt="")
Create intial selector code from TTree::MakeSelector()
void AddHSOutput ()
void HSOut_h ()
void HSOut_C ()
void HSOut_Control ()
void HSHisto ()
void HSAppend ()
void HSNewTree ()
Adds example of how to create a new output tree.
void HSWeights ()
Adds example of how to use the THSWeights class.
void HSLPS ()
Adds example of how to use the THSLongPS class.
void HSFinalState ()
void CreateMyFinalState ()
void CreateRooFitEventsPDF (TString pdfName, TString obsNames, TString parNames)
void AddLineAfter (TString line0, TString line1, Int_t off=0)
void ContinueLineAfter (TString line1, Int_t off=0)
void MoveToLine (TString line0)
TString FindNextLineLike (TString linelike)
void ReplaceMacroText (TString text0, TString text1)
void ReplaceAllMacroText (TString text0, TString text1)
void ReplaceInCurrLine (TString text0, TString text1)
Constructor & Destructor Documentation
THSSkeleton::THSSkeleton () inline
Definition at line 49 of file THSSkeleton.h.
virtual THSSkeleton::~THSSkeleton () inline virtual
Definition at line 50 of file THSSkeleton.h.
Member Function Documentation
void THSSkeleton::AddHSOutput ()
Definition at line 47 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::AddLineAfter (TString line0, TString line1, Int_t off = 0)
Definition at line 655 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::ContinueLineAfter (TString line1, Int_t off = 0)
Definition at line 662 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::CreateMyFinalState ()
Create a FinalState project.
Set fFinalTopo with SetFinalStateTopo()
Set fFinalParts with SetFinalStateParts()
Set fFinalName with SetFinalState()
Definition at line 563 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::CreateRooFitEventsPDF (TString pdfName, TString obsNames, TString parNames)
Definition at line 436 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::CreateSelector (TString selname, TString filename, TString treename, TString opt = "")
Create intial selector code from TTree::MakeSelector()
Definition at line 20 of file THSSkeleton.C.
Referenced by SetSelName().
TString THSSkeleton::FindNextLineLike (TString linelike)
Definition at line 675 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::HSAppend ()
Adds examples of how to append branches to the input to the input tree.
Definition at line 196 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::HSFinalState ()
Adds examples of how to include an analysis project like e.g. THSFinalTemp.C
Definition at line 359 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::HSHisto ()
Add examples of how to use the THSHisto class
Definition at line 137 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::HSLPS ()
Adds example of how to use the THSLongPS class.
Definition at line 323 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::HSNewTree ()
Adds example of how to create a new output tree.
Definition at line 229 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::HSOut_C ()
Definition at line 69 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::HSOut_Control ()
Definition at line 119 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::HSOut_h ()
Definition at line 105 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::HSWeights ()
Adds example of how to use the THSWeights class.
Definition at line 269 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::MoveToLine (TString line0)
Definition at line 668 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::ReplaceAllMacroText (TString text0, TString text1)
Definition at line 703 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::ReplaceInCurrLine (TString text0, TString text1)
Definition at line 689 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::ReplaceMacroText (TString text0, TString text1)
Definition at line 697 of file THSSkeleton.C.
Referenced by SetSelName().
void THSSkeleton::SetAppendTree (Bool_t is = kTRUE) inline
Definition at line 54 of file THSSkeleton.h.
void THSSkeleton::SetFileName (TString name) inline
Definition at line 61 of file THSSkeleton.h.
void THSSkeleton::SetFinalState (TString proj, Bool_t perm = kFALSE) inline
Definition at line 58 of file THSSkeleton.h.
void THSSkeleton::SetFinalStateParts (TString finals) inline
Definition at line 60 of file THSSkeleton.h.
void THSSkeleton::SetFinalStateTopo (TString topos) inline
Definition at line 59 of file THSSkeleton.h.
void THSSkeleton::SetHisto (Bool_t is = kTRUE) inline
Definition at line 53 of file THSSkeleton.h.
void THSSkeleton::SetLPS (Int_t is = 0) inline
Definition at line 57 of file THSSkeleton.h.
void THSSkeleton::SetNewTree (Bool_t is = kTRUE) inline
Definition at line 55 of file THSSkeleton.h.
void THSSkeleton::SetSelName (TString name) inline
Definition at line 62 of file THSSkeleton.h.
References AddHSOutput(), AddLineAfter(), ContinueLineAfter(), CreateMyFinalState(), CreateRooFitEventsPDF(), CreateSelector(), FindNextLineLike(), HSAppend(), HSFinalState(), HSHisto(), HSLPS(), HSNewTree(), HSOut_C(), HSOut_Control(), HSOut_h(), HSWeights(), MoveToLine(), ReplaceAllMacroText(), ReplaceInCurrLine(), and ReplaceMacroText().
void THSSkeleton::SetWeights (Bool_t is = kTRUE) inline
Definition at line 56 of file THSSkeleton.h.
The documentation for this class was generated from the following files:
HaSpect/THSSkeleton.h
HaSpect/THSSkeleton.C