HASPECT6: THSDataManager Class Reference
THSDataManager Class Reference
Definition at line 20 of file THSDataManager.h.
#include <THSDataManager.h>
Public Member Functions
THSDataManager ()
virtual ~THSDataManager ()
virtual Bool_t Init (TString filename, TString name="")
Bool_t InitTreeReader (TString filename, TString name)
virtual Bool_t ReadEvent (Long64_t entry=-1)
virtual void PrintEvent (Long64_t=0)
virtual void WriteParticles (TString filename)
Int_t GetN ()
THSParticle * GetParticle (Int_t i)
THSParticle * GetGenerated (Int_t i)
vector< THSParticle * > * GetParticles ()
vector< THSParticle * > * GetGenerated ()
void AddParticle (THSParticle *part)
void AddGenerated (THSParticle *part)
void ClearParticles ()
void SetReadBranch (TString name)
void SetReadGenBranch (TString name="")
void SetWriteGenBranch (TString name="")
virtual void InitOutput (TString filename)
void WriteEvent ()
void CloseOutput ()
void ReadWriteChain (TChain *chain, TString OutDirName, TString FileAppend)
void CloseReadTree ()
void AddUID (TString filename, TString treename="HSParticles")
void SetUID (Long64_t val)
Long64_t GetEntry ()
TTreeReaderArray< THSParticle > * GetReaderParticles ()
TTreeReaderArray< THSParticle > * GetReaderGenerated ()
void LoadWeights (TString fname, TString wname)
void GetWeightEvent ()
Double_t GetWeight (Int_t species)
THSWeights * GetWeights ()
TTree * GetReadTree ()
Protected Attributes
vector< THSParticle * > fParticles
vector< THSParticle * > * fReadParticles =nullptr
vector< THSParticle * > fGenerated
vector< THSParticle * > * fReadGenerated =nullptr
UInt_t fNin =0
UInt_t fNgen =0
TFile * fReadFile =0
TTree * fReadTree =0
Long64_t fEntry =0
TString fReadBName ="Particles"
TString fReadGName =""
TString fWriteGName =""
TString fIDName ="UID"
Bool_t fAddGenerated =kFALSE
Bool_t fInGenerated =kFALSE
TFile * fWriteFile =0
TTree * fWriteTree =0
TTreeReader fTReader
TTreeReaderArray< THSParticle > fTParticles {fTReader, "Particles"}
TTreeReaderArray< THSParticle > * fTGenerated =nullptr
TTreeReaderValue< Double_t > * fTUID =nullptr
Double_t UID =0
THSWeights * fWeights =nullptr
Double_t fWeight =1
Constructor & Destructor Documentation
THSDataManager::THSDataManager () inline
Definition at line 23 of file THSDataManager.h.
References Init(), InitTreeReader(), PrintEvent(), ReadEvent(), WriteParticles(), and ~THSDataManager().
THSDataManager::~THSDataManager () virtual
Definition at line 6 of file THSDataManager.C.
References CloseReadTree(), fGenerated, fParticles, fReadGenerated, fReadParticles, fTGenerated, fTUID, and fWeights.
Referenced by THSDataManager().
Member Function Documentation
void THSDataManager::AddGenerated (THSParticle * part) inline
Definition at line 38 of file THSDataManager.h.
References fGenerated, and fNgen.
void THSDataManager::AddParticle (THSParticle * part) inline
Definition at line 37 of file THSDataManager.h.
References fNin, and fParticles.
void THSDataManager::AddUID (TString filename, TString treename = "HSParticles")
Definition at line 158 of file THSDataManager.C.
References UID.
Referenced by WriteEvent().
void THSDataManager::ClearParticles () inline
Definition at line 39 of file THSDataManager.h.
References fGenerated, fNgen, fNin, and fParticles.
Referenced by ReadEvent().
void THSDataManager::CloseOutput ()
Definition at line 141 of file THSDataManager.C.
References fWriteFile, and fWriteTree.
Referenced by WriteEvent(), and WriteParticles().
void THSDataManager::CloseReadTree ()
Definition at line 40 of file THSDataManager.C.
References fReadFile.
Referenced by ReadWriteChain(), WriteEvent(), and ~THSDataManager().
Long64_t THSDataManager::GetEntry () inline
Definition at line 53 of file THSDataManager.h.
References fEntry.
THSParticle* THSDataManager::GetGenerated (Int_t i) inline
Definition at line 34 of file THSDataManager.h.
References fGenerated.
vector<THSParticle*>* THSDataManager::GetGenerated () inline
Definition at line 36 of file THSDataManager.h.
References fGenerated.
Int_t THSDataManager::GetN () inline
Definition at line 32 of file THSDataManager.h.
References fNin.
THSParticle* THSDataManager::GetParticle (Int_t i) inline
Definition at line 33 of file THSDataManager.h.
References fParticles.
vector<THSParticle*>* THSDataManager::GetParticles () inline
Definition at line 35 of file THSDataManager.h.
References fParticles.
TTreeReaderArray<THSParticle>* THSDataManager::GetReaderGenerated () inline
Definition at line 91 of file THSDataManager.h.
References fTGenerated, GetWeight(), GetWeightEvent(), and LoadWeights().
TTreeReaderArray<THSParticle>* THSDataManager::GetReaderParticles () inline
Definition at line 90 of file THSDataManager.h.
References fTParticles.
TTree* THSDataManager::GetReadTree () inline
Definition at line 97 of file THSDataManager.h.
References fReadTree.
Double_t THSDataManager::GetWeight (Int_t species)
Definition at line 193 of file THSDataManager.C.
References fWeight, fWeights, and THSWeights::GetWeight().
Referenced by GetReaderGenerated().
void THSDataManager::GetWeightEvent ()
Definition at line 190 of file THSDataManager.C.
References fTUID, fWeights, and THSWeights::GetEntryBinarySearch().
Referenced by GetReaderGenerated().
THSWeights* THSDataManager::GetWeights () inline
Definition at line 96 of file THSDataManager.h.
References fWeights.
Bool_t THSDataManager::Init (TString filename, TString name = "") virtual
Reimplemented in THSHipoReader, THSTxtTreeReader, THSLundReader, and THSRADSReader.
Definition at line 62 of file THSDataManager.C.
References InitTreeReader().
Referenced by ReadWriteChain(), and THSDataManager().
void THSDataManager::InitOutput (TString filename) virtual
Reimplemented in THSHipoTrigger.
Definition at line 133 of file THSDataManager.C.
References fAddGenerated, fGenerated, fParticles, fReadBName, fWriteFile, fWriteGName, and fWriteTree.
Referenced by THSHipoTrigger::InitOutput(), SetWriteGenBranch(), and WriteParticles().
Bool_t THSDataManager::InitTreeReader (TString filename, TString name)
Definition at line 48 of file THSDataManager.C.
References fIDName, fInGenerated, fReadBName, fReadFile, fReadGName, fReadTree, fTGenerated, fTParticles, fTReader, and fTUID.
Referenced by Init(), and THSDataManager().
void THSDataManager::LoadWeights (TString fname, TString wname)
Definition at line 183 of file THSDataManager.C.
References fWeights.
Referenced by GetReaderGenerated().
void THSDataManager::PrintEvent (Long64_t entry = 0) virtual
Definition at line 148 of file THSDataManager.C.
References fNin, fParticles, and ReadEvent().
Referenced by THSDataManager().
Bool_t THSDataManager::ReadEvent (Long64_t entry = -1) virtual
Reimplemented in THSHipoReader, THSTxtTreeReader, THSLundReader, THSRADSReader, and THSHipoTrigger.
Definition at line 66 of file THSDataManager.C.
References ClearParticles(), fEntry, fGenerated, fInGenerated, fParticles, fTGenerated, fTParticles, and fTReader.
Referenced by PrintEvent(), THSDataManager(), and WriteParticles().
void THSDataManager::ReadWriteChain (TChain * chain, TString OutDirName, TString FileAppend)
Definition at line 108 of file THSDataManager.C.
References CloseReadTree(), Init(), and WriteParticles().
Referenced by WriteEvent().
void THSDataManager::SetReadBranch (TString name) inline
Definition at line 41 of file THSDataManager.h.
References fReadBName.
void THSDataManager::SetReadGenBranch (TString name = "") inline
Definition at line 42 of file THSDataManager.h.
References fInGenerated, and fReadGName.
void THSDataManager::SetUID (Long64_t val) inline
Definition at line 51 of file THSDataManager.h.
References UID.
void THSDataManager::SetWriteGenBranch (TString name = "") inline
Definition at line 43 of file THSDataManager.h.
References fAddGenerated, fWriteGName, and InitOutput().
void THSDataManager::WriteEvent () inline
Definition at line 45 of file THSDataManager.h.
References AddUID(), CloseOutput(), CloseReadTree(), fWriteTree, and ReadWriteChain().
void THSDataManager::WriteParticles (TString filename) virtual
Definition at line 125 of file THSDataManager.C.
References CloseOutput(), fWriteTree, InitOutput(), and ReadEvent().
Referenced by ReadWriteChain(), and THSDataManager().
Member Data Documentation
Bool_t THSDataManager::fAddGenerated =kFALSE protected
Definition at line 71 of file THSDataManager.h.
Referenced by THSLundReader::Init(), THSHipoReader::Init(), InitOutput(), THSRADSReader::ReadEvent(), THSLundReader::ReadEvent(), THSHipoReader::ReadEvent(), and SetWriteGenBranch().
Long64_t THSDataManager::fEntry =0 protected
Definition at line 66 of file THSDataManager.h.
Referenced by GetEntry(), THSHipoReader::ReadEvent(), and ReadEvent().
vector<THSParticle*> THSDataManager::fGenerated protected
Definition at line 58 of file THSDataManager.h.
Referenced by AddGenerated(), ClearParticles(), GetGenerated(), InitOutput(), THSRADSReader::ReadEvent(), THSHipoReader::ReadEvent(), ReadEvent(), THSLundReader::ReadGenerated(), and ~THSDataManager().
TString THSDataManager::fIDName ="UID" protected
Definition at line 70 of file THSDataManager.h.
Referenced by InitTreeReader().
Bool_t THSDataManager::fInGenerated =kFALSE protected
Definition at line 72 of file THSDataManager.h.
Referenced by InitTreeReader(), ReadEvent(), and SetReadGenBranch().
UInt_t THSDataManager::fNgen =0 protected
Definition at line 61 of file THSDataManager.h.
Referenced by AddGenerated(), and ClearParticles().
UInt_t THSDataManager::fNin =0 protected
Definition at line 60 of file THSDataManager.h.
Referenced by AddParticle(), ClearParticles(), GetN(), THSRADSReader::Init(), THSLundReader::Init(), THSTxtTreeReader::Init(), PrintEvent(), THSLundReader::ReadEvent(), THSRADSReader::ReadEvent(), and THSLundReader::ReadGenerated().
vector<THSParticle*> THSDataManager::fParticles protected
Definition at line 56 of file THSDataManager.h.
Referenced by AddParticle(), ClearParticles(), GetParticle(), GetParticles(), THSTxtTreeReader::Init(), InitOutput(), PrintEvent(), THSLundReader::ReadEvent(), THSRADSReader::ReadEvent(), THSHipoReader::ReadEvent(), THSTxtTreeReader::ReadEvent(), ReadEvent(), and ~THSDataManager().
TString THSDataManager::fReadBName ="Particles" protected
Definition at line 67 of file THSDataManager.h.
Referenced by InitOutput(), InitTreeReader(), and SetReadBranch().
TFile* THSDataManager::fReadFile =0 protected
Definition at line 64 of file THSDataManager.h.
Referenced by CloseReadTree(), and InitTreeReader().
vector<THSParticle*>* THSDataManager::fReadGenerated =nullptr protected
Definition at line 59 of file THSDataManager.h.
Referenced by THSLundReader::Init(), THSRADSReader::Init(), THSHipoReader::Init(), THSRADSReader::ReadEvent(), THSHipoReader::ReadEvent(), THSLundReader::ReadGenerated(), and ~THSDataManager().
TString THSDataManager::fReadGName ="" protected
Definition at line 68 of file THSDataManager.h.
Referenced by InitTreeReader(), and SetReadGenBranch().
vector<THSParticle*>* THSDataManager::fReadParticles =nullptr protected
Definition at line 57 of file THSDataManager.h.
Referenced by THSLundReader::Init(), THSRADSReader::Init(), THSLundReader::ReadEvent(), THSRADSReader::ReadEvent(), THSHipoReader::ReadEvent(), THSHipoReader::THSHipoReader(), and ~THSDataManager().
TTree* THSDataManager::fReadTree =0 protected
Definition at line 65 of file THSDataManager.h.
Referenced by GetReadTree(), and InitTreeReader().
TTreeReaderArray<THSParticle>* THSDataManager::fTGenerated =nullptr protected
Definition at line 80 of file THSDataManager.h.
Referenced by GetReaderGenerated(), InitTreeReader(), ReadEvent(), and ~THSDataManager().
TTreeReaderArray<THSParticle> THSDataManager::fTParticles {fTReader, "Particles"} protected
Definition at line 79 of file THSDataManager.h.
Referenced by GetReaderParticles(), InitTreeReader(), and ReadEvent().
TTreeReader THSDataManager::fTReader protected
Definition at line 78 of file THSDataManager.h.
Referenced by InitTreeReader(), and ReadEvent().
TTreeReaderValue<Double_t>* THSDataManager::fTUID =nullptr protected
Definition at line 81 of file THSDataManager.h.
Referenced by GetWeightEvent(), InitTreeReader(), and ~THSDataManager().
Double_t THSDataManager::fWeight =1 protected
Definition at line 87 of file THSDataManager.h.
Referenced by GetWeight().
THSWeights* THSDataManager::fWeights =nullptr protected
Definition at line 86 of file THSDataManager.h.
Referenced by GetWeight(), GetWeightEvent(), GetWeights(), LoadWeights(), and ~THSDataManager().
TFile* THSDataManager::fWriteFile =0 protected
Definition at line 74 of file THSDataManager.h.
Referenced by CloseOutput(), and InitOutput().
TString THSDataManager::fWriteGName ="" protected
Definition at line 69 of file THSDataManager.h.
Referenced by InitOutput(), and SetWriteGenBranch().
TTree* THSDataManager::fWriteTree =0 protected
Definition at line 75 of file THSDataManager.h.
Referenced by CloseOutput(), THSHipoTrigger::InitOutput(), InitOutput(), WriteEvent(), and WriteParticles().
Double_t THSDataManager::UID =0 protected
Definition at line 83 of file THSDataManager.h.
Referenced by AddUID(), and SetUID().
The documentation for this class was generated from the following files:
HaSpect/THSDataManager.h
HaSpect/THSDataManager.C