HASPECT6: THSOutput Class Reference
THSOutput Class Reference
Definition at line 29 of file THSOutput.h.
#include <THSOutput.h>
Public Member Functions
THSOutput ()
virtual ~THSOutput ()
virtual void FinishOutput ()
virtual void InitOutFile (TTree *chain)
void InitOutTree ()
void PrepareOutDir ()
Int_t CountChar (TString tests, char testc)
void CopyCode (TDirectory *curDir=0, TDirectory *prevDir=0)
void ImportSysDirtoList (const char *dirname, TList *list)
TList * CopyDirtoList (TDirectory *source)
void WriteListtoFile (TList *list0)
void HSBegin (TList *input, TList *output)
void HSSlaveBegin (TList *input, TList *output)
virtual void HSProcessStart (Long64_t entry)
virtual void HSProcessFill ()
virtual void HSSlaveTerminate ()
virtual void HSNotify (TTree *tree)
virtual void HSTerminate ()
void SortTree (TTree *tree)
void SetSort (Bool_t sort=kTRUE)
TTree * GetOutTree ()
void SetIDoff (Long64_t off)
void SetParticles (TString sp)
Public Member Functions inherited from THSHisto
THSHisto (TTree *=0)
virtual ~THSHisto ()
virtual void InitialiseHisto (TList *input)
virtual void LoadCut (TString sCut)
virtual void LoadHistograms ()
virtual void ChangeNames ()
virtual TH1 * MapHist (TH1 *hist)
virtual TH1 * FindHist (TString hname)
virtual void OrganiseSavedHists (TFile *stdFile, TList *output)
void MakeAxisDir (Int_t iA, TDirectory *curDir)
virtual void HistogramList (TString sLabel)
virtual void FillHistograms (TString sCut)
void LoadWeights (TString fname, TString wname)
void LoadCutsForWeights ()
void FillCutsForWeights ()
void GetWeightEvent (Double_t id)
void SetWeight (TString species)
Protected Attributes
TFile * fFile =nullptr
TProofOutputFile * fProofFile =nullptr
TTree * fOutTree =nullptr
TTree * fCurTree =nullptr
TEntryList * fEntryList =nullptr
TString fOutName
TString fStrParticles
TString fStepName
TList * fStepDir =nullptr
TList * fSelInput =nullptr
TList * fSelOutput =nullptr
TList * fCodeList =nullptr
TList * fListOfFiles =nullptr
Long64_t fEntry =0
TObject fMessages
Bool_t fSort =kFALSE
Bool_t fSaveID =kFALSE
Double_t fgID =0
Long64_t fgIDoff =0
Protected Attributes inherited from THSHisto
Bool_t fIsHisto =0
StrTH1_Map fHistNameMap
Vec_StrTH1 fVecHistCut
vector< Vec_StrTH1 > fVecHistBin
TString fCurrCut
Int_t fCurrBin = 0
vector< TString > fVecTypes
vector< TString > fVecCuts
vector< TString > fVecBinNames
map< TString, Int_t > fMapCuts
map< TString, TString > fBinMap
TObjArray * fBinEntryLists
Additional Inherited Members
Public Attributes inherited from THSHisto
THSWeights * fWeights =nullptr
Double_t fWeight =1
THSBins * fBins =nullptr
Constructor & Destructor Documentation
THSOutput::THSOutput () inline
Definition at line 52 of file THSOutput.h.
References CopyCode(), CopyDirtoList(), CountChar(), FinishOutput(), HSBegin(), HSNotify(), HSProcessFill(), HSProcessStart(), HSSlaveBegin(), HSSlaveTerminate(), HSTerminate(), ImportSysDirtoList(), InitOutFile(), InitOutTree(), PrepareOutDir(), SortTree(), WriteListtoFile(), and ~THSOutput().
THSOutput::~THSOutput () virtual
Definition at line 37 of file THSOutput.C.
Referenced by THSOutput().
Member Function Documentation
void THSOutput::CopyCode (TDirectory * curDir = 0, TDirectory * prevDir = 0)
Definition at line 329 of file THSOutput.C.
Referenced by THSOutput().
TList * THSOutput::CopyDirtoList (TDirectory * source)
Definition at line 420 of file THSOutput.C.
Referenced by THSOutput().
Int_t THSOutput::CountChar (TString tests, char testc)
Definition at line 475 of file THSOutput.C.
Referenced by THSPartOutput::InitOutput(), and THSOutput().
void THSOutput::FinishOutput () virtual
Definition at line 219 of file THSOutput.C.
Referenced by THSOutput().
TTree* THSOutput::GetOutTree () inline
Definition at line 84 of file THSOutput.h.
References fOutTree.
void THSOutput::HSBegin (TList * input, TList * output)
Definition at line 46 of file THSOutput.C.
Referenced by THSOutput().
void THSOutput::HSNotify (TTree * tree) virtual
Definition at line 80 of file THSOutput.C.
Referenced by THSOutput().
void THSOutput::HSProcessFill () virtual
Definition at line 110 of file THSOutput.C.
Referenced by THSOutput().
void THSOutput::HSProcessStart (Long64_t entry) virtual
Definition at line 102 of file THSOutput.C.
Referenced by THSOutput().
void THSOutput::HSSlaveBegin (TList * input, TList * output)
Definition at line 61 of file THSOutput.C.
Referenced by THSOutput().
void THSOutput::HSSlaveTerminate () virtual
Definition at line 116 of file THSOutput.C.
Referenced by THSOutput().
void THSOutput::HSTerminate () virtual
Definition at line 119 of file THSOutput.C.
Referenced by THSOutput().
void THSOutput::ImportSysDirtoList (const char * dirname, TList * list)
Definition at line 373 of file THSOutput.C.
Referenced by THSOutput().
void THSOutput::InitOutFile (TTree * chain) virtual
Definition at line 287 of file THSOutput.C.
Referenced by THSOutput().
void THSOutput::InitOutTree ()
Definition at line 318 of file THSOutput.C.
Referenced by THSOutput().
void THSOutput::PrepareOutDir ()
Definition at line 278 of file THSOutput.C.
Referenced by THSOutput().
void THSOutput::SetIDoff (Long64_t off) inline
Definition at line 86 of file THSOutput.h.
void THSOutput::SetParticles (TString sp) inline
Definition at line 88 of file THSOutput.h.
void THSOutput::SetSort (Bool_t sort = kTRUE) inline
Definition at line 82 of file THSOutput.h.
void THSOutput::SortTree (TTree * tree)
Definition at line 254 of file THSOutput.C.
Referenced by THSOutput().
void THSOutput::WriteListtoFile (TList * list0)
Definition at line 452 of file THSOutput.C.
Referenced by THSOutput().
Member Data Documentation
TList* THSOutput::fCodeList =nullptr protected
Definition at line 42 of file THSOutput.h.
TTree* THSOutput::fCurTree =nullptr protected
Definition at line 34 of file THSOutput.h.
Long64_t THSOutput::fEntry =0 protected
Definition at line 44 of file THSOutput.h.
TEntryList* THSOutput::fEntryList =nullptr protected
Definition at line 35 of file THSOutput.h.
TFile* THSOutput::fFile =nullptr protected
Definition at line 31 of file THSOutput.h.
Double_t THSOutput::fgID =0 protected
Definition at line 49 of file THSOutput.h.
Long64_t THSOutput::fgIDoff =0 protected
Definition at line 50 of file THSOutput.h.
TList* THSOutput::fListOfFiles =nullptr protected
Definition at line 43 of file THSOutput.h.
TObject THSOutput::fMessages protected
Definition at line 45 of file THSOutput.h.
TString THSOutput::fOutName protected
Definition at line 36 of file THSOutput.h.
TTree* THSOutput::fOutTree =nullptr protected
Definition at line 33 of file THSOutput.h.
Referenced by GetOutTree(), and THSPartOutput::InitOutput().
TProofOutputFile* THSOutput::fProofFile =nullptr protected
Definition at line 32 of file THSOutput.h.
Bool_t THSOutput::fSaveID =kFALSE protected
Definition at line 48 of file THSOutput.h.
TList* THSOutput::fSelInput =nullptr protected
Definition at line 40 of file THSOutput.h.
TList* THSOutput::fSelOutput =nullptr protected
Definition at line 41 of file THSOutput.h.
Bool_t THSOutput::fSort =kFALSE protected
Definition at line 46 of file THSOutput.h.
TList* THSOutput::fStepDir =nullptr protected
Definition at line 39 of file THSOutput.h.
TString THSOutput::fStepName protected
Definition at line 38 of file THSOutput.h.
TString THSOutput::fStrParticles protected
Definition at line 37 of file THSOutput.h.
Referenced by THSPartOutput::InitOutput().
The documentation for this class was generated from the following files:
HaSpect/THSOutput.h
HaSpect/THSOutput.C