HASPECT6: THSKinematics Class Reference
THSKinematics Class Reference
Definition at line 12 of file THSKinematics.h.
#include <THSKinematics.h>
Public Member Functions
THSKinematics ()
~THSKinematics ()
Double_t CosTheta ()
Double_t Phi ()
void SetTarget (TLorentzVector tar)
void SetElecsTarget (TLorentzVector in, TLorentzVector sc, TLorentzVector tar)
void SetGammaTarget (TLorentzVector gamma, TLorentzVector tar)
void SetMesonBaryon (TLorentzVector mes, TLorentzVector bar)
void SetMesonDecay (TLorentzVector d1, TLorentzVector d2)
void SetBaryonDecay (TLorentzVector d1, TLorentzVector d2)
TLorentzVector Gamma ()
Double_t W ()
Double_t Q2 ()
Double_t GammaE ()
Double_t GammaTh ()
Double_t ElScatTh ()
Double_t GammaPol ()
Double_t GammaFlux ()
Double_t t ()
Double_t t (TLorentzVector p0, TLorentzVector p1)
Double_t t0 ()
Double_t t0 (TLorentzVector p0, TLorentzVector p1)
Double_t Cosx ()
Double_t Cosy ()
Double_t Cosz ()
void MesonDecayHelicity ()
void MesonDecayGJ ()
void ElectroCMDecay ()
void PhotoCMDecay ()
void LambdaDecay ()
void PolPhotoCMDecay ()
Constructor & Destructor Documentation
THSKinematics::THSKinematics () inline
Definition at line 35 of file THSKinematics.h.
THSKinematics::~THSKinematics () inline
Definition at line 36 of file THSKinematics.h.
Member Function Documentation
Double_t THSKinematics::CosTheta () inline
Definition at line 38 of file THSKinematics.h.
Double_t THSKinematics::Cosx () inline
Definition at line 86 of file THSKinematics.h.
Double_t THSKinematics::Cosy () inline
Definition at line 87 of file THSKinematics.h.
Double_t THSKinematics::Cosz () inline
Definition at line 88 of file THSKinematics.h.
References ElectroCMDecay(), LambdaDecay(), MesonDecayGJ(), MesonDecayHelicity(), PhotoCMDecay(), and PolPhotoCMDecay().
void THSKinematics::ElectroCMDecay () inline
Definition at line 110 of file THSKinematics.h.
Referenced by Cosz().
Double_t THSKinematics::ElScatTh () inline
Definition at line 73 of file THSKinematics.h.
Referenced by GammaPol().
TLorentzVector THSKinematics::Gamma () inline
Definition at line 68 of file THSKinematics.h.
Double_t THSKinematics::GammaE () inline
Definition at line 71 of file THSKinematics.h.
Referenced by GammaPol().
Double_t THSKinematics::GammaFlux () inline
Definition at line 75 of file THSKinematics.h.
References GammaPol(), Q2(), and W().
Double_t THSKinematics::GammaPol () inline
Definition at line 74 of file THSKinematics.h.
References ElScatTh(), GammaE(), and Q2().
Referenced by GammaFlux().
Double_t THSKinematics::GammaTh () inline
Definition at line 72 of file THSKinematics.h.
void THSKinematics::LambdaDecay () inline
Definition at line 208 of file THSKinematics.h.
Referenced by Cosz().
void THSKinematics::MesonDecayGJ () inline
Definition at line 193 of file THSKinematics.h.
Referenced by Cosz().
void THSKinematics::MesonDecayHelicity () inline
Definition at line 177 of file THSKinematics.h.
Referenced by Cosz().
Double_t THSKinematics::Phi () inline
Definition at line 39 of file THSKinematics.h.
void THSKinematics::PhotoCMDecay () inline
Definition at line 138 of file THSKinematics.h.
Referenced by Cosz().
void THSKinematics::PolPhotoCMDecay () inline
Definition at line 145 of file THSKinematics.h.
Referenced by Cosz().
Double_t THSKinematics::Q2 () inline
Definition at line 70 of file THSKinematics.h.
Referenced by GammaFlux(), and GammaPol().
void THSKinematics::SetBaryonDecay (TLorentzVector d1, TLorentzVector d2) inline
Definition at line 63 of file THSKinematics.h.
void THSKinematics::SetElecsTarget (TLorentzVector in, TLorentzVector sc, TLorentzVector tar) inline
Definition at line 42 of file THSKinematics.h.
void THSKinematics::SetGammaTarget (TLorentzVector gamma, TLorentzVector tar) inline
Definition at line 50 of file THSKinematics.h.
void THSKinematics::SetMesonBaryon (TLorentzVector mes, TLorentzVector bar) inline
Definition at line 55 of file THSKinematics.h.
void THSKinematics::SetMesonDecay (TLorentzVector d1, TLorentzVector d2) inline
Definition at line 59 of file THSKinematics.h.
void THSKinematics::SetTarget (TLorentzVector tar) inline
Definition at line 41 of file THSKinematics.h.
Double_t THSKinematics::t () inline
Definition at line 78 of file THSKinematics.h.
References t().
Referenced by t(), and t0().
Double_t THSKinematics::t (TLorentzVector p0, TLorentzVector p1) inline
Definition at line 79 of file THSKinematics.h.
Double_t THSKinematics::t0 () inline
Definition at line 83 of file THSKinematics.h.
References t0().
Referenced by t0().
Double_t THSKinematics::t0 (TLorentzVector p0, TLorentzVector p1) inline
Definition at line 98 of file THSKinematics.h.
References t(), and t0().
Double_t THSKinematics::W () inline
Definition at line 69 of file THSKinematics.h.
Referenced by GammaFlux().
The documentation for this class was generated from the following file:
HaSpect/THSKinematics.h