HASPECT6: THSHisto Class Reference
THSHisto Class Reference
Definition at line 35 of file THSHisto.h.
#include <THSHisto.h>
Public Member Functions
THSHisto (TTree *=0)
virtual ~THSHisto ()
virtual void InitialiseHisto (TList *input)
virtual void LoadCut (TString sCut)
virtual void LoadHistograms ()
virtual void ChangeNames ()
virtual TH1 * MapHist (TH1 *hist)
virtual TH1 * FindHist (TString hname)
virtual void OrganiseSavedHists (TFile *stdFile, TList *output)
void MakeAxisDir (Int_t iA, TDirectory *curDir)
virtual void HistogramList (TString sLabel)
virtual void FillHistograms (TString sCut)
void LoadWeights (TString fname, TString wname)
void LoadCutsForWeights ()
void FillCutsForWeights ()
void GetWeightEvent (Double_t id)
void SetWeight (TString species)
Public Attributes
THSWeights * fWeights =nullptr
Double_t fWeight =1
THSBins * fBins =nullptr
Protected Attributes
Bool_t fIsHisto =0
StrTH1_Map fHistNameMap
Vec_StrTH1 fVecHistCut
vector< Vec_StrTH1 > fVecHistBin
TString fCurrCut
Int_t fCurrBin = 0
vector< TString > fVecTypes
vector< TString > fVecCuts
vector< TString > fVecBinNames
map< TString, Int_t > fMapCuts
map< TString, TString > fBinMap
TObjArray * fBinEntryLists
Constructor & Destructor Documentation
THSHisto::THSHisto (TTree * = 0) inline
Definition at line 38 of file THSHisto.h.
virtual THSHisto::~THSHisto () inline virtual
Definition at line 39 of file THSHisto.h.
Member Function Documentation
void THSHisto::ChangeNames () virtual
Definition at line 131 of file THSHisto.C.
References fBinMap, fBins, fVecBinNames, THSBins::GetBinName(), and THSBins::GetN().
Referenced by InitialiseHisto().
void THSHisto::FillCutsForWeights ()
Definition at line 223 of file THSHisto.C.
References FillHistograms(), fWeights, THSWeights::GetSpecies(), and SetWeight().
virtual void THSHisto::FillHistograms (TString sCut) inline virtual
Definition at line 55 of file THSHisto.h.
Referenced by FillCutsForWeights().
TH1 * THSHisto::FindHist (TString hname) virtual
Definition at line 116 of file THSHisto.C.
References fCurrBin, fCurrCut, fMapCuts, fVecBinNames, and fVecHistBin.
void THSHisto::GetWeightEvent (Double_t id)
Definition at line 234 of file THSHisto.C.
References fWeights, and THSWeights::GetEntryBinarySearch().
virtual void THSHisto::HistogramList (TString sLabel) inline virtual
Definition at line 54 of file THSHisto.h.
Referenced by LoadHistograms().
void THSHisto::InitialiseHisto (TList * input) virtual
Definition at line 19 of file THSHisto.C.
References ChangeNames(), fBins, fIsHisto, and THSBins::InitialiseBins().
void THSHisto::LoadCut (TString sCut) virtual
Definition at line 26 of file THSHisto.C.
References fCurrCut, fMapCuts, and fVecCuts.
Referenced by LoadCutsForWeights().
void THSHisto::LoadCutsForWeights ()
Definition at line 215 of file THSHisto.C.
References fWeights, THSWeights::GetSpecies(), and LoadCut().
void THSHisto::LoadHistograms () virtual
Definition at line 36 of file THSHisto.C.
References fBins, fCurrBin, fCurrCut, fHistNameMap, fVecBinNames, fVecCuts, fVecHistBin, fVecHistCut, THSBins::GetN(), and HistogramList().
void THSHisto::LoadWeights (TString fname, TString wname)
Definition at line 202 of file THSHisto.C.
References fWeights.
void THSHisto::MakeAxisDir (Int_t iA, TDirectory * curDir)
Definition at line 299 of file THSHisto.C.
References fBins, THSBins::GetAxis(), THSBins::GetNAxis(), and THSBins::GetPartName().
Referenced by OrganiseSavedHists().
TH1 * THSHisto::MapHist (TH1 * hist) virtual
Definition at line 95 of file THSHisto.C.
References fCurrBin, fCurrCut, fHistNameMap, fVecBinNames, and fVecTypes.
void THSHisto::OrganiseSavedHists (TFile * stdFile, TList * output) virtual
Definition at line 240 of file THSHisto.C.
References fBins, fIsHisto, fVecBinNames, fVecCuts, fVecTypes, THSBins::GetBinName(), THSBins::GetN(), THSBins::InitialiseBins(), and MakeAxisDir().
void THSHisto::SetWeight (TString species)
Definition at line 237 of file THSHisto.C.
References fWeight, fWeights, and THSWeights::GetWeight().
Referenced by FillCutsForWeights().
Member Data Documentation
TObjArray* THSHisto::fBinEntryLists protected
Definition at line 78 of file THSHisto.h.
map< TString,TString > THSHisto::fBinMap protected
Definition at line 76 of file THSHisto.h.
Referenced by ChangeNames().
THSBins* THSHisto::fBins =nullptr
Definition at line 43 of file THSHisto.h.
Referenced by ChangeNames(), InitialiseHisto(), LoadHistograms(), MakeAxisDir(), and OrganiseSavedHists().
Int_t THSHisto::fCurrBin = 0 protected
Definition at line 71 of file THSHisto.h.
Referenced by FindHist(), LoadHistograms(), and MapHist().
TString THSHisto::fCurrCut protected
Definition at line 70 of file THSHisto.h.
Referenced by FindHist(), LoadCut(), LoadHistograms(), and MapHist().
StrTH1_Map THSHisto::fHistNameMap protected
Definition at line 66 of file THSHisto.h.
Referenced by LoadHistograms(), and MapHist().
Bool_t THSHisto::fIsHisto =0 protected
Definition at line 65 of file THSHisto.h.
Referenced by InitialiseHisto(), and OrganiseSavedHists().
map< TString, Int_t > THSHisto::fMapCuts protected
Definition at line 75 of file THSHisto.h.
Referenced by FindHist(), and LoadCut().
vector< TString > THSHisto::fVecBinNames protected
Definition at line 74 of file THSHisto.h.
Referenced by ChangeNames(), FindHist(), LoadHistograms(), MapHist(), and OrganiseSavedHists().
vector< TString > THSHisto::fVecCuts protected
Definition at line 73 of file THSHisto.h.
Referenced by LoadCut(), LoadHistograms(), and OrganiseSavedHists().
vector< Vec_StrTH1 > THSHisto::fVecHistBin protected
Definition at line 68 of file THSHisto.h.
Referenced by FindHist(), and LoadHistograms().
Vec_StrTH1 THSHisto::fVecHistCut protected
Definition at line 67 of file THSHisto.h.
Referenced by LoadHistograms().
vector< TString > THSHisto::fVecTypes protected
Definition at line 72 of file THSHisto.h.
Referenced by MapHist(), and OrganiseSavedHists().
Double_t THSHisto::fWeight =1
Definition at line 42 of file THSHisto.h.
Referenced by SetWeight().
THSWeights* THSHisto::fWeights =nullptr
Definition at line 41 of file THSHisto.h.
Referenced by FillCutsForWeights(), GetWeightEvent(), LoadCutsForWeights(), LoadWeights(), and SetWeight().
The documentation for this class was generated from the following files:
HaSpect/THSHisto.h
HaSpect/THSHisto.C