HASPECT6: THSRooFit Class Reference
THSRooFit Class Reference
Definition at line 31 of file THSRooFit.h.
#include <THSRooFit.h>
Public Member Functions
THSRooFit ()
THSRooFit (TString name)
THSRooFit (TString name, RooWorkspace *ws)
THSRooFit (THSRooFit *rf)
virtual ~THSRooFit ()
void LoadVariable (TString opt)
void LoadVariable (RooRealVar *var)
void LoadAuxVars (TString opt)
void LoadAuxVars (RooRealVar *var)
void LoadBinVars (TString opt, Int_t nbins, Double_t min, Double_t max)
void LoadBinVars (TString opt, Int_t nbins, Double_t *xbins)
void LoadSpeciesPDF (TString opt, Int_t Scale0=1)
void DefineSets ()
void LoadDataSet (TTree *tree, Bool_t toWS=kFALSE)
void LoadDataSet (RooAbsData *data, Bool_t toWS=kFALSE)
void LoadMCIntTree (TTree *tree)
void LoadMCGenTree (TTree *tree)
void LoadWeights (TString wfile, TString wname)
void LoadWeights (THSWeights *wts)
void SetDataWeight ()
void SetDataWeightFast ()
void LoadWorkSpace (RooWorkspace *ws, TString rfname="")
void LoadWorkSpaceData (RooWorkspace *ws, TString rfname="")
void TotalPDF ()
RooArgList GetVariables ()
RooRealVar * GetVariable (TString name)
RooRealVar * GetParameter (TString name)
RooArgList GetAuxVars ()
RooArgList GetBinVars ()
RooRealVar * GetAuxVar (TString name)
RooRealVar * GetBinVar (TString name)
RooRealVar * GetVar (TString name)
RooArgList GetYields ()
RooArgList * GetPDFsp ()
RooArgList * GetYieldsp ()
RooArgList GetPDFs ()
RooArgList GetParameters ()
RooArgList GetConstraints ()
RooAbsPdf * GetModel ()
RooAbsData * GetData ()
RooDataSet * GetDataSet ()
RooDataHist * GetDataHist ()
TList * GetFits ()
RooFitResult * GetResult ()
TList * GetPlots ()
void AddVariables (RooArgList list)
void AddAuxVars (RooArgList list)
void AddParameters (RooArgList list)
void AddYields (RooArgList list)
void AddGausConstraint (RooGaussian *pdf)
void AddFormulaConstraint (RooFormulaVar *formu)
void SetSingleSpecies (TString ssp)
void SetIDBranchName (TString str)
void CheckRange ()
void SetParVals (RooFitResult *res)
void SetParVals (RooArgList pars)
void RemoveDataSet ()
void CleanWSDataSets ()
void RemoveConstraints ()
TTree * GetTree ()
RooWorkspace * GetWorkSpace ()
void SetTree (TTree *tree)
void PlotDataModel ()
void PlotModel (TString varName, TString pdfName)
void Factory (TString opt)
void Fit (Bool_t randPar=kFALSE)
virtual Bool_t InitialiseFit ()
virtual THSRooFit * CreateSubFitBins (TTree *ctree, TString rfname, Bool_t CopyTree=kTRUE)
void SavePlots (TString filename)
virtual void FitMany (Int_t Nfits=1)
void FitSavedBins (Int_t Nfits)
void FitBatchBin (Int_t Nfits)
virtual void FitAndStudy (Int_t Nfits=1)
void RandomisePars ()
void MakeBins ()
void MakeBins (TTree *tree, TString name)
void MakeBinnedTrees (TTree *tree, TString name)
virtual void FitWithBins (Int_t Nfits=1)
THSBins * GetBins ()
void SetOutDir (TString name)
void SetBinDir (TString name)
void ConfigureSavedBins (TString dirname, TString pdfname="Data")
TString GetOutDir ()
TString GetBinDir ()
void WriteToFile (TString fname)
void SetBinnedFit (Bool_t bf=kTRUE)
void SetInWeights (THSWeights *wts)
void SetWeightName (TString WName)
virtual void DefaultFitOptions ()
void AddFitOption (RooCmdArg cmd)
RooLinkedList GetFitOptions ()
void SetPlot (Bool_t plot=kTRUE)
void StudyFit ()
void SetNStudyTrials (Int_t Nt)
void SetStudyPDF (TString pdfn)
void SetStudyPlot (Bool_t plot=kTRUE)
Protected Attributes
RooWorkspace * fWS =nullptr
RooArgList fVariables
RooArgList fAuxVars
RooArgList fBinVars
RooArgList fYields
RooArgList fPDFs
RooArgList fParameters
RooArgList fConstraints
RooRealVar * fID =nullptr
RooAbsPdf * fModel =nullptr
RooAbsData * fData =nullptr
TList * fCanvases =nullptr
TList * fHists =nullptr
TList * fRooFits =nullptr
TTree * fTree =nullptr
TTree * fMCIntTree =nullptr
// tree to be imported, don't save as part of class!
TTree * fMCGenTree =nullptr
//tree for calculating MC based NormInt
TString fIDBranchName ="DontHaveOneYet"
//tree for calculating MC based NormInt
TString fYld ="Yld_"
TString fSingleSp
TString fOutDir
TString fBinDir
TString fWeightName
TString fStudyPDF
RooFitResult * fResult =nullptr
THSWeights * fInWeights =nullptr
THSBins * fDataBins =nullptr
//input weights for dataset to be fitted
Bool_t fGotID =kFALSE
Bool_t fIsPlot =kTRUE
Bool_t fBinnedFit =kFALSE
Bool_t ftoWS =kFALSE
Bool_t fStudyPlot =kFALSE
Bool_t fOwnWorkSpace =kFALSE
Double_t fChi2 =0
Int_t fFiti =0
Int_t fNStudyTrials =0
RooLinkedList fFitOptions
Constructor & Destructor Documentation
THSRooFit::THSRooFit ()
Definition at line 25 of file THSRooFit.C.
Referenced by CreateSubFitBins(), and THSsPlot::THSsPlot().
THSRooFit::THSRooFit (TString name)
Definition at line 38 of file THSRooFit.C.
References fCanvases, fGotID, fHists, fOwnWorkSpace, fRooFits, and fWS.
THSRooFit::THSRooFit (TString name, RooWorkspace * ws)
Definition at line 27 of file THSRooFit.C.
References fCanvases, fHists, fOwnWorkSpace, fRooFits, and fWS.
THSRooFit::THSRooFit (THSRooFit * rf)
Definition at line 49 of file THSRooFit.C.
References THSBins::Clone(), fBinDir, fBinnedFit, fDataBins, fInWeights, fIsPlot, fNStudyTrials, fOutDir, fOwnWorkSpace, fSingleSp, fStudyPDF, fStudyPlot, fWeightName, GetBins(), GetWorkSpace(), and LoadWorkSpace().
THSRooFit::~THSRooFit () virtual
Definition at line 99 of file THSRooFit.C.
References fDataBins, fHists, fInWeights, fMCGenTree, fMCIntTree, fOwnWorkSpace, fResult, and fWS.
Member Function Documentation
void THSRooFit::AddAuxVars (RooArgList list) inline
Definition at line 119 of file THSRooFit.h.
void THSRooFit::AddFitOption (RooCmdArg cmd) inline
Definition at line 170 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), CreateSubFitBins(), THSsPlot::DefaultFitOptions(), DefaultFitOptions(), Fit(), FitAndStudy(), RooHS1StepStudy::initialize(), RooHSsPlotAndFitStudy::initialize(), and TotalPDF().
void THSRooFit::AddFormulaConstraint (RooFormulaVar * formu) inline
Definition at line 123 of file THSRooFit.h.
void THSRooFit::AddGausConstraint (RooGaussian * pdf) inline
Definition at line 122 of file THSRooFit.h.
void THSRooFit::AddParameters (RooArgList list) inline
Definition at line 120 of file THSRooFit.h.
void THSRooFit::AddVariables (RooArgList list) inline
Definition at line 118 of file THSRooFit.h.
void THSRooFit::AddYields (RooArgList list) inline
Definition at line 121 of file THSRooFit.h.
void THSRooFit::CheckRange ()
Definition at line 311 of file THSRooFit.C.
References fData, and fVariables.
void THSRooFit::CleanWSDataSets ()
Definition at line 131 of file THSRooFit.C.
References fWS.
Referenced by RooHS1StepStudy::execute(), and RooHSsPlotAndFitStudy::execute().
void THSRooFit::ConfigureSavedBins (TString dirname, TString pdfname = "Data")
Definition at line 668 of file THSRooFit.C.
References fBinDir, fDataBins, and THSBins::GetN().
THSRooFit * THSRooFit::CreateSubFitBins (TTree * ctree, TString rfname, Bool_t CopyTree = kTRUE) virtual
Reimplemented in THSsPlot.
Definition at line 574 of file THSRooFit.C.
References AddFitOption(), fBinDir, fBinnedFit, fFitOptions, fInWeights, fNStudyTrials, fOutDir, fRooFits, fSingleSp, fStudyPDF, fStudyPlot, fWeightName, fWS, LoadDataSet(), LoadWorkSpace(), SetBinDir(), SetBinnedFit(), SetDataWeight(), SetInWeights(), SetNStudyTrials(), SetOutDir(), SetSingleSpecies(), SetStudyPDF(), SetStudyPlot(), SetWeightName(), and THSRooFit().
Referenced by FitSavedBins(), and FitWithBins().
void THSRooFit::DefaultFitOptions () virtual
Reimplemented in THSsPlot.
Definition at line 978 of file THSRooFit.C.
References AddFitOption().
Referenced by Fit().
void THSRooFit::DefineSets ()
Definition at line 189 of file THSRooFit.C.
References fAuxVars, fBinVars, fConstraints, fParameters, fPDFs, fVariables, fWS, and fYields.
Referenced by THSsPlot::FitAndStudy(), FitAndStudy(), FitBatchBin(), FitMany(), FitSavedBins(), FitWithBins(), LoadWorkSpace(), and StudyFit().
void THSRooFit::Factory (TString opt) inline
Examples:
FitHSSimple.C.
Definition at line 142 of file THSRooFit.h.
void THSRooFit::Fit (Bool_t randPar = kFALSE)
Definition at line 361 of file THSRooFit.C.
References AddFitOption(), DefaultFitOptions(), fBinnedFit, fConstraints, fData, fFiti, fFitOptions, fModel, fResult, fVariables, fWS, fYields, and RandomisePars().
Referenced by RooHS1StepStudy::execute(), RooHSsPlotAndFitStudy::execute(), FitAndStudy(), and FitMany().
void THSRooFit::FitAndStudy (Int_t Nfits = 1) virtual
Reimplemented in THSsPlot.
Definition at line 776 of file THSRooFit.C.
References AddFitOption(), DefineSets(), fData, Fit(), FitMany(), fOutDir, fWS, GetFitOptions(), SavePlots(), and StudyFit().
Referenced by FitBatchBin(), and FitSavedBins().
void THSRooFit::FitBatchBin (Int_t Nfits)
Definition at line 739 of file THSRooFit.C.
References RooHSEventsPDF::AddProtoData(), DefineSets(), fBinDir, FitAndStudy(), fPDFs, fWS, GetBinDir(), GetDataSet(), LoadDataSet(), SetDataWeight(), and RooHSEventsPDF::SetEvTree().
void THSRooFit::FitMany (Int_t Nfits = 1) virtual
Definition at line 814 of file THSRooFit.C.
References DefineSets(), fBinnedFit, fChi2, fIsPlot, Fit(), fModel, fParameters, fPDFs, fResult, fWS, fYields, and PlotDataModel().
Referenced by THSsPlot::FitAndStudy(), FitAndStudy(), and FitWithBins().
void THSRooFit::FitSavedBins (Int_t Nfits)
Definition at line 702 of file THSRooFit.C.
References RooHSEventsPDF::AddProtoData(), CreateSubFitBins(), DefineSets(), fBinDir, fDataBins, FitAndStudy(), fModel, fPDFs, fWS, GetBinDir(), THSBins::GetBinName(), GetBins(), GetDataSet(), THSBins::GetN(), GetWorkSpace(), RooHSEventsPDF::ResetTree(), RooHSEventsPDF::SetEvTree(), and TotalPDF().
void THSRooFit::FitWithBins (Int_t Nfits = 1) virtual
??delete savedBins;
Definition at line 675 of file THSRooFit.C.
References CreateSubFitBins(), DefineSets(), fDataBins, fIDBranchName, FitMany(), fModel, fOutDir, fTree, fVariables, fWS, THSBins::GetBinName(), THSBins::GetBinnedTree(), THSBins::GetN(), MakeBins(), SavePlots(), and TotalPDF().
RooRealVar* THSRooFit::GetAuxVar (TString name) inline
Definition at line 102 of file THSRooFit.h.
Referenced by GetVar().
RooArgList THSRooFit::GetAuxVars () inline
Definition at line 100 of file THSRooFit.h.
TString THSRooFit::GetBinDir () inline
Definition at line 164 of file THSRooFit.h.
Referenced by FitBatchBin(), and FitSavedBins().
THSBins* THSRooFit::GetBins () inline
Definition at line 159 of file THSRooFit.h.
Referenced by FitSavedBins(), and THSRooFit().
RooRealVar* THSRooFit::GetBinVar (TString name) inline
Definition at line 103 of file THSRooFit.h.
RooArgList THSRooFit::GetBinVars () inline
Definition at line 101 of file THSRooFit.h.
RooArgList THSRooFit::GetConstraints () inline
Definition at line 110 of file THSRooFit.h.
RooAbsData* THSRooFit::GetData () inline
Definition at line 112 of file THSRooFit.h.
RooDataHist* THSRooFit::GetDataHist () inline
Definition at line 114 of file THSRooFit.h.
RooDataSet* THSRooFit::GetDataSet () inline
Definition at line 113 of file THSRooFit.h.
Referenced by FitBatchBin(), FitSavedBins(), and InitialiseFit().
RooLinkedList THSRooFit::GetFitOptions () inline
Definition at line 171 of file THSRooFit.h.
Referenced by FitAndStudy().
TList* THSRooFit::GetFits () inline
Definition at line 115 of file THSRooFit.h.
RooAbsPdf* THSRooFit::GetModel () inline
Definition at line 111 of file THSRooFit.h.
Referenced by RooHS1StepStudy::execute(), and RooHSsPlotAndFitStudy::execute().
TString THSRooFit::GetOutDir () inline
Definition at line 163 of file THSRooFit.h.
Referenced by StudyFit().
RooRealVar* THSRooFit::GetParameter (TString name) inline
Definition at line 99 of file THSRooFit.h.
RooArgList THSRooFit::GetParameters () inline
Definition at line 109 of file THSRooFit.h.
Referenced by RooHS1StepStudy::finalize(), RooHS1StepStudy::initialize(), RooHSsPlotAndFitStudy::initialize(), and RooHSsPlotAndFitStudy::terminate().
RooArgList THSRooFit::GetPDFs () inline
Definition at line 108 of file THSRooFit.h.
Referenced by THSsPlot::FitAndStudy(), and InitialiseFit().
RooArgList* THSRooFit::GetPDFsp () inline
Definition at line 106 of file THSRooFit.h.
Referenced by THSsPlot::FitAndStudy().
TList* THSRooFit::GetPlots () inline
Definition at line 117 of file THSRooFit.h.
Referenced by RooHS1StepStudy::execute().
RooFitResult* THSRooFit::GetResult () inline
Definition at line 116 of file THSRooFit.h.
Referenced by RooHS1StepStudy::execute(), and RooHSsPlotAndFitStudy::execute().
TTree* THSRooFit::GetTree () inline
Definition at line 137 of file THSRooFit.h.
RooRealVar * THSRooFit::GetVar (TString name)
Definition at line 329 of file THSRooFit.C.
References GetAuxVar(), and GetVariable().
RooRealVar* THSRooFit::GetVariable (TString name) inline
Definition at line 98 of file THSRooFit.h.
Referenced by GetVar().
RooArgList THSRooFit::GetVariables () inline
Definition at line 97 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), RooHS1StepStudy::execute(), and RooHSsPlotAndFitStudy::execute().
RooWorkspace* THSRooFit::GetWorkSpace () inline
Definition at line 138 of file THSRooFit.h.
Referenced by RooHS1StepStudy::attach(), FitSavedBins(), RooHS1StepStudy::RooHS1StepStudy(), RooHSsPlotAndFitStudy::RooHSsPlotAndFitStudy(), RooHS1StepStudy::SetHSRooFit(), RooHSsPlotAndFitStudy::terminate(), and THSRooFit().
RooArgList THSRooFit::GetYields () inline
Definition at line 105 of file THSRooFit.h.
Referenced by THSsPlot::FitAndStudy(), RooHS1StepStudy::initialize(), and RooHSsPlotAndFitStudy::initialize().
RooArgList* THSRooFit::GetYieldsp () inline
Definition at line 107 of file THSRooFit.h.
Referenced by THSsPlot::FitAndStudy().
Bool_t THSRooFit::InitialiseFit () virtual
Definition at line 968 of file THSRooFit.C.
References GetDataSet(), and GetPDFs().
void THSRooFit::LoadAuxVars (TString opt)
Examples:
FitHSSimple.C.
Definition at line 290 of file THSRooFit.C.
References fAuxVars, and fWS.
void THSRooFit::LoadAuxVars (RooRealVar * var) inline
Definition at line 81 of file THSRooFit.h.
void THSRooFit::LoadBinVars (TString opt, Int_t nbins, Double_t min, Double_t max)
Definition at line 293 of file THSRooFit.C.
References THSBins::AddAxis(), fBinVars, fDataBins, and fWS.
void THSRooFit::LoadBinVars (TString opt, Int_t nbins, Double_t * xbins)
Definition at line 302 of file THSRooFit.C.
References THSBins::AddAxis(), fBinVars, fDataBins, and fWS.
void THSRooFit::LoadDataSet (TTree * tree, Bool_t toWS = kFALSE)
Examples:
FitHSSimple.C.
Definition at line 111 of file THSRooFit.C.
References fAuxVars, fData, fDataBins, fID, fInWeights, ftoWS, fTree, fVariables, and fWS.
Referenced by THSsPlot::CreateSubFitBins(), CreateSubFitBins(), RooHS1StepStudy::execute(), RooHSsPlotAndFitStudy::execute(), FitBatchBin(), and LoadWorkSpaceData().
void THSRooFit::LoadDataSet (RooAbsData * data, Bool_t toWS = kFALSE)
Definition at line 138 of file THSRooFit.C.
References fData, fDataBins, fInWeights, ftoWS, and fWS.
void THSRooFit::LoadMCGenTree (TTree * tree) inline
Definition at line 89 of file THSRooFit.h.
void THSRooFit::LoadMCIntTree (TTree * tree) inline
Definition at line 88 of file THSRooFit.h.
void THSRooFit::LoadSpeciesPDF (TString opt, Int_t Scale0 = 1)
Examples:
FitHSSimple.C.
Definition at line 336 of file THSRooFit.C.
References fAuxVars, fParameters, fPDFs, fVariables, fWS, fYields, and fYld.
void THSRooFit::LoadVariable (TString opt)
Examples:
FitHSSimple.C.
Definition at line 284 of file THSRooFit.C.
References fVariables, and fWS.
void THSRooFit::LoadVariable (RooRealVar * var) inline
Definition at line 79 of file THSRooFit.h.
void THSRooFit::LoadWeights (TString wfile, TString wname)
Definition at line 214 of file THSRooFit.C.
References fInWeights, THSWeights::LoadSaved(), and THSWeights::PrintWeight().
Referenced by RooHS1StepStudy::execute(), and RooHSsPlotAndFitStudy::execute().
void THSRooFit::LoadWeights (THSWeights * wts) inline
Definition at line 91 of file THSRooFit.h.
void THSRooFit::LoadWorkSpace (RooWorkspace * ws, TString rfname = "")
Definition at line 154 of file THSRooFit.C.
References DefineSets(), fAuxVars, fBinVars, fConstraints, fGotID, fID, fIDBranchName, fModel, fOwnWorkSpace, fParameters, fPDFs, fVariables, fWS, and fYields.
Referenced by RooHS1StepStudy::attach(), RooHSsPlotAndFitStudy::attach(), THSsPlot::CreateSubFitBins(), CreateSubFitBins(), LoadWorkSpaceData(), and THSRooFit().
void THSRooFit::LoadWorkSpaceData (RooWorkspace * ws, TString rfname = "")
Definition at line 150 of file THSRooFit.C.
References LoadDataSet(), and LoadWorkSpace().
void THSRooFit::MakeBinnedTrees (TTree * tree, TString name)
Definition at line 640 of file THSRooFit.C.
References fAuxVars, fIDBranchName, fOutDir, fVariables, THSBins::GetBinName(), THSBins::GetBinnedTree(), THSBins::GetN(), and MakeBins().
void THSRooFit::MakeBins ()
Definition at line 615 of file THSRooFit.C.
References fDataBins, fMCGenTree, fMCIntTree, fOutDir, fTree, THSBins::InitialiseBinTree(), THSBins::RunBinTree(), and THSBins::Save().
Referenced by FitWithBins(), and MakeBinnedTrees().
void THSRooFit::MakeBins (TTree * tree, TString name)
Definition at line 634 of file THSRooFit.C.
References fDataBins, fOutDir, THSBins::InitialiseBinTree(), THSBins::RunBinTree(), and THSBins::Save().
void THSRooFit::PlotDataModel ()
Definition at line 467 of file THSRooFit.C.
References fCanvases, fChi2, fData, fFiti, fModel, fPDFs, fVariables, and fWS.
Referenced by RooHS1StepStudy::execute(), FitMany(), and THSsPlot::sPlot().
void THSRooFit::PlotModel (TString varName, TString pdfName)
Definition at line 450 of file THSRooFit.C.
References fCanvases, and fWS.
void THSRooFit::RandomisePars ()
Definition at line 424 of file THSRooFit.C.
References fConstraints, and fParameters.
Referenced by Fit().
void THSRooFit::RemoveConstraints () inline
Definition at line 136 of file THSRooFit.h.
void THSRooFit::RemoveDataSet ()
Definition at line 125 of file THSRooFit.C.
References fData, and fTree.
Referenced by RooHS1StepStudy::execute(), and RooHSsPlotAndFitStudy::execute().
void THSRooFit::SavePlots (TString filename)
Definition at line 605 of file THSRooFit.C.
References fCanvases, fOutDir, and fResult.
Referenced by RooHS1StepStudy::execute(), THSsPlot::FitAndStudy(), FitAndStudy(), and FitWithBins().
void THSRooFit::SetBinDir (TString name) inline
Definition at line 161 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), and CreateSubFitBins().
void THSRooFit::SetBinnedFit (Bool_t bf = kTRUE) inline
Examples:
FitHSSimple.C.
Definition at line 166 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), and CreateSubFitBins().
void THSRooFit::SetDataWeight ()
Definition at line 224 of file THSRooFit.C.
References fData, fDataBins, fIDBranchName, fInWeights, ftoWS, fWeightName, fWS, THSWeights::GetEntryBinarySearch(), THSWeights::GetSpeciesID(), and THSWeights::GetWeight().
Referenced by THSsPlot::CreateSubFitBins(), CreateSubFitBins(), FitBatchBin(), and THSsPlot::sPlot().
void THSRooFit::SetDataWeightFast ()
Definition at line 253 of file THSRooFit.C.
References fData, fDataBins, fInWeights, ftoWS, fWeightName, fWS, THSWeights::GetSpeciesID(), and THSWeights::GetTree().
Referenced by RooHS1StepStudy::execute(), and RooHSsPlotAndFitStudy::execute().
void THSRooFit::SetIDBranchName (TString str) inline
Definition at line 125 of file THSRooFit.h.
void THSRooFit::SetInWeights (THSWeights * wts) inline
Definition at line 167 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), and CreateSubFitBins().
void THSRooFit::SetNStudyTrials (Int_t Nt) inline
Definition at line 175 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), and CreateSubFitBins().
void THSRooFit::SetOutDir (TString name) inline
Examples:
FitHSSimple.C.
Definition at line 160 of file THSRooFit.h.
Referenced by RooHS1StepStudy::attach(), RooHSsPlotAndFitStudy::attach(), THSsPlot::CreateSubFitBins(), and CreateSubFitBins().
void THSRooFit::SetParVals (RooFitResult * res)
Definition at line 201 of file THSRooFit.C.
void THSRooFit::SetParVals (RooArgList pars)
Definition at line 204 of file THSRooFit.C.
References fParameters.
void THSRooFit::SetPlot (Bool_t plot = kTRUE) inline
Definition at line 172 of file THSRooFit.h.
Referenced by RooHSsPlotAndFitStudy::attach(), and RooHSsPlotAndFitStudy::execute().
void THSRooFit::SetSingleSpecies (TString ssp) inline
Definition at line 124 of file THSRooFit.h.
Referenced by CreateSubFitBins().
void THSRooFit::SetStudyPDF (TString pdfn) inline
Definition at line 176 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), and CreateSubFitBins().
void THSRooFit::SetStudyPlot (Bool_t plot = kTRUE) inline
Definition at line 177 of file THSRooFit.h.
Referenced by CreateSubFitBins().
void THSRooFit::SetTree (TTree * tree) inline
Definition at line 139 of file THSRooFit.h.
void THSRooFit::SetWeightName (TString WName)
Definition at line 279 of file THSRooFit.C.
References fInWeights, fWeightName, and THSWeights::GetSpeciesID().
Referenced by THSsPlot::CreateSubFitBins(), CreateSubFitBins(), RooHS1StepStudy::execute(), and RooHSsPlotAndFitStudy::execute().
void THSRooFit::StudyFit ()
Definition at line 797 of file THSRooFit.C.
References DefineSets(), fBinnedFit, fFitOptions, fNStudyTrials, fStudyPDF, fStudyPlot, fWS, and GetOutDir().
Referenced by THSsPlot::FitAndStudy(), and FitAndStudy().
void THSRooFit::TotalPDF ()
Definition at line 345 of file THSRooFit.C.
References AddFitOption(), fModel, fPDFs, fWS, and fYields.
Referenced by RooHS1StepStudy::attach(), RooHSsPlotAndFitStudy::attach(), THSsPlot::FitAndStudy(), FitSavedBins(), FitWithBins(), and THSsPlot::MergeModelSpecies().
void THSRooFit::WriteToFile (TString fname)
Definition at line 961 of file THSRooFit.C.
Member Data Documentation
RooArgList THSRooFit::fAuxVars protected
Definition at line 35 of file THSRooFit.h.
Referenced by DefineSets(), LoadAuxVars(), LoadDataSet(), LoadSpeciesPDF(), LoadWorkSpace(), MakeBinnedTrees(), and THSsPlot::sPlot().
TString THSRooFit::fBinDir protected
Definition at line 54 of file THSRooFit.h.
Referenced by ConfigureSavedBins(), THSsPlot::CreateSubFitBins(), CreateSubFitBins(), FitBatchBin(), FitSavedBins(), and THSRooFit().
Bool_t THSRooFit::fBinnedFit =kFALSE protected
Definition at line 62 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), CreateSubFitBins(), Fit(), FitMany(), StudyFit(), and THSRooFit().
RooArgList THSRooFit::fBinVars protected
Definition at line 36 of file THSRooFit.h.
Referenced by DefineSets(), LoadBinVars(), and LoadWorkSpace().
TList* THSRooFit::fCanvases =nullptr protected
Definition at line 44 of file THSRooFit.h.
Referenced by THSsPlot::DrawTreeVar(), PlotDataModel(), PlotModel(), SavePlots(), THSsPlot::sPlot(), and THSRooFit().
Double_t THSRooFit::fChi2 =0 protected
Definition at line 66 of file THSRooFit.h.
Referenced by FitMany(), PlotDataModel(), and THSsPlot::sPlot().
RooArgList THSRooFit::fConstraints protected
Definition at line 40 of file THSRooFit.h.
Referenced by DefineSets(), Fit(), LoadWorkSpace(), and RandomisePars().
RooAbsData* THSRooFit::fData =nullptr protected
Definition at line 43 of file THSRooFit.h.
Referenced by CheckRange(), THSsPlot::ExportTreeWeights(), THSsPlot::ExportWeights(), THSsPlot::ExportWeights1(), Fit(), FitAndStudy(), LoadDataSet(), PlotDataModel(), RemoveDataSet(), SetDataWeight(), SetDataWeightFast(), and THSsPlot::sPlot().
THSBins* THSRooFit::fDataBins =nullptr protected
//input weights for dataset to be fitted
Definition at line 59 of file THSRooFit.h.
Referenced by ConfigureSavedBins(), FitSavedBins(), FitWithBins(), LoadBinVars(), LoadDataSet(), MakeBins(), SetDataWeight(), SetDataWeightFast(), THSRooFit(), and ~THSRooFit().
Int_t THSRooFit::fFiti =0 protected
Definition at line 67 of file THSRooFit.h.
Referenced by Fit(), PlotDataModel(), and THSsPlot::sPlot().
RooLinkedList THSRooFit::fFitOptions protected
Definition at line 70 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), CreateSubFitBins(), Fit(), and StudyFit().
Bool_t THSRooFit::fGotID =kFALSE protected
Definition at line 60 of file THSRooFit.h.
Referenced by THSsPlot::DrawTreeVar(), THSsPlot::ExportTreeWeights(), THSsPlot::ExportWeights(), THSsPlot::ExportWeights1(), LoadWorkSpace(), THSsPlot::sPlot(), and THSRooFit().
TList* THSRooFit::fHists =nullptr protected
Definition at line 45 of file THSRooFit.h.
Referenced by THSsPlot::DrawTreeVar(), THSsPlot::SaveHists(), THSRooFit(), and ~THSRooFit().
RooRealVar* THSRooFit::fID =nullptr protected
Definition at line 41 of file THSRooFit.h.
Referenced by LoadDataSet(), LoadWorkSpace(), and THSsPlot::sPlot().
TString THSRooFit::fIDBranchName ="DontHaveOneYet" protected
//tree for calculating MC based NormInt
Definition at line 50 of file THSRooFit.h.
Referenced by THSsPlot::DrawTreeVar(), THSsPlot::ExportTreeWeights(), THSsPlot::ExportWeights(), THSsPlot::ExportWeights1(), FitWithBins(), LoadWorkSpace(), MakeBinnedTrees(), SetDataWeight(), and THSsPlot::sPlot().
THSWeights* THSRooFit::fInWeights =nullptr protected
Definition at line 58 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), CreateSubFitBins(), LoadDataSet(), LoadWeights(), SetDataWeight(), SetDataWeightFast(), SetWeightName(), THSsPlot::sPlot(), THSRooFit(), and ~THSRooFit().
Bool_t THSRooFit::fIsPlot =kTRUE protected
Definition at line 61 of file THSRooFit.h.
Referenced by FitMany(), THSsPlot::sPlot(), and THSRooFit().
TTree* THSRooFit::fMCGenTree =nullptr protected
//tree for calculating MC based NormInt
Definition at line 49 of file THSRooFit.h.
Referenced by MakeBins(), and ~THSRooFit().
TTree* THSRooFit::fMCIntTree =nullptr protected
// tree to be imported, don't save as part of class!
Definition at line 48 of file THSRooFit.h.
Referenced by MakeBins(), and ~THSRooFit().
RooAbsPdf* THSRooFit::fModel =nullptr protected
Definition at line 42 of file THSRooFit.h.
Referenced by Fit(), THSsPlot::FitAndStudy(), FitMany(), FitSavedBins(), FitWithBins(), LoadWorkSpace(), THSsPlot::MergeModelSpecies(), PlotDataModel(), THSsPlot::sPlot(), and TotalPDF().
Int_t THSRooFit::fNStudyTrials =0 protected
Definition at line 68 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), CreateSubFitBins(), StudyFit(), and THSRooFit().
TString THSRooFit::fOutDir protected
Definition at line 53 of file THSRooFit.h.
Referenced by THSsPlot::AddWeightMap(), THSsPlot::CreateSubFitBins(), CreateSubFitBins(), THSsPlot::DrawTreeVar(), THSsPlot::FitAndStudy(), FitAndStudy(), FitWithBins(), MakeBinnedTrees(), MakeBins(), SavePlots(), THSsPlot::sPlot(), and THSRooFit().
Bool_t THSRooFit::fOwnWorkSpace =kFALSE protected
Definition at line 65 of file THSRooFit.h.
Referenced by LoadWorkSpace(), THSRooFit(), and ~THSRooFit().
RooArgList THSRooFit::fParameters protected
Definition at line 39 of file THSRooFit.h.
Referenced by DefineSets(), FitMany(), LoadSpeciesPDF(), LoadWorkSpace(), RandomisePars(), SetParVals(), and THSsPlot::sPlot().
RooArgList THSRooFit::fPDFs protected
Definition at line 38 of file THSRooFit.h.
Referenced by DefineSets(), FitBatchBin(), FitMany(), FitSavedBins(), LoadSpeciesPDF(), LoadWorkSpace(), THSsPlot::MergeModelSpecies(), PlotDataModel(), and TotalPDF().
RooFitResult* THSRooFit::fResult =nullptr protected
Definition at line 57 of file THSRooFit.h.
Referenced by Fit(), FitMany(), SavePlots(), and ~THSRooFit().
TList* THSRooFit::fRooFits =nullptr protected
Definition at line 46 of file THSRooFit.h.
Referenced by THSsPlot::AddSubWeights(), THSsPlot::CreateSubFitBins(), CreateSubFitBins(), and THSRooFit().
TString THSRooFit::fSingleSp protected
Definition at line 52 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), CreateSubFitBins(), THSsPlot::MergeModelSpecies(), THSsPlot::sPlot(), and THSRooFit().
TString THSRooFit::fStudyPDF protected
Definition at line 56 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), CreateSubFitBins(), StudyFit(), and THSRooFit().
Bool_t THSRooFit::fStudyPlot =kFALSE protected
Definition at line 64 of file THSRooFit.h.
Referenced by CreateSubFitBins(), StudyFit(), and THSRooFit().
Bool_t THSRooFit::ftoWS =kFALSE protected
Definition at line 63 of file THSRooFit.h.
Referenced by LoadDataSet(), SetDataWeight(), and SetDataWeightFast().
TTree* THSRooFit::fTree =nullptr protected
Definition at line 47 of file THSRooFit.h.
Referenced by THSsPlot::DrawTreeVar(), THSsPlot::ExportTreeWeights(), FitWithBins(), LoadDataSet(), MakeBins(), RemoveDataSet(), and THSsPlot::sPlot().
RooArgList THSRooFit::fVariables protected
Definition at line 34 of file THSRooFit.h.
Referenced by CheckRange(), DefineSets(), Fit(), FitWithBins(), LoadDataSet(), LoadSpeciesPDF(), LoadVariable(), LoadWorkSpace(), MakeBinnedTrees(), THSsPlot::MergeModelSpecies(), PlotDataModel(), and THSsPlot::sPlot().
TString THSRooFit::fWeightName protected
Definition at line 55 of file THSRooFit.h.
Referenced by THSsPlot::CreateSubFitBins(), CreateSubFitBins(), SetDataWeight(), SetDataWeightFast(), SetWeightName(), and THSRooFit().
RooWorkspace* THSRooFit::fWS =nullptr protected
Definition at line 33 of file THSRooFit.h.
Referenced by CleanWSDataSets(), THSsPlot::CreateSubFitBins(), CreateSubFitBins(), DefineSets(), Fit(), THSsPlot::FitAndStudy(), FitAndStudy(), FitBatchBin(), FitMany(), FitSavedBins(), FitWithBins(), LoadAuxVars(), LoadBinVars(), LoadDataSet(), LoadSpeciesPDF(), LoadVariable(), LoadWorkSpace(), THSsPlot::MergeModelSpecies(), PlotDataModel(), PlotModel(), SetDataWeight(), SetDataWeightFast(), StudyFit(), THSRooFit(), TotalPDF(), and ~THSRooFit().
RooArgList THSRooFit::fYields protected
Definition at line 37 of file THSRooFit.h.
Referenced by DefineSets(), THSsPlot::ExportTreeWeights(), THSsPlot::ExportWeights(), THSsPlot::ExportWeights1(), Fit(), THSsPlot::FitAndStudy(), FitMany(), LoadSpeciesPDF(), LoadWorkSpace(), THSsPlot::MergeModelSpecies(), THSsPlot::sPlot(), and TotalPDF().
TString THSRooFit::fYld ="Yld_" protected
Definition at line 51 of file THSRooFit.h.
Referenced by LoadSpeciesPDF(), and THSsPlot::MergeModelSpecies().
The documentation for this class was generated from the following files:
HaSpect/THSRooFit.h
HaSpect/THSRooFit.C