HASPECT6: THSIsobarPS Class Reference
THSIsobarPS Class Reference
Definition at line 17 of file THSIsobarPS.h.
#include <THSIsobarPS.h>
Public Member Functions
THSIsobarPS ()
THSIsobarPS (Int_t Np)
virtual ~THSIsobarPS ()
Bool_t IsIsobar (TLorentzVector z0, TLorentzVector d1, TLorentzVector d2, TLorentzVector fixCM=TLorentzVector())
Double_t breakupMomentum (double mass0, double mass1, double mass2)
Double_t BetaPM (double p0, double m0)
Double_t GetOmega ()
Double_t GetCosTh ()
Double_t GetCosHel ()
Int_t GetSector ()
Int_t GetNSector ()
Protected Attributes
UInt_t fSector
UInt_t fNSector
Double_t fCosTh
Double_t fCosHel
Double_t fOmega
Constructor & Destructor Documentation
THSIsobarPS::THSIsobarPS () inline
Definition at line 25 of file THSIsobarPS.h.
THSIsobarPS::THSIsobarPS (Int_t Np)
Definition at line 11 of file THSIsobarPS.C.
virtual THSIsobarPS::~THSIsobarPS () inline virtual
Definition at line 27 of file THSIsobarPS.h.
References BetaPM(), breakupMomentum(), and IsIsobar().
Member Function Documentation
Double_t THSIsobarPS::BetaPM (double p0, double m0)
Definition at line 144 of file THSIsobarPS.C.
Referenced by ~THSIsobarPS().
Double_t THSIsobarPS::breakupMomentum (double mass0, double mass1, double mass2)
Definition at line 154 of file THSIsobarPS.C.
Referenced by IsIsobar(), and ~THSIsobarPS().
Double_t THSIsobarPS::GetCosHel () inline
Definition at line 34 of file THSIsobarPS.h.
References fCosHel.
Double_t THSIsobarPS::GetCosTh () inline
Definition at line 33 of file THSIsobarPS.h.
References fCosTh.
Int_t THSIsobarPS::GetNSector () inline
Definition at line 36 of file THSIsobarPS.h.
References fNSector.
Double_t THSIsobarPS::GetOmega () inline
Definition at line 32 of file THSIsobarPS.h.
References fOmega.
Int_t THSIsobarPS::GetSector () inline
Definition at line 35 of file THSIsobarPS.h.
References fSector.
Bool_t THSIsobarPS::IsIsobar (TLorentzVector z0, TLorentzVector d1, TLorentzVector d2, TLorentzVector fixCM = TLorentzVector())
Definition at line 33 of file THSIsobarPS.C.
References breakupMomentum(), fCosHel, fCosTh, and fOmega.
Referenced by ~THSIsobarPS().
Member Data Documentation
Double_t THSIsobarPS::fCosHel protected
Definition at line 22 of file THSIsobarPS.h.
Referenced by GetCosHel(), and IsIsobar().
Double_t THSIsobarPS::fCosTh protected
Definition at line 21 of file THSIsobarPS.h.
Referenced by GetCosTh(), and IsIsobar().
UInt_t THSIsobarPS::fNSector protected
Definition at line 20 of file THSIsobarPS.h.
Referenced by GetNSector().
Double_t THSIsobarPS::fOmega protected
Definition at line 23 of file THSIsobarPS.h.
Referenced by GetOmega(), and IsIsobar().
UInt_t THSIsobarPS::fSector protected
Definition at line 19 of file THSIsobarPS.h.
Referenced by GetSector().
The documentation for this class was generated from the following files:
HaSpect/THSIsobarPS.h
HaSpect/THSIsobarPS.C