HASPECT6: THSDataReader Class Reference
THSDataReader Class Reference
Definition at line 15 of file THSDataReader.h.
#include <THSDataReader.h>
Public Member Functions
THSDataReader ()
~THSDataReader ()
virtual Bool_t Init (TString filename, TString name="")
virtual Bool_t ReadEvent (Long64_t entry=-1)
virtual void PrintEvent (Long64_t=0)
virtual void WriteParticles (TString filename)
Int_t GetN ()
THSParticle * GetParticle (Int_t i)
void AddParticle (THSParticle *part)
void SetReadBranch (TString name)
void InitOutput (TString filename)
void WriteEvent ()
void CloseOutput ()
Protected Attributes
vector< THSParticle * > fParticles
vector< THSParticle * > * fReadParticles
Int_t fNin
TFile * fReadFile =0
TTree * fReadTree =0
Long64_t fEntry =0
TString fReadBName ="Particles"
TFile * fWriteFile =0
TTree * fWriteTree =0
Constructor & Destructor Documentation
THSDataReader::THSDataReader () inline
Definition at line 18 of file THSDataReader.h.
References Init(), PrintEvent(), ReadEvent(), WriteParticles(), and ~THSDataReader().
THSDataReader::~THSDataReader ()
Definition at line 4 of file THSDataReader.C.
References fParticles, fReadFile, and fReadTree.
Referenced by THSDataReader().
Member Function Documentation
void THSDataReader::AddParticle (THSParticle * part) inline
Definition at line 27 of file THSDataReader.h.
References fNin, and fParticles.
void THSDataReader::CloseOutput ()
Definition at line 72 of file THSDataReader.C.
References fWriteFile, and fWriteTree.
Referenced by WriteEvent(), and WriteParticles().
Int_t THSDataReader::GetN () inline
Definition at line 25 of file THSDataReader.h.
References fNin.
THSParticle* THSDataReader::GetParticle (Int_t i) inline
Definition at line 26 of file THSDataReader.h.
References fParticles.
Bool_t THSDataReader::Init (TString filename, TString name = "") virtual
Definition at line 18 of file THSDataReader.C.
References fNin, fParticles, fReadBName, fReadFile, fReadParticles, and fReadTree.
Referenced by THSDataReader().
void THSDataReader::InitOutput (TString filename)
Definition at line 65 of file THSDataReader.C.
References fParticles, fReadBName, fWriteFile, and fWriteTree.
Referenced by SetReadBranch(), and WriteParticles().
void THSDataReader::PrintEvent (Long64_t entry = 0) virtual
Definition at line 79 of file THSDataReader.C.
References fNin, fParticles, and ReadEvent().
Referenced by THSDataReader().
Bool_t THSDataReader::ReadEvent (Long64_t entry = -1) virtual
Definition at line 32 of file THSDataReader.C.
References fEntry, fParticles, fReadParticles, and fReadTree.
Referenced by PrintEvent(), THSDataReader(), and WriteParticles().
void THSDataReader::SetReadBranch (TString name) inline
Definition at line 29 of file THSDataReader.h.
References fReadBName, and InitOutput().
void THSDataReader::WriteEvent () inline
Definition at line 31 of file THSDataReader.h.
References CloseOutput(), and fWriteTree.
void THSDataReader::WriteParticles (TString filename) virtual
Definition at line 49 of file THSDataReader.C.
References CloseOutput(), fWriteTree, InitOutput(), and ReadEvent().
Referenced by THSDataReader().
Member Data Documentation
Long64_t THSDataReader::fEntry =0 protected
Definition at line 42 of file THSDataReader.h.
Referenced by ReadEvent().
Int_t THSDataReader::fNin protected
Definition at line 37 of file THSDataReader.h.
Referenced by AddParticle(), GetN(), Init(), and PrintEvent().
vector<THSParticle*> THSDataReader::fParticles protected
Definition at line 35 of file THSDataReader.h.
Referenced by AddParticle(), GetParticle(), Init(), InitOutput(), PrintEvent(), ReadEvent(), and ~THSDataReader().
TString THSDataReader::fReadBName ="Particles" protected
Definition at line 43 of file THSDataReader.h.
Referenced by Init(), InitOutput(), and SetReadBranch().
TFile* THSDataReader::fReadFile =0 protected
Definition at line 40 of file THSDataReader.h.
Referenced by Init(), and ~THSDataReader().
vector<THSParticle*>* THSDataReader::fReadParticles protected
Definition at line 36 of file THSDataReader.h.
Referenced by Init(), and ReadEvent().
TTree* THSDataReader::fReadTree =0 protected
Definition at line 41 of file THSDataReader.h.
Referenced by Init(), ReadEvent(), and ~THSDataReader().
TFile* THSDataReader::fWriteFile =0 protected
Definition at line 45 of file THSDataReader.h.
Referenced by CloseOutput(), and InitOutput().
TTree* THSDataReader::fWriteTree =0 protected
Definition at line 46 of file THSDataReader.h.
Referenced by CloseOutput(), InitOutput(), WriteEvent(), and WriteParticles().
The documentation for this class was generated from the following files:
HaSpect/THSDataReader.h
HaSpect/THSDataReader.C