HASPECT6: RooHS1StepStudy Class Reference
RooHS1StepStudy Class Reference
Definition at line 22 of file RooHS1StepStudy.h.
#include <RooHS1StepStudy.h>
Public Member Functions
RooHS1StepStudy (const char *name=0, const char *title=0)
RooHS1StepStudy (const RooHS1StepStudy &other)
virtual ~RooHS1StepStudy ()
virtual RooAbsStudy * clone (const char *newname="") const
virtual Bool_t attach (RooWorkspace &w)
virtual Bool_t initialize ()
virtual Bool_t execute ()
virtual Bool_t finalize ()
virtual void SetHSRooFit (THSRooFit *rf)
void SetPDFName (TString pdf)
void Print (Option_t *options=0) const
RooWorkspace * GetWorkSpace ()
THSRooFit * GetRooFit ()
void SetOutDir (TString dir)
void SetPlot (Bool_t plot=kTRUE)
void UseAll (Bool_t all=kTRUE)
Protected Attributes
RooAbsPdf * _genPdf =0
RooArgSet _genObs
RooAbsPdf * _fitPdf =0
RooArgSet _fitObs
RooRealVar * _nllVar =0
RooRealVar * _ngenVar =0
RooArgSet * _params =0
RooArgSet * _initParams =0
THSRooFit * fHSRooFit =0
RooWorkspace * fWS =0
TString fOutDir
Bool_t fIsCloned =kFALSE
Bool_t fIsPlot =kFALSE
Bool_t fUseAll =kFALSE
TString fPDFName
Long64_t fGeni =0
Constructor & Destructor Documentation
RooHS1StepStudy::RooHS1StepStudy (const char * name = 0, const char * title = 0)
Referenced by clone().
RooHS1StepStudy::RooHS1StepStudy (const RooHS1StepStudy & other)
Definition at line 35 of file RooHS1StepStudy.C.
References fHSRooFit, fIsCloned, fIsPlot, fOutDir, fUseAll, fWS, and THSRooFit::GetWorkSpace().
RooHS1StepStudy::~RooHS1StepStudy () virtual
Definition at line 49 of file RooHS1StepStudy.C.
References fHSRooFit, fIsCloned, and fWS.
Member Function Documentation
Bool_t RooHS1StepStudy::attach (RooWorkspace & w) virtual
Definition at line 55 of file RooHS1StepStudy.C.
References fHSRooFit, fOutDir, fWS, THSRooFit::GetWorkSpace(), THSRooFit::LoadWorkSpace(), THSRooFit::SetOutDir(), and THSRooFit::TotalPDF().
Referenced by clone().
virtual RooAbsStudy* RooHS1StepStudy::clone (const char * newname = "") const inline virtual
Definition at line 28 of file RooHS1StepStudy.h.
References attach(), execute(), finalize(), initialize(), and RooHS1StepStudy().
Bool_t RooHS1StepStudy::execute () virtual
Definition at line 95 of file RooHS1StepStudy.C.
References _ngenVar, _nllVar, _params, THSRooFit::CleanWSDataSets(), fGeni, fHSRooFit, fIsPlot, THSRooFit::Fit(), fPDFName, fUseAll, fWS, RooHSEventsPDF::GetGeni(), RooHSEventsPDF::GetGenTree(), THSRooFit::GetModel(), THSRooFit::GetPlots(), THSRooFit::GetResult(), THSRooFit::GetVariables(), RooHSEventsPDF::initIntegrator(), THSRooFit::LoadDataSet(), THSRooFit::LoadWeights(), THSRooFit::PlotDataModel(), THSRooFit::RemoveDataSet(), THSRooFit::SavePlots(), THSRooFit::SetDataWeightFast(), RooHSEventsPDF::SetGeni(), RooHSEventsPDF::SetUseWeightsGen(), THSRooFit::SetWeightName(), and RooHSEventsPDF::UseWeightsGen().
Referenced by clone().
Bool_t RooHS1StepStudy::finalize () virtual
Definition at line 162 of file RooHS1StepStudy.C.
References _initParams, _ngenVar, _nllVar, _params, fGeni, fHSRooFit, fIsPlot, fOutDir, fWS, and THSRooFit::GetParameters().
Referenced by clone().
THSRooFit* RooHS1StepStudy::GetRooFit () inline
Definition at line 39 of file RooHS1StepStudy.h.
References fHSRooFit.
RooWorkspace* RooHS1StepStudy::GetWorkSpace () inline
Definition at line 38 of file RooHS1StepStudy.h.
References fWS.
Bool_t RooHS1StepStudy::initialize () virtual
Definition at line 68 of file RooHS1StepStudy.C.
References _initParams, _ngenVar, _nllVar, _params, THSRooFit::AddFitOption(), fHSRooFit, fWS, THSRooFit::GetParameters(), and THSRooFit::GetYields().
Referenced by clone().
void RooHS1StepStudy::Print (Option_t * options = 0) const
Definition at line 238 of file RooHS1StepStudy.C.
Referenced by SetPDFName().
virtual void RooHS1StepStudy::SetHSRooFit (THSRooFit * rf) inline virtual
Definition at line 35 of file RooHS1StepStudy.h.
References fHSRooFit, fWS, and THSRooFit::GetWorkSpace().
void RooHS1StepStudy::SetOutDir (TString dir) inline
Definition at line 40 of file RooHS1StepStudy.h.
References fOutDir.
void RooHS1StepStudy::SetPDFName (TString pdf) inline
Definition at line 36 of file RooHS1StepStudy.h.
References fPDFName, and Print().
void RooHS1StepStudy::SetPlot (Bool_t plot = kTRUE) inline
Definition at line 41 of file RooHS1StepStudy.h.
References fIsPlot.
void RooHS1StepStudy::UseAll (Bool_t all = kTRUE) inline
Definition at line 42 of file RooHS1StepStudy.h.
References fUseAll.
Member Data Documentation
RooArgSet RooHS1StepStudy::_fitObs protected
Definition at line 49 of file RooHS1StepStudy.h.
RooAbsPdf* RooHS1StepStudy::_fitPdf =0 protected
Definition at line 48 of file RooHS1StepStudy.h.
RooArgSet RooHS1StepStudy::_genObs protected
Definition at line 47 of file RooHS1StepStudy.h.
RooAbsPdf* RooHS1StepStudy::_genPdf =0 protected
Definition at line 46 of file RooHS1StepStudy.h.
RooArgSet* RooHS1StepStudy::_initParams =0 protected
Definition at line 54 of file RooHS1StepStudy.h.
Referenced by finalize(), and initialize().
RooRealVar* RooHS1StepStudy::_ngenVar =0 protected
Definition at line 52 of file RooHS1StepStudy.h.
Referenced by execute(), finalize(), and initialize().
RooRealVar* RooHS1StepStudy::_nllVar =0 protected
Definition at line 51 of file RooHS1StepStudy.h.
Referenced by execute(), finalize(), and initialize().
RooArgSet* RooHS1StepStudy::_params =0 protected
Definition at line 53 of file RooHS1StepStudy.h.
Referenced by execute(), finalize(), and initialize().
Long64_t RooHS1StepStudy::fGeni =0 protected
Definition at line 64 of file RooHS1StepStudy.h.
Referenced by execute(), and finalize().
THSRooFit* RooHS1StepStudy::fHSRooFit =0 protected
Definition at line 56 of file RooHS1StepStudy.h.
Referenced by attach(), execute(), finalize(), GetRooFit(), initialize(), RooHS1StepStudy(), SetHSRooFit(), and ~RooHS1StepStudy().
Bool_t RooHS1StepStudy::fIsCloned =kFALSE protected
Definition at line 60 of file RooHS1StepStudy.h.
Referenced by RooHS1StepStudy(), and ~RooHS1StepStudy().
Bool_t RooHS1StepStudy::fIsPlot =kFALSE protected
Definition at line 61 of file RooHS1StepStudy.h.
Referenced by execute(), finalize(), RooHS1StepStudy(), and SetPlot().
TString RooHS1StepStudy::fOutDir protected
Definition at line 58 of file RooHS1StepStudy.h.
Referenced by attach(), finalize(), RooHS1StepStudy(), and SetOutDir().
TString RooHS1StepStudy::fPDFName protected
Definition at line 63 of file RooHS1StepStudy.h.
Referenced by execute(), and SetPDFName().
Bool_t RooHS1StepStudy::fUseAll =kFALSE protected
Definition at line 62 of file RooHS1StepStudy.h.
Referenced by execute(), RooHS1StepStudy(), and UseAll().
RooWorkspace* RooHS1StepStudy::fWS =0 protected
Definition at line 57 of file RooHS1StepStudy.h.
Referenced by attach(), execute(), finalize(), GetWorkSpace(), initialize(), RooHS1StepStudy(), SetHSRooFit(), and ~RooHS1StepStudy().
The documentation for this class was generated from the following files:
HaSpect/RooHS1StepStudy.h
HaSpect/RooHS1StepStudy.C