HASPECT6: THSCombitorial Class Reference
THSCombitorial Class Reference
Class to handle general iterations these can be : Permuations (==std::next_permuation) Rotations (==std::rotate) Selections (Combinations) (= Lexographic algorithm define here)
Definition at line 11 of file THSCombitorial.h.
#include <THSCombitorial.h>
Public Member Functions
THSCombitorial ()
virtual ~THSCombitorial ()
Int_t GetType ()
Int_t Niter ()
Bool_t IsFinished ()
Bool_t WhatIsFinished ()
std::vector< int > VectorIntDiff (const std::vector< int > &full, const std::vector< int > &part)
Function to return the different entries between 2 vector<int> s.
template<class T >
std::vector< T * > SubSet (std::vector< T * > *vec, Int_t entries, Int_t starti=0)
Function to truncate a vector at element = entries.
template<class T >
std::vector< T * > SubSet (std::vector< T * > *vec, vector< int > items)
Function to select out elements of a vector with indices given in items.
void PrintVectorInt (vector< Int_t > vec)
vector< Int_t > Single_Combination (vector< Int_t > c, Int_t n, Int_t p, Int_t x)
void MakeCombinations (Int_t n, Int_t p, Int_t nidentical)
void PrintCombinations ()
void ResetCombi ()
template<class T >
std::vector< T * > Next (std::vector< T * > *vec, Int_t a=0, Int_t b=1)
template<class T >
std::vector< T * > Permutation (std::vector< T * > *vec)
template<class T >
std::vector< T * > Rotation (std::vector< T * > *vec)
template<class T >
std::vector< T * > Selection (std::vector< T * > *vec, Int_t p, Int_t nidentical=1)
Function to select a subset of a vector containing any type of objects.
template<class T >
std::vector< T * > Remainder (std::vector< T * > *vec)
Protected Attributes
UInt_t fType =0
Bool_t fIsFinished =kFALSE
UInt_t fNiter =0
Int_t fSize =-1
Constructor & Destructor Documentation
THSCombitorial::THSCombitorial () inline
Definition at line 14 of file THSCombitorial.h.
virtual THSCombitorial::~THSCombitorial () inline virtual
Definition at line 15 of file THSCombitorial.h.
Member Function Documentation
Int_t THSCombitorial::GetType () inline
Definition at line 30 of file THSCombitorial.h.
References fType.
Referenced by THSParticleIter::NextCombitorial(), and THSParticleIter::Testing().
Bool_t THSCombitorial::IsFinished () inline
Definition at line 34 of file THSCombitorial.h.
Referenced by THSParticleIter::NextCombitorial().
void THSCombitorial::MakeCombinations (Int_t n, Int_t p, Int_t nidentical)
Definition at line 15 of file THSCombitorial.C.
References Single_Combination().
Referenced by Selection(), and WhatIsFinished().
template<class T > std::vector< T * > THSCombitorial::Next (std::vector< T * > * vec, Int_t a = 0, Int_t b = 1)
Function to control behviour depending on which type of iteration Is desired. To get the different behviour users must create and object of the appropriate type: THSPermuation;THSRotation;THSSelection
Definition at line 106 of file THSCombitorial.h.
References fIsFinished, fType, Permutation(), Rotation(), and Selection().
Referenced by THSParticleIter::NextCombitorial(), and ResetCombi().
Int_t THSCombitorial::Niter () inline
Definition at line 31 of file THSCombitorial.h.
References fNiter.
template<class T > std::vector< T * > THSCombitorial::Permutation (std::vector< T * > * vec)
Function to permutate a vector containing any type of objects Returns a copy of the permuated vector but the supplied vector vec is itself permutated
Definition at line 118 of file THSCombitorial.h.
References fIsFinished, and fNiter.
Referenced by Next(), and ResetCombi().
void THSCombitorial::PrintCombinations ()
Definition at line 44 of file THSCombitorial.C.
Referenced by WhatIsFinished().
void THSCombitorial::PrintVectorInt (vector< Int_t > vec)
Definition at line 79 of file THSCombitorial.C.
Referenced by WhatIsFinished().
template<class T > std::vector< T * > THSCombitorial::Remainder (std::vector< T * > * vec)
Function to return the unselected elements from Selection Returns a copy of the selected vector The supplied vector vec is not altered
Definition at line 164 of file THSCombitorial.h.
References fNiter, fType, SubSet(), and VectorIntDiff().
Referenced by THSParticleIter::NextCombitorial(), and ResetCombi().
void THSCombitorial::ResetCombi () inline
Definition at line 49 of file THSCombitorial.h.
References Next(), Permutation(), Remainder(), Rotation(), and Selection().
template<class T > std::vector< T * > THSCombitorial::Rotation (std::vector< T * > * vec)
Function to rotate a vector containing any type of objects Returns a copy of the rotated vector but the supplied vector vec is itself rotated
Definition at line 132 of file THSCombitorial.h.
References fIsFinished, and fNiter.
Referenced by Next(), and ResetCombi().
template<class T > std::vector< T * > THSCombitorial::Selection (std::vector< T * > * vec, Int_t p, Int_t nidentical = 1)
Function to select a subset of a vector containing any type of objects.
Returns a copy of the selected vector The supplied vector vec is not altered
Definition at line 145 of file THSCombitorial.h.
References fIsFinished, fNiter, fSize, MakeCombinations(), and SubSet().
Referenced by Next(), and ResetCombi().
B and M ACM Transactions on Mathematical June *vector< Int_t > THSCombitorial::Single_Combination (vector< Int_t > c, Int_t n, Int_t p, Int_t x)
Definition at line 58 of file THSCombitorial.C.
Referenced by MakeCombinations(), and WhatIsFinished().
template<class T > std::vector< T * > THSCombitorial::SubSet (std::vector< T * > * vec, Int_t entries, Int_t starti = 0)
Function to truncate a vector at element = entries.
Definition at line 185 of file THSCombitorial.h.
Referenced by Remainder(), Selection(), THSParticleIter::SelectXofY(), and WhatIsFinished().
template<class T > std::vector< T * > THSCombitorial::SubSet (std::vector< T * > * vec, vector< int > items)
Function to select out elements of a vector with indices given in items.
Definition at line 195 of file THSCombitorial.h.
std::vector< int > THSCombitorial::VectorIntDiff (const std::vector< int > & full, const std::vector< int > & part)
Function to return the different entries between 2 vector<int> s.
Definition at line 172 of file THSCombitorial.h.
Referenced by Remainder(), and WhatIsFinished().
Bool_t THSCombitorial::WhatIsFinished () inline
Definition at line 35 of file THSCombitorial.h.
References fIsFinished, MakeCombinations(), PrintCombinations(), PrintVectorInt(), Single_Combination(), SubSet(), and VectorIntDiff().
Member Data Documentation
Bool_t THSCombitorial::fIsFinished =kFALSE protected
Definition at line 25 of file THSCombitorial.h.
Referenced by Next(), Permutation(), Rotation(), Selection(), and WhatIsFinished().
UInt_t THSCombitorial::fNiter =0 protected
Definition at line 26 of file THSCombitorial.h.
Referenced by Niter(), Permutation(), Remainder(), Rotation(), and Selection().
Int_t THSCombitorial::fSize =-1 protected
Definition at line 27 of file THSCombitorial.h.
Referenced by Selection().
UInt_t THSCombitorial::fType =0 protected
Definition at line 24 of file THSCombitorial.h.
Referenced by GetType(), Next(), Remainder(), THSPermutation::THSPermutation(), THSRotation::THSRotation(), and THSSelection::THSSelection().
The documentation for this class was generated from the following files:
HaSpect/THSCombitorial.h
HaSpect/THSCombitorial.C