HASPECT6: THSPartOutput Class Reference
THSPartOutput Class Reference
Definition at line 25 of file THSPartOutput.h.
#include <THSPartOutput.h>
Public Member Functions
THSPartOutput ()
~THSPartOutput ()
THSParticle * GetHSParticle (Int_t np)
vector< UInt_t > GetNType ()
vector< Int_t > GetFinalState ()
virtual void InitOutput ()
Public Member Functions inherited from THSOutput
THSOutput ()
virtual ~THSOutput ()
virtual void FinishOutput ()
virtual void InitOutFile (TTree *chain)
void InitOutTree ()
void PrepareOutDir ()
Int_t CountChar (TString tests, char testc)
void CopyCode (TDirectory *curDir=0, TDirectory *prevDir=0)
void ImportSysDirtoList (const char *dirname, TList *list)
TList * CopyDirtoList (TDirectory *source)
void WriteListtoFile (TList *list0)
void HSBegin (TList *input, TList *output)
void HSSlaveBegin (TList *input, TList *output)
virtual void HSProcessStart (Long64_t entry)
virtual void HSProcessFill ()
virtual void HSSlaveTerminate ()
virtual void HSNotify (TTree *tree)
virtual void HSTerminate ()
void SortTree (TTree *tree)
void SetSort (Bool_t sort=kTRUE)
TTree * GetOutTree ()
void SetIDoff (Long64_t off)
void SetParticles (TString sp)
Public Member Functions inherited from THSHisto
THSHisto (TTree *=0)
virtual ~THSHisto ()
virtual void InitialiseHisto (TList *input)
virtual void LoadCut (TString sCut)
virtual void LoadHistograms ()
virtual void ChangeNames ()
virtual TH1 * MapHist (TH1 *hist)
virtual TH1 * FindHist (TString hname)
virtual void OrganiseSavedHists (TFile *stdFile, TList *output)
void MakeAxisDir (Int_t iA, TDirectory *curDir)
virtual void HistogramList (TString sLabel)
virtual void FillHistograms (TString sCut)
void LoadWeights (TString fname, TString wname)
void LoadCutsForWeights ()
void FillCutsForWeights ()
void GetWeightEvent (Double_t id)
void SetWeight (TString species)
Protected Attributes
vector< Int_t > fFinalState
vector< UInt_t > fNtype
vector< UInt_t > fIDtype
UInt_t fNdet
vector< Int_t > fDetID
vector< THSParticle * > fDetParticle
Protected Attributes inherited from THSOutput
TFile * fFile =nullptr
TProofOutputFile * fProofFile =nullptr
TTree * fOutTree =nullptr
TTree * fCurTree =nullptr
TEntryList * fEntryList =nullptr
TString fOutName
TString fStrParticles
TString fStepName
TList * fStepDir =nullptr
TList * fSelInput =nullptr
TList * fSelOutput =nullptr
TList * fCodeList =nullptr
TList * fListOfFiles =nullptr
Long64_t fEntry =0
TObject fMessages
Bool_t fSort =kFALSE
Bool_t fSaveID =kFALSE
Double_t fgID =0
Long64_t fgIDoff =0
Protected Attributes inherited from THSHisto
Bool_t fIsHisto =0
StrTH1_Map fHistNameMap
Vec_StrTH1 fVecHistCut
vector< Vec_StrTH1 > fVecHistBin
TString fCurrCut
Int_t fCurrBin = 0
vector< TString > fVecTypes
vector< TString > fVecCuts
vector< TString > fVecBinNames
map< TString, Int_t > fMapCuts
map< TString, TString > fBinMap
TObjArray * fBinEntryLists
Additional Inherited Members
Public Attributes inherited from THSHisto
THSWeights * fWeights =nullptr
Double_t fWeight =1
THSBins * fBins =nullptr
Constructor & Destructor Documentation
THSPartOutput::THSPartOutput () inline
Definition at line 28 of file THSPartOutput.h.
References ~THSPartOutput().
THSPartOutput::~THSPartOutput ()
Definition at line 3 of file THSPartOutput.C.
References fDetParticle.
Referenced by THSPartOutput().
Member Function Documentation
vector<Int_t> THSPartOutput::GetFinalState () inline
Definition at line 42 of file THSPartOutput.h.
References fFinalState, and InitOutput().
THSParticle* THSPartOutput::GetHSParticle (Int_t np) inline
Definition at line 40 of file THSPartOutput.h.
vector<UInt_t> THSPartOutput::GetNType () inline
Definition at line 41 of file THSPartOutput.h.
References fNtype.
void THSPartOutput::InitOutput () virtual
!!!!!!!!!!!!!!!!!!!!!very important step for event algorithm!!!!!!!!!!
Definition at line 9 of file THSPartOutput.C.
References THSOutput::CountChar(), fDetID, fDetParticle, fFinalState, fIDtype, fNdet, fNtype, THSOutput::fOutTree, and THSOutput::fStrParticles.
Referenced by GetFinalState().
Member Data Documentation
vector<Int_t> THSPartOutput::fDetID protected
Definition at line 36 of file THSPartOutput.h.
Referenced by InitOutput().
vector<THSParticle*> THSPartOutput::fDetParticle protected
Definition at line 37 of file THSPartOutput.h.
Referenced by InitOutput(), and ~THSPartOutput().
vector<Int_t> THSPartOutput::fFinalState protected
Definition at line 32 of file THSPartOutput.h.
Referenced by GetFinalState(), and InitOutput().
vector<UInt_t> THSPartOutput::fIDtype protected
Definition at line 34 of file THSPartOutput.h.
Referenced by InitOutput().
UInt_t THSPartOutput::fNdet protected
Definition at line 35 of file THSPartOutput.h.
Referenced by InitOutput().
vector<UInt_t> THSPartOutput::fNtype protected
Definition at line 33 of file THSPartOutput.h.
Referenced by GetNType(), and InitOutput().
The documentation for this class was generated from the following files:
HaSpect/THSPartOutput.h
HaSpect/THSPartOutput.C