HASPECT6: THSBins Class Reference
THSBins Class Reference
Definition at line 18 of file THSBins.h.
#include <THSBins.h>
Public Member Functions
THSBins ()
THSBins (TString name, TString filename)
THSBins (const THSBins &other, const char *name=0)
THSBins (TString name)
~THSBins ()
virtual TObject * Clone (const char *newname="") const
void AddAxis (TString name, Int_t nbins, Double_t min, Double_t max)
void AddAxis (TString name, Int_t nbins, Double_t *xbins)
void IterateAxis (Int_t iA, TString binName)
VecString_t GetBinNames ()
VecAxis_t GetVarAxis ()
Int_t GetAxisi (TString aname)
TAxis GetAxis (Int_t ia)
TString GetBinName (Int_t i)
TString GetPartName (Int_t ia, Int_t ib)
Int_t GetParti (Int_t ia, TString name)
void InitialiseBins ()
void InitialiseBinTree (TString name, TString filename)
void Save ()
void RunBinTree (TTree *tree)
void MakeBinTree (TTree *tree, TString name, TString filename)
TTree * GetBinTree ()
TTree * GetBinnedTree (TTree *tree, Int_t bin)
Int_t GetN ()
Int_t GetNAxis ()
void PrintAxis ()
Int_t FindBin (TVectorD vals)
Int_t FindBin (Double_t v0)
Int_t FindBin (Double_t v0, Double_t v1)
Int_t FindBin (Double_t v0, Double_t v1, Double_t v2)
Int_t FindBin (Double_t v0, Double_t v1, Double_t v2, Double_t v3, Double_t v4=0, Double_t v5=0)
Protected Attributes
TTree * fBinTree =nullptr
VecString_t fBinNames
VecAxis_t fVarAxis
vector< VecString_t > fPartName
TFile * fFile =nullptr
Int_t fNbins
file for writing lists to disc in case they get large
Int_t fNaxis
Int_t fBin
Constructor & Destructor Documentation
THSBins::THSBins () inline
Definition at line 31 of file THSBins.h.
THSBins::THSBins (TString name, TString filename)
Definition at line 15 of file THSBins.C.
References fBinNames, fBinTree, fFile, fNaxis, fNbins, fVarAxis, GetBinNames(), GetN(), GetNAxis(), and GetVarAxis().
THSBins::THSBins (const THSBins & other, const char * name = 0)
Definition at line 31 of file THSBins.C.
References fBinNames, fBinTree, fFile, fNaxis, fNbins, and fVarAxis.
THSBins::THSBins (TString name)
THSBins::~THSBins ()
Definition at line 40 of file THSBins.C.
References fBinTree, and fFile.
Member Function Documentation
void THSBins::AddAxis (TString name, Int_t nbins, Double_t min, Double_t max)
Definition at line 44 of file THSBins.C.
Referenced by THSRooFit::LoadBinVars().
void THSBins::AddAxis (TString name, Int_t nbins, Double_t * xbins)
Definition at line 58 of file THSBins.C.
References fNaxis, and fVarAxis.
virtual TObject* THSBins::Clone (const char * newname = "") const inline virtual
Definition at line 38 of file THSBins.h.
Referenced by THSRooFit::THSRooFit().
Int_t THSBins::FindBin (TVectorD vals)
Definition at line 211 of file THSBins.C.
References fNaxis, and fVarAxis.
Referenced by FindBin(), and RunBinTree().
Int_t THSBins::FindBin (Double_t v0)
Definition at line 195 of file THSBins.C.
References FindBin().
Int_t THSBins::FindBin (Double_t v0, Double_t v1)
Definition at line 199 of file THSBins.C.
References FindBin().
Int_t THSBins::FindBin (Double_t v0, Double_t v1, Double_t v2)
Definition at line 203 of file THSBins.C.
References FindBin().
Int_t THSBins::FindBin (Double_t v0, Double_t v1, Double_t v2, Double_t v3, Double_t v4 = 0, Double_t v5 = 0)
Definition at line 207 of file THSBins.C.
References FindBin().
TAxis THSBins::GetAxis (Int_t ia) inline
Definition at line 46 of file THSBins.h.
Referenced by THSHisto::MakeAxisDir().
Int_t THSBins::GetAxisi (TString aname) inline
Definition at line 45 of file THSBins.h.
TString THSBins::GetBinName (Int_t i) inline
Definition at line 47 of file THSBins.h.
Referenced by THSHisto::ChangeNames(), THSRooFit::FitSavedBins(), THSRooFit::FitWithBins(), THSRooFit::MakeBinnedTrees(), and THSHisto::OrganiseSavedHists().
VecString_t THSBins::GetBinNames () inline
Definition at line 43 of file THSBins.h.
Referenced by THSBins().
TTree * THSBins::GetBinnedTree (TTree * tree, Int_t bin)
Definition at line 146 of file THSBins.C.
References fBinNames, and fBinTree.
Referenced by THSRooFit::FitWithBins(), and THSRooFit::MakeBinnedTrees().
TTree* THSBins::GetBinTree () inline
Definition at line 55 of file THSBins.h.
Int_t THSBins::GetN () inline
Definition at line 57 of file THSBins.h.
Referenced by THSHisto::ChangeNames(), THSRooFit::ConfigureSavedBins(), THSRooFit::FitSavedBins(), THSRooFit::FitWithBins(), THSHisto::LoadHistograms(), THSRooFit::MakeBinnedTrees(), THSHisto::OrganiseSavedHists(), and THSBins().
Int_t THSBins::GetNAxis () inline
Definition at line 58 of file THSBins.h.
Referenced by THSHisto::MakeAxisDir(), and THSBins().
Int_t THSBins::GetParti (Int_t ia, TString name) inline
Definition at line 49 of file THSBins.h.
TString THSBins::GetPartName (Int_t ia, Int_t ib) inline
Definition at line 48 of file THSBins.h.
Referenced by THSHisto::MakeAxisDir().
VecAxis_t THSBins::GetVarAxis () inline
Definition at line 44 of file THSBins.h.
Referenced by THSBins().
void THSBins::InitialiseBins ()
Definition at line 65 of file THSBins.C.
References fBinNames, fNaxis, fNbins, and IterateAxis().
Referenced by InitialiseBinTree(), THSHisto::InitialiseHisto(), and THSHisto::OrganiseSavedHists().
void THSBins::InitialiseBinTree (TString name, TString filename)
Definition at line 74 of file THSBins.C.
References fBin, fBinTree, fFile, and InitialiseBins().
Referenced by THSRooFit::MakeBins().
void THSBins::IterateAxis (Int_t iA, TString binName)
Definition at line 86 of file THSBins.C.
References fBinNames, fNaxis, fNbins, fPartName, and fVarAxis.
Referenced by InitialiseBins().
void THSBins::MakeBinTree (TTree * tree, TString name, TString filename) inline
Definition at line 54 of file THSBins.h.
void THSBins::PrintAxis ()
Definition at line 173 of file THSBins.C.
References fNaxis, and fVarAxis.
void THSBins::RunBinTree (TTree * tree)
Definition at line 106 of file THSBins.C.
References fBin, fBinTree, fFile, FindBin(), fNaxis, and fVarAxis.
Referenced by THSRooFit::MakeBins().
void THSBins::Save ()
Definition at line 163 of file THSBins.C.
References fBinTree, and fFile.
Referenced by THSRooFit::MakeBins().
Member Data Documentation
Int_t THSBins::fBin protected
Definition at line 28 of file THSBins.h.
Referenced by InitialiseBinTree(), and RunBinTree().
VecString_t THSBins::fBinNames protected
Definition at line 22 of file THSBins.h.
Referenced by GetBinnedTree(), InitialiseBins(), IterateAxis(), and THSBins().
TTree* THSBins::fBinTree =nullptr protected
Definition at line 21 of file THSBins.h.
Referenced by GetBinnedTree(), InitialiseBinTree(), RunBinTree(), Save(), THSBins(), and ~THSBins().
TFile* THSBins::fFile =nullptr protected
Definition at line 25 of file THSBins.h.
Referenced by InitialiseBinTree(), RunBinTree(), Save(), THSBins(), and ~THSBins().
Int_t THSBins::fNaxis protected
Definition at line 27 of file THSBins.h.
Referenced by AddAxis(), FindBin(), InitialiseBins(), IterateAxis(), PrintAxis(), RunBinTree(), and THSBins().
Int_t THSBins::fNbins protected
file for writing lists to disc in case they get large
Definition at line 26 of file THSBins.h.
Referenced by InitialiseBins(), IterateAxis(), and THSBins().
vector<VecString_t> THSBins::fPartName protected
Definition at line 24 of file THSBins.h.
Referenced by IterateAxis().
VecAxis_t THSBins::fVarAxis protected
Definition at line 23 of file THSBins.h.
Referenced by AddAxis(), FindBin(), IterateAxis(), PrintAxis(), RunBinTree(), and THSBins().
The documentation for this class was generated from the following files:
HaSpect/THSBins.h
HaSpect/THSBins.C