HASPECT6: THSFinalTemp Class Reference
THSFinalTemp Class Reference
Template final class .
Users should create their own analysis specific project classes.
Definition at line 9 of file THSFinalTemp.h.
#include <THSFinalTemp.h>
Public Member Functions
THSFinalTemp ()
~THSFinalTemp ()
virtual Bool_t WorkOnEvent ()
void Init_Generated ()
void Kinematics ()
virtual void FinalStateOutTree (TTree *tree)
Public Member Functions inherited from THSFinalState
THSFinalState ()
virtual ~THSFinalState ()
virtual void GetEvent (Long64_t uid)
virtual void FinaliseEvent ()
virtual void InitEvent ()
void SetDetParts (vector< THSParticle * > *dpp)
void SetGenParts (vector< THSParticle * > *dpp)
Int_t AddTopology (TString topo)
topo should be a pdg particle list seperated by : e.g. "proton:pi+:pi-"
vector< Int_t > GetTopology (Int_t i)
Int_t FindTopology ()
Int_t FindInclusiveTopology (Int_t incType=-1E9)
void SetPermutate ()
void SetInclusive ()
void SetGenerated (Bool_t gen=kTRUE)
void SetUseChargePID (Bool_t gen=kTRUE)
Bool_t IsGoodEvent ()
virtual Bool_t IsPermutating ()
virtual void ProcessEvent ()
Process one event from the input tree.
virtual void MatchWithGen (THSParticle *part)
Loop through generated and record momentum distance.
virtual Bool_t IsCorrectTruth (THSParticle *part)
virtual void CheckTruth ()
Check if our final vectors match with truth.
THSParticleIter * AddSelectToSelected (THSParticleIter *diter, Int_t nsel, Int_t ni, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddSelectToRemainder (THSParticleIter *diter, Int_t nsel, Int_t ni, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddSelectXofY (Int_t nsel, Int_t ni, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddPermutateToSelected (THSParticleIter *diter, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddPermutateToRemainder (THSParticleIter *diter, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddPermutate (THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * CreateParticleIter (Int_t topo, vector< THSParticle * > *parts, Int_t Nsel)
THSFinalState ()
virtual ~THSFinalState ()
virtual void GetEvent (Long64_t uid)
virtual void FinaliseEvent ()
virtual void InitEvent ()
void SetDetParts (vector< THSParticle * > *dpp)
void SetGenParts (vector< THSParticle * > *dpp)
Int_t AddTopology (TString topo)
vector< Int_t > GetTopology (Int_t i)
Int_t FindTopology ()
Int_t FindInclusiveTopology (Int_t incType=-1E9)
void SetPermutate ()
void SetInclusive ()
void SetGenerated (Bool_t gen=kTRUE)
void SetUseChargePID (Bool_t gen=kTRUE)
Bool_t IsGoodEvent ()
virtual Bool_t IsPermutating ()
virtual void ProcessEvent ()
virtual void MatchWithGen (THSParticle *part)
virtual Bool_t IsCorrectTruth (THSParticle *part)
virtual void CheckTruth ()
THSParticleIter * AddSelectToSelected (THSParticleIter *diter, Int_t nsel, Int_t ni, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddSelectToRemainder (THSParticleIter *diter, Int_t nsel, Int_t ni, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddSelectXofY (Int_t nsel, Int_t ni, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddPermutateToSelected (THSParticleIter *diter, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddPermutateToRemainder (THSParticleIter *diter, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddPermutate (THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * CreateParticleIter (Int_t topo, vector< THSParticle * > *parts, Int_t Nsel)
Protected Attributes
TLorentzVector fBeam =TLorentzVector(0,0,10.6,10.6)
TLorentzVector fTarget =TLorentzVector(0,0,0,0.938272)
Double_t f_t
Double_t f_Q2
Double_t f_W
Double_t f_Pol
Double_t fCMCosTh
Double_t fCMPhi
Double_t fMissMass =0
Protected Attributes inherited from THSFinalState
Int_t fNDet =0
vector< vector< Int_t > > fTopo
Int_t fNTopo =0
Int_t fCurrTopo =-1
UInt_t fNParts =0
UInt_t fNGen =0
Bool_t fGoodEvent = kTRUE
Long64_t fNUsedReadEvent =0
Bool_t fIsGenerated =kFALSE
Int_t fCorrect =kTRUE
Bool_t fGotCorrectOne =kFALSE
Bool_t fUseChargePID =kFALSE
Bool_t fIsInclusive =kFALSE
Bool_t fTryPerm =kFALSE
Int_t fNPerm =0
vector< THSParticle * > fVecProtons
vector< THSParticle * > fVecPiPs
vector< THSParticle * > fVecPiMs
vector< THSParticle * > fVecKPs
vector< THSParticle * > fVecKMs
vector< THSParticle * > fVecEls
vector< THSParticle * > fVecPos
vector< THSParticle * > fVecPi0s
vector< THSParticle * > fVecGams
vector< THSParticle * > fVecPlus
vector< THSParticle * > fVecMinus
vector< THSParticle * > fVec0
vector< THSParticle * > fVecBeams
vector< Int_t > fDetTypes
vector< THSParticleIter * > fDetIter
Int_t fIterLevel =0
map< Int_t, vector< THSParticle * > * > fMapPDGtoParticle
Bool_t fIsPermutating0 =kFALSE
Bool_t fIsPermutating1 =kFALSE
TTree * fFinalTree =nullptr
THSKinematics fKine
Double_t fUID =0
vector< THSParticle * > * frDetParts =nullptr
vector< THSParticle * > * frGenParts =nullptr
vector< THSParticle * > fFinal
Additional Inherited Members
Protected Member Functions inherited from THSFinalState
virtual void InitGenerated ()
Bool_t IsMissing (THSParticle *part)
void InitParticles ()
void InitDetParts ()
void InitDetPartsCharge ()
Bool_t PermutateParticles ()
virtual void InitGenerated ()
Bool_t IsMissing (THSParticle *part)
void InitParticles ()
void InitDetParts ()
void InitDetPartsCharge ()
Bool_t PermutateParticles ()
Constructor & Destructor Documentation
THSFinalTemp::THSFinalTemp ()
Examples:
THSFinalTemp.C.
Definition at line 17 of file THSFinalTemp.C.
References THSFinalState::fDetIter, and THSFinalState::fNTopo.
THSFinalTemp::~THSFinalTemp () inline
Definition at line 13 of file THSFinalTemp.h.
References Init_Generated(), Kinematics(), and WorkOnEvent().
Member Function Documentation
void THSFinalTemp::FinalStateOutTree (TTree * tree) virtual
Reimplemented from THSFinalState.
Examples:
THSFinalTemp.C.
Definition at line 62 of file THSFinalTemp.C.
References THSFinalState::fFinal, THSFinalState::fFinalTree, and fMissMass.
void THSFinalTemp::Init_Generated ()
Examples:
THSFinalTemp.C.
Definition at line 28 of file THSFinalTemp.C.
References THSFinalState::fGoodEvent, THSFinalState::fIsGenerated, and THSFinalState::frGenParts.
Referenced by WorkOnEvent(), and ~THSFinalTemp().
void THSFinalTemp::Kinematics ()
Examples:
THSFinalTemp.C.
Definition at line 56 of file THSFinalTemp.C.
References THSFinalState::fGoodEvent.
Referenced by WorkOnEvent(), and ~THSFinalTemp().
Bool_t THSFinalTemp::WorkOnEvent () virtual
Reimplemented from THSFinalState.
Examples:
THSFinalTemp.C.
Definition at line 68 of file THSFinalTemp.C.
References THSFinalState::CheckTruth(), THSFinalState::fCorrect, THSFinalState::fGoodEvent, THSFinalState::FindTopology(), THSFinalState::fIsGenerated, THSFinalState::fIsPermutating0, Init_Generated(), Kinematics(), and THSFinalState::PermutateParticles().
Referenced by ~THSFinalTemp().
Member Data Documentation
Double_t THSFinalTemp::f_Pol protected
Definition at line 36 of file THSFinalTemp.h.
Double_t THSFinalTemp::f_Q2 protected
Definition at line 34 of file THSFinalTemp.h.
Double_t THSFinalTemp::f_t protected
Definition at line 33 of file THSFinalTemp.h.
Double_t THSFinalTemp::f_W protected
Definition at line 35 of file THSFinalTemp.h.
TLorentzVector THSFinalTemp::fBeam =TLorentzVector(0,0,10.6,10.6) protected
Definition at line 28 of file THSFinalTemp.h.
Double_t THSFinalTemp::fCMCosTh protected
Definition at line 37 of file THSFinalTemp.h.
Double_t THSFinalTemp::fCMPhi protected
Definition at line 38 of file THSFinalTemp.h.
Double_t THSFinalTemp::fMissMass =0 protected
Examples:
THSFinalTemp.C.
Definition at line 41 of file THSFinalTemp.h.
Referenced by FinalStateOutTree().
TLorentzVector THSFinalTemp::fTarget =TLorentzVector(0,0,0,0.938272) protected
Definition at line 29 of file THSFinalTemp.h.
The documentation for this class was generated from the following files:
HaSpect/THSFinalTemp.h
HaSpect/THSFinalTemp.C