HASPECT6: THSFinalState Class Reference
THSFinalState Class Reference
Class to control particlular analysis Users need to create their own specific final state class It should operate on 3 classes of data: real, mc rec, mc gen input should be in form of events extracted from trees or text files,...
The main task is to take detected particles and convert them into information needed for subsequent fitting of observables, e.g TLorentzVectors for AmpTools Double_t s for RooFit
Definition at line 28 of file THSFinalState.h.
#include <THSFinalState.h>
Public Member Functions
THSFinalState ()
virtual ~THSFinalState ()
virtual void GetEvent (Long64_t uid)
virtual Bool_t WorkOnEvent ()
virtual void FinaliseEvent ()
virtual void InitEvent ()
void SetDetParts (vector< THSParticle * > *dpp)
void SetGenParts (vector< THSParticle * > *dpp)
Int_t AddTopology (TString topo)
topo should be a pdg particle list seperated by : e.g. "proton:pi+:pi-"
vector< Int_t > GetTopology (Int_t i)
Int_t FindTopology ()
Int_t FindInclusiveTopology (Int_t incType=-1E9)
void SetPermutate ()
void SetInclusive ()
void SetGenerated (Bool_t gen=kTRUE)
void SetUseChargePID (Bool_t gen=kTRUE)
Bool_t IsGoodEvent ()
virtual Bool_t IsPermutating ()
virtual void ProcessEvent ()
Process one event from the input tree.
virtual void MatchWithGen (THSParticle *part)
Loop through generated and record momentum distance.
virtual Bool_t IsCorrectTruth (THSParticle *part)
virtual void FinalStateOutTree (TTree *tree)
virtual void CheckTruth ()
Check if our final vectors match with truth.
THSParticleIter * AddSelectToSelected (THSParticleIter *diter, Int_t nsel, Int_t ni, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddSelectToRemainder (THSParticleIter *diter, Int_t nsel, Int_t ni, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddSelectXofY (Int_t nsel, Int_t ni, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddPermutateToSelected (THSParticleIter *diter, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddPermutateToRemainder (THSParticleIter *diter, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddPermutate (THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * CreateParticleIter (Int_t topo, vector< THSParticle * > *parts, Int_t Nsel)
THSFinalState ()
virtual ~THSFinalState ()
virtual void GetEvent (Long64_t uid)
virtual Bool_t WorkOnEvent ()
virtual void FinaliseEvent ()
virtual void InitEvent ()
void SetDetParts (vector< THSParticle * > *dpp)
void SetGenParts (vector< THSParticle * > *dpp)
Int_t AddTopology (TString topo)
vector< Int_t > GetTopology (Int_t i)
Int_t FindTopology ()
Int_t FindInclusiveTopology (Int_t incType=-1E9)
void SetPermutate ()
void SetInclusive ()
void SetGenerated (Bool_t gen=kTRUE)
void SetUseChargePID (Bool_t gen=kTRUE)
Bool_t IsGoodEvent ()
virtual Bool_t IsPermutating ()
virtual void ProcessEvent ()
virtual void MatchWithGen (THSParticle *part)
virtual Bool_t IsCorrectTruth (THSParticle *part)
virtual void FinalStateOutTree (TTree *tree)
virtual void CheckTruth ()
THSParticleIter * AddSelectToSelected (THSParticleIter *diter, Int_t nsel, Int_t ni, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddSelectToRemainder (THSParticleIter *diter, Int_t nsel, Int_t ni, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddSelectXofY (Int_t nsel, Int_t ni, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddPermutateToSelected (THSParticleIter *diter, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddPermutateToRemainder (THSParticleIter *diter, THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * AddPermutate (THSParticle *part0=nullptr, THSParticle *part1=nullptr, THSParticle *part2=nullptr, THSParticle *part3=nullptr, THSParticle *part4=nullptr, THSParticle *part5=nullptr, THSParticle *part6=nullptr, THSParticle *part7=nullptr, THSParticle *part8=nullptr, THSParticle *part9=nullptr)
THSParticleIter * CreateParticleIter (Int_t topo, vector< THSParticle * > *parts, Int_t Nsel)
Protected Member Functions
virtual void InitGenerated ()
Bool_t IsMissing (THSParticle *part)
void InitParticles ()
void InitDetParts ()
void InitDetPartsCharge ()
Bool_t PermutateParticles ()
virtual void InitGenerated ()
Bool_t IsMissing (THSParticle *part)
void InitParticles ()
void InitDetParts ()
void InitDetPartsCharge ()
Bool_t PermutateParticles ()
Protected Attributes
Int_t fNDet =0
vector< vector< Int_t > > fTopo
Int_t fNTopo =0
Int_t fCurrTopo =-1
UInt_t fNParts =0
UInt_t fNGen =0
Bool_t fGoodEvent = kTRUE
Long64_t fNUsedReadEvent =0
Bool_t fIsGenerated =kFALSE
Int_t fCorrect =kTRUE
Bool_t fGotCorrectOne =kFALSE
Bool_t fUseChargePID =kFALSE
Bool_t fIsInclusive =kFALSE
Bool_t fTryPerm =kFALSE
Int_t fNPerm =0
vector< THSParticle * > fVecProtons
vector< THSParticle * > fVecPiPs
vector< THSParticle * > fVecPiMs
vector< THSParticle * > fVecKPs
vector< THSParticle * > fVecKMs
vector< THSParticle * > fVecEls
vector< THSParticle * > fVecPos
vector< THSParticle * > fVecPi0s
vector< THSParticle * > fVecGams
vector< THSParticle * > fVecPlus
vector< THSParticle * > fVecMinus
vector< THSParticle * > fVec0
vector< THSParticle * > fVecBeams
vector< Int_t > fDetTypes
vector< THSParticleIter * > fDetIter
Int_t fIterLevel =0
map< Int_t, vector< THSParticle * > * > fMapPDGtoParticle
Bool_t fIsPermutating0 =kFALSE
Bool_t fIsPermutating1 =kFALSE
TTree * fFinalTree =nullptr
THSKinematics fKine
Double_t fUID =0
vector< THSParticle * > * frDetParts =nullptr
vector< THSParticle * > * frGenParts =nullptr
vector< THSParticle * > fFinal
Constructor & Destructor Documentation
THSFinalState::THSFinalState ()
Definition at line 23 of file THSFinalState.C.
References fMapPDGtoParticle, fVec0, fVecBeams, fVecEls, fVecGams, fVecKMs, fVecKPs, fVecMinus, fVecPi0s, fVecPiMs, fVecPiPs, fVecPlus, fVecPos, and fVecProtons.
virtual THSFinalState::~THSFinalState () inline virtual
Definition at line 32 of file THSFinalState.h.
References fDetIter.
THSFinalState::THSFinalState ()
virtual THSFinalState::~THSFinalState () inline virtual
Definition at line 32 of file THSFinalState12.h.
References fDetIter.
Member Function Documentation
THSParticleIter * THSFinalState::AddPermutate (THSParticle * part0 = nullptr, THSParticle * part1 = nullptr, THSParticle * part2 = nullptr, THSParticle * part3 = nullptr, THSParticle * part4 = nullptr, THSParticle * part5 = nullptr, THSParticle * part6 = nullptr, THSParticle * part7 = nullptr, THSParticle * part8 = nullptr, THSParticle * part9 = nullptr)
Interface to THSParticleIter Add selected iterator
Definition at line 367 of file THSFinalState.C.
References THSParticleIter::AddEventParticles(), and THSParticleIter::SetCombi().
Referenced by AddPermutateToRemainder(), AddPermutateToSelected(), and FinalStateOutTree().
THSParticleIter* THSFinalState::AddPermutate (THSParticle * part0 = nullptr, THSParticle * part1 = nullptr, THSParticle * part2 = nullptr, THSParticle * part3 = nullptr, THSParticle * part4 = nullptr, THSParticle * part5 = nullptr, THSParticle * part6 = nullptr, THSParticle * part7 = nullptr, THSParticle * part8 = nullptr, THSParticle * part9 = nullptr)
THSParticleIter * THSFinalState::AddPermutateToRemainder (THSParticleIter * diter, THSParticle * part0 = nullptr, THSParticle * part1 = nullptr, THSParticle * part2 = nullptr, THSParticle * part3 = nullptr, THSParticle * part4 = nullptr, THSParticle * part5 = nullptr, THSParticle * part6 = nullptr, THSParticle * part7 = nullptr, THSParticle * part8 = nullptr, THSParticle * part9 = nullptr)
Interface to THSParticleIter Add permutate iterator to remaining particles
Definition at line 359 of file THSFinalState.C.
References AddPermutate(), and THSParticleIter::SetRemIter().
Referenced by FinalStateOutTree().
THSParticleIter* THSFinalState::AddPermutateToRemainder (THSParticleIter * diter, THSParticle * part0 = nullptr, THSParticle * part1 = nullptr, THSParticle * part2 = nullptr, THSParticle * part3 = nullptr, THSParticle * part4 = nullptr, THSParticle * part5 = nullptr, THSParticle * part6 = nullptr, THSParticle * part7 = nullptr, THSParticle * part8 = nullptr, THSParticle * part9 = nullptr)
THSParticleIter * THSFinalState::AddPermutateToSelected (THSParticleIter * diter, THSParticle * part0 = nullptr, THSParticle * part1 = nullptr, THSParticle * part2 = nullptr, THSParticle * part3 = nullptr, THSParticle * part4 = nullptr, THSParticle * part5 = nullptr, THSParticle * part6 = nullptr, THSParticle * part7 = nullptr, THSParticle * part8 = nullptr, THSParticle * part9 = nullptr)
Interface to THSParticleIter Add permutate iterator to previously selected particles
Definition at line 351 of file THSFinalState.C.
References AddPermutate(), and THSParticleIter::SetSelIter().
Referenced by FinalStateOutTree().
THSParticleIter* THSFinalState::AddPermutateToSelected (THSParticleIter * diter, THSParticle * part0 = nullptr, THSParticle * part1 = nullptr, THSParticle * part2 = nullptr, THSParticle * part3 = nullptr, THSParticle * part4 = nullptr, THSParticle * part5 = nullptr, THSParticle * part6 = nullptr, THSParticle * part7 = nullptr, THSParticle * part8 = nullptr, THSParticle * part9 = nullptr)
THSParticleIter * THSFinalState::AddSelectToRemainder (THSParticleIter * diter, Int_t nsel, Int_t ni, THSParticle * part0 = nullptr, THSParticle * part1 = nullptr, THSParticle * part2 = nullptr, THSParticle * part3 = nullptr, THSParticle * part4 = nullptr, THSParticle * part5 = nullptr, THSParticle * part6 = nullptr, THSParticle * part7 = nullptr, THSParticle * part8 = nullptr, THSParticle * part9 = nullptr)
Interface to THSParticleIter Add selected iterator to remaining particles
Definition at line 333 of file THSFinalState.C.
References AddSelectXofY(), and THSParticleIter::SetRemIter().
Referenced by FinalStateOutTree().
THSParticleIter* THSFinalState::AddSelectToRemainder (THSParticleIter * diter, Int_t nsel, Int_t ni, THSParticle * part0 = nullptr, THSParticle * part1 = nullptr, THSParticle * part2 = nullptr, THSParticle * part3 = nullptr, THSParticle * part4 = nullptr, THSParticle * part5 = nullptr, THSParticle * part6 = nullptr, THSParticle * part7 = nullptr, THSParticle * part8 = nullptr, THSParticle * part9 = nullptr)
THSParticleIter * THSFinalState::AddSelectToSelected (THSParticleIter * diter, Int_t nsel, Int_t ni, THSParticle * part0 = nullptr, THSParticle * part1 = nullptr, THSParticle * part2 = nullptr, THSParticle * part3 = nullptr, THSParticle * part4 = nullptr, THSParticle * part5 = nullptr, THSParticle * part6 = nullptr, THSParticle * part7 = nullptr, THSParticle * part8 = nullptr, THSParticle * part9 = nullptr)
Interface to THSParticleIter Add selected iterator to previously selected particles
Definition at line 324 of file THSFinalState.C.
References AddSelectXofY(), THSParticleIter::GetNSel(), and THSParticleIter::SetSelIter().
Referenced by FinalStateOutTree().
THSParticleIter* THSFinalState::AddSelectToSelected (THSParticleIter * diter, Int_t nsel, Int_t ni, THSParticle * part0 = nullptr, THSParticle * part1 = nullptr, THSParticle * part2 = nullptr, THSParticle * part3 = nullptr, THSParticle * part4 = nullptr, THSParticle * part5 = nullptr, THSParticle * part6 = nullptr, THSParticle * part7 = nullptr, THSParticle * part8 = nullptr, THSParticle * part9 = nullptr)
THSParticleIter* THSFinalState::AddSelectXofY (Int_t nsel, Int_t ni, THSParticle * part0 = nullptr, THSParticle * part1 = nullptr, THSParticle * part2 = nullptr, THSParticle * part3 = nullptr, THSParticle * part4 = nullptr, THSParticle * part5 = nullptr, THSParticle * part6 = nullptr, THSParticle * part7 = nullptr, THSParticle * part8 = nullptr, THSParticle * part9 = nullptr)
THSParticleIter * THSFinalState::AddSelectXofY (Int_t nsel, Int_t ni, THSParticle * part0 = nullptr, THSParticle * part1 = nullptr, THSParticle * part2 = nullptr, THSParticle * part3 = nullptr, THSParticle * part4 = nullptr, THSParticle * part5 = nullptr, THSParticle * part6 = nullptr, THSParticle * part7 = nullptr, THSParticle * part8 = nullptr, THSParticle * part9 = nullptr)
Interface to THSParticleIter Add selected iterator
Definition at line 341 of file THSFinalState.C.
References THSParticleIter::AddEventParticles(), and THSParticleIter::SelectXofY().
Referenced by AddSelectToRemainder(), AddSelectToSelected(), and FinalStateOutTree().
Int_t THSFinalState::AddTopology (TString topo)
Int_t THSFinalState::AddTopology (TString topo)
topo should be a pdg particle list seperated by : e.g. "proton:pi+:pi-"
Definition at line 43 of file THSFinalState.C.
References fDetTypes, fNTopo, fTopo, and fUseChargePID.
Referenced by SetGenParts().
void THSFinalState::CheckTruth () virtual
Check if our final vectors match with truth.
Examples:
THSFinalTemp.C.
Definition at line 305 of file THSFinalState.C.
References fCorrect, fFinal, fGotCorrectOne, fIsGenerated, and IsCorrectTruth().
Referenced by FinalStateOutTree(), and THSFinalTemp::WorkOnEvent().
virtual void THSFinalState::CheckTruth () virtual
THSParticleIter * THSFinalState::CreateParticleIter (Int_t topo, vector< THSParticle * > * parts, Int_t Nsel)
Interface to THSParticleIter Create particle iterator for a particticular species Given by the particle vector parts (e.g. fVecMinus)
Definition at line 379 of file THSFinalState.C.
References fDetIter, THSParticleIter::SetCombi(), THSParticleIter::SetNSel(), and THSParticleIter::SetParticles().
Referenced by FinalStateOutTree().
THSParticleIter* THSFinalState::CreateParticleIter (Int_t topo, vector< THSParticle * > * parts, Int_t Nsel)
virtual void THSFinalState::FinaliseEvent () inline virtual
Definition at line 36 of file THSFinalState12.h.
virtual void THSFinalState::FinaliseEvent () inline virtual
Definition at line 36 of file THSFinalState.h.
Referenced by ProcessEvent().
virtual void THSFinalState::FinalStateOutTree (TTree * tree) inline virtual
Reimplemented in THSFinalTemp.
Definition at line 130 of file THSFinalState.h.
References AddPermutate(), AddPermutateToRemainder(), AddPermutateToSelected(), AddSelectToRemainder(), AddSelectToSelected(), AddSelectXofY(), CheckTruth(), and CreateParticleIter().
virtual void THSFinalState::FinalStateOutTree (TTree * tree) inline virtual
Reimplemented in THSFinalTemp.
Definition at line 130 of file THSFinalState12.h.
References AddPermutate(), AddPermutateToRemainder(), AddPermutateToSelected(), AddSelectToRemainder(), AddSelectToSelected(), AddSelectXofY(), CheckTruth(), and CreateParticleIter().
Int_t THSFinalState::FindInclusiveTopology (Int_t incType = -1E9)
Note particles with TruthOnly are reserved for undetected particles which may be kept in simulated data, but shouldn't be included in final state check
Definition at line 113 of file THSFinalState.C.
References fCurrTopo, fNParts, fNTopo, frDetParts, fTopo, fUseChargePID, InitParticles(), and IsPermutating().
Referenced by GetTopology().
Int_t THSFinalState::FindInclusiveTopology (Int_t incType = -1E9)
Int_t THSFinalState::FindTopology ()
Note particles with TruthOnly are reserved for undetected particles which may be kept in simulated data, but shouldn't be included in final state check
Examples:
THSFinalTemp.C.
Definition at line 78 of file THSFinalState.C.
References fCurrTopo, fNParts, fNTopo, frDetParts, fTopo, fUseChargePID, InitParticles(), and IsPermutating().
Referenced by GetTopology(), and THSFinalTemp::WorkOnEvent().
Int_t THSFinalState::FindTopology ()
virtual void THSFinalState::GetEvent (Long64_t uid) inline virtual
Definition at line 34 of file THSFinalState12.h.
virtual void THSFinalState::GetEvent (Long64_t uid) inline virtual
Definition at line 34 of file THSFinalState.h.
vector<Int_t> THSFinalState::GetTopology (Int_t i) inline
Definition at line 43 of file THSFinalState.h.
References FindInclusiveTopology(), FindTopology(), and fTopo.
vector<Int_t> THSFinalState::GetTopology (Int_t i) inline
Definition at line 43 of file THSFinalState12.h.
References FindInclusiveTopology(), FindTopology(), and fTopo.
void THSFinalState::InitDetParts () protected
Read in the particles from this input event Place detected particles in array associated with their pdg type Loop over detected particles
Definition at line 196 of file THSFinalState.C.
References fMapPDGtoParticle, fNParts, frDetParts, and THSParticle::PDG().
Referenced by InitParticles(), and IsMissing().
void THSFinalState::InitDetParts () protected
void THSFinalState::InitDetPartsCharge () protected
Read in the particles from this input event assign them in vectors corrsponing to their charge
Definition at line 212 of file THSFinalState.C.
References THSParticle::Charge(), fMapPDGtoParticle, fNParts, and frDetParts.
Referenced by InitParticles(), and IsMissing().
void THSFinalState::InitDetPartsCharge () protected
virtual void THSFinalState::InitEvent () inline virtual
Definition at line 37 of file THSFinalState.h.
References fGotCorrectOne, and fNPerm.
Referenced by ProcessEvent().
virtual void THSFinalState::InitEvent () inline virtual
Definition at line 37 of file THSFinalState12.h.
References fGotCorrectOne, and fNPerm.
virtual void THSFinalState::InitGenerated () inline protected virtual
Definition at line 62 of file THSFinalState12.h.
References fCorrect, fGotCorrectOne, fIsInclusive, and fUseChargePID.
virtual void THSFinalState::InitGenerated () inline protected virtual
Definition at line 62 of file THSFinalState.h.
void THSFinalState::InitParticles () protected
Read in the particles from this input event and Get the first combination from the particle iterator
Definition at line 172 of file THSFinalState.C.
References fCurrTopo, fDetIter, fIsPermutating0, fUseChargePID, InitDetParts(), and InitDetPartsCharge().
Referenced by FindInclusiveTopology(), FindTopology(), and IsMissing().
void THSFinalState::InitParticles () protected
virtual Bool_t THSFinalState::IsCorrectTruth (THSParticle * part) virtual
Bool_t THSFinalState::IsCorrectTruth (THSParticle * part) virtual
Loop through generated and record momentum distance if the nearest generated track is the same as the TRUTH return true
Definition at line 284 of file THSFinalState.C.
References frGenParts, THSParticle::p3Distance(), THSParticle::P4p(), THSParticle::TruthP4(), and THSParticle::TruthPDG().
Referenced by CheckTruth(), and IsPermutating().
Bool_t THSFinalState::IsGoodEvent () inline
Definition at line 125 of file THSFinalState.h.
References fGoodEvent.
Referenced by ProcessEvent().
Bool_t THSFinalState::IsGoodEvent () inline
Definition at line 125 of file THSFinalState12.h.
References fGoodEvent.
Bool_t THSFinalState::IsMissing (THSParticle * part) inline protected
Definition at line 71 of file THSFinalState.h.
References THSParticle::P4p().
Bool_t THSFinalState::IsMissing (THSParticle * part) inline protected
Definition at line 71 of file THSFinalState12.h.
References fDetIter, fDetTypes, fFinal, fFinalTree, fIsPermutating0, fIsPermutating1, fIterLevel, fKine, fMapPDGtoParticle, fNPerm, frDetParts, frGenParts, fTryPerm, fUID, fVec0, fVecBeams, fVecEls, fVecGams, fVecKMs, fVecKPs, fVecMinus, fVecPi0s, fVecPiMs, fVecPiPs, fVecPlus, fVecPos, fVecProtons, InitDetParts(), InitDetPartsCharge(), InitParticles(), THSParticle::P4p(), and PermutateParticles().
virtual Bool_t THSFinalState::IsPermutating () inline virtual
Definition at line 126 of file THSFinalState.h.
References fIsPermutating1, IsCorrectTruth(), MatchWithGen(), and ProcessEvent().
Referenced by FindInclusiveTopology(), FindTopology(), and ProcessEvent().
virtual Bool_t THSFinalState::IsPermutating () inline virtual
Definition at line 126 of file THSFinalState12.h.
References fIsPermutating1, IsCorrectTruth(), MatchWithGen(), and ProcessEvent().
virtual void THSFinalState::MatchWithGen (THSParticle * part) virtual
void THSFinalState::MatchWithGen (THSParticle * part) virtual
Loop through generated and record momentum distance.
Definition at line 267 of file THSFinalState.C.
References frGenParts, THSParticle::p3Distance(), THSParticle::P4p(), and THSParticle::SetTruth().
Referenced by IsPermutating().
Bool_t THSFinalState::PermutateParticles () protected
Bool_t THSFinalState::PermutateParticles () protected
returns true if another valid permuation to be tried
returns false when time to move on
Check through particle types, if more than 1 of a type permutate through all combinations
Examples:
THSFinalTemp.C.
Definition at line 252 of file THSFinalState.C.
References fCurrTopo, fDetIter, fIsPermutating0, fIsPermutating1, fNPerm, and fTryPerm.
Referenced by IsMissing(), and THSFinalTemp::WorkOnEvent().
virtual void THSFinalState::ProcessEvent () virtual
void THSFinalState::ProcessEvent () virtual
Process one event from the input tree.
Definition at line 227 of file THSFinalState.C.
References fFinalTree, FinaliseEvent(), fNDet, fNUsedReadEvent, frDetParts, fUID, InitEvent(), IsGoodEvent(), IsPermutating(), and WorkOnEvent().
Referenced by IsPermutating().
void THSFinalState::SetDetParts (vector< THSParticle * > * dpp) inline
Definition at line 39 of file THSFinalState12.h.
References frDetParts.
void THSFinalState::SetDetParts (vector< THSParticle * > * dpp) inline
Definition at line 39 of file THSFinalState.h.
References frDetParts.
void THSFinalState::SetGenerated (Bool_t gen = kTRUE) inline
Definition at line 48 of file THSFinalState12.h.
References fIsGenerated.
void THSFinalState::SetGenerated (Bool_t gen = kTRUE) inline
Definition at line 48 of file THSFinalState.h.
References fIsGenerated.
void THSFinalState::SetGenParts (vector< THSParticle * > * dpp) inline
Definition at line 40 of file THSFinalState.h.
References AddTopology(), and frGenParts.
void THSFinalState::SetGenParts (vector< THSParticle * > * dpp) inline
Definition at line 40 of file THSFinalState12.h.
References AddTopology(), and frGenParts.
void THSFinalState::SetInclusive () inline
Definition at line 47 of file THSFinalState12.h.
References fIsInclusive.
void THSFinalState::SetInclusive () inline
Definition at line 47 of file THSFinalState.h.
References fIsInclusive.
void THSFinalState::SetPermutate () inline
Definition at line 46 of file THSFinalState.h.
References fTryPerm.
void THSFinalState::SetPermutate () inline
Definition at line 46 of file THSFinalState12.h.
References fTryPerm.
void THSFinalState::SetUseChargePID (Bool_t gen = kTRUE) inline
Definition at line 49 of file THSFinalState12.h.
References fCurrTopo, fGoodEvent, fIsGenerated, fNDet, fNGen, fNParts, fNTopo, fNUsedReadEvent, fTopo, and fUseChargePID.
void THSFinalState::SetUseChargePID (Bool_t gen = kTRUE) inline
Definition at line 49 of file THSFinalState.h.
References fUseChargePID.
virtual Bool_t THSFinalState::WorkOnEvent () inline virtual
Reimplemented in THSFinalTemp.
Definition at line 35 of file THSFinalState.h.
Referenced by ProcessEvent().
virtual Bool_t THSFinalState::WorkOnEvent () inline virtual
Reimplemented in THSFinalTemp.
Definition at line 35 of file THSFinalState12.h.
Member Data Documentation
Int_t THSFinalState::fCorrect =kTRUE protected
Examples:
THSFinalTemp.C.
Definition at line 64 of file THSFinalState.h.
Referenced by CheckTruth(), InitGenerated(), and THSFinalTemp::WorkOnEvent().
Int_t THSFinalState::fCurrTopo =-1 protected
Definition at line 55 of file THSFinalState.h.
Referenced by FindInclusiveTopology(), FindTopology(), InitParticles(), PermutateParticles(), and SetUseChargePID().
vector< THSParticleIter * > THSFinalState::fDetIter protected
Examples:
THSFinalTemp.C.
Definition at line 94 of file THSFinalState.h.
Referenced by CreateParticleIter(), InitParticles(), IsMissing(), PermutateParticles(), THSFinalTemp::THSFinalTemp(), and ~THSFinalState().
vector< Int_t > THSFinalState::fDetTypes protected
Definition at line 92 of file THSFinalState.h.
Referenced by AddTopology(), and IsMissing().
vector< THSParticle * > THSFinalState::fFinal protected
Examples:
THSFinalTemp.C.
Definition at line 118 of file THSFinalState.h.
Referenced by CheckTruth(), THSFinalTemp::FinalStateOutTree(), and IsMissing().
TTree * THSFinalState::fFinalTree =nullptr protected
Examples:
THSFinalTemp.C.
Definition at line 105 of file THSFinalState.h.
Referenced by THSFinalTemp::FinalStateOutTree(), IsMissing(), and ProcessEvent().
Bool_t THSFinalState::fGoodEvent = kTRUE protected
Examples:
THSFinalTemp.C.
Definition at line 58 of file THSFinalState.h.
Referenced by THSFinalTemp::Init_Generated(), IsGoodEvent(), THSFinalTemp::Kinematics(), SetUseChargePID(), and THSFinalTemp::WorkOnEvent().
Bool_t THSFinalState::fGotCorrectOne =kFALSE protected
Definition at line 65 of file THSFinalState.h.
Referenced by CheckTruth(), InitEvent(), and InitGenerated().
Bool_t THSFinalState::fIsGenerated =kFALSE protected
Examples:
THSFinalTemp.C.
Definition at line 61 of file THSFinalState.h.
Referenced by CheckTruth(), THSFinalTemp::Init_Generated(), SetGenerated(), SetUseChargePID(), and THSFinalTemp::WorkOnEvent().
Bool_t THSFinalState::fIsInclusive =kFALSE protected
Definition at line 68 of file THSFinalState.h.
Referenced by InitGenerated(), and SetInclusive().
Bool_t THSFinalState::fIsPermutating0 =kFALSE protected
Examples:
THSFinalTemp.C.
Definition at line 102 of file THSFinalState.h.
Referenced by InitParticles(), IsMissing(), PermutateParticles(), and THSFinalTemp::WorkOnEvent().
Bool_t THSFinalState::fIsPermutating1 =kFALSE protected
Definition at line 103 of file THSFinalState.h.
Referenced by IsMissing(), IsPermutating(), and PermutateParticles().
Int_t THSFinalState::fIterLevel =0 protected
Definition at line 96 of file THSFinalState.h.
Referenced by IsMissing().
THSKinematics THSFinalState::fKine protected
Definition at line 108 of file THSFinalState.h.
Referenced by IsMissing().
map< Int_t, vector< THSParticle * > * > THSFinalState::fMapPDGtoParticle protected
Definition at line 99 of file THSFinalState.h.
Referenced by InitDetParts(), InitDetPartsCharge(), IsMissing(), and THSFinalState().
Int_t THSFinalState::fNDet =0 protected
Definition at line 52 of file THSFinalState.h.
Referenced by ProcessEvent(), and SetUseChargePID().
UInt_t THSFinalState::fNGen =0 protected
Definition at line 57 of file THSFinalState.h.
Referenced by SetUseChargePID().
UInt_t THSFinalState::fNParts =0 protected
Definition at line 56 of file THSFinalState.h.
Referenced by FindInclusiveTopology(), FindTopology(), InitDetParts(), InitDetPartsCharge(), and SetUseChargePID().
Int_t THSFinalState::fNPerm =0 protected
Definition at line 73 of file THSFinalState.h.
Referenced by InitEvent(), IsMissing(), and PermutateParticles().
Int_t THSFinalState::fNTopo =0 protected
Examples:
THSFinalTemp.C.
Definition at line 54 of file THSFinalState.h.
Referenced by AddTopology(), FindInclusiveTopology(), FindTopology(), SetUseChargePID(), and THSFinalTemp::THSFinalTemp().
Long64_t THSFinalState::fNUsedReadEvent =0 protected
Definition at line 59 of file THSFinalState.h.
Referenced by ProcessEvent(), and SetUseChargePID().
vector< THSParticle * > * THSFinalState::frDetParts =nullptr protected
Definition at line 114 of file THSFinalState.h.
Referenced by FindInclusiveTopology(), FindTopology(), InitDetParts(), InitDetPartsCharge(), IsMissing(), ProcessEvent(), and SetDetParts().
vector< THSParticle * > * THSFinalState::frGenParts =nullptr protected
Examples:
THSFinalTemp.C.
Definition at line 115 of file THSFinalState.h.
Referenced by THSFinalTemp::Init_Generated(), IsCorrectTruth(), IsMissing(), MatchWithGen(), and SetGenParts().
vector< vector< Int_t > > THSFinalState::fTopo protected
Definition at line 53 of file THSFinalState.h.
Referenced by AddTopology(), FindInclusiveTopology(), FindTopology(), GetTopology(), and SetUseChargePID().
Bool_t THSFinalState::fTryPerm =kFALSE protected
Definition at line 72 of file THSFinalState.h.
Referenced by IsMissing(), PermutateParticles(), and SetPermutate().
Double_t THSFinalState::fUID =0 protected
Definition at line 111 of file THSFinalState.h.
Referenced by IsMissing(), and ProcessEvent().
Bool_t THSFinalState::fUseChargePID =kFALSE protected
Definition at line 67 of file THSFinalState.h.
Referenced by AddTopology(), FindInclusiveTopology(), FindTopology(), InitGenerated(), InitParticles(), and SetUseChargePID().
vector< THSParticle * > THSFinalState::fVec0 protected
Definition at line 90 of file THSFinalState.h.
Referenced by IsMissing(), and THSFinalState().
vector< THSParticle * > THSFinalState::fVecBeams protected
Definition at line 91 of file THSFinalState.h.
Referenced by IsMissing(), and THSFinalState().
vector< THSParticle * > THSFinalState::fVecEls protected
Definition at line 84 of file THSFinalState.h.
Referenced by IsMissing(), and THSFinalState().
vector< THSParticle * > THSFinalState::fVecGams protected
Definition at line 87 of file THSFinalState.h.
Referenced by IsMissing(), and THSFinalState().
vector< THSParticle * > THSFinalState::fVecKMs protected
Definition at line 83 of file THSFinalState.h.
Referenced by IsMissing(), and THSFinalState().
vector< THSParticle * > THSFinalState::fVecKPs protected
Definition at line 82 of file THSFinalState.h.
Referenced by IsMissing(), and THSFinalState().
vector< THSParticle * > THSFinalState::fVecMinus protected
Definition at line 89 of file THSFinalState.h.
Referenced by IsMissing(), and THSFinalState().
vector< THSParticle * > THSFinalState::fVecPi0s protected
Definition at line 86 of file THSFinalState.h.
Referenced by IsMissing(), and THSFinalState().
vector< THSParticle * > THSFinalState::fVecPiMs protected
Definition at line 81 of file THSFinalState.h.
Referenced by IsMissing(), and THSFinalState().
vector< THSParticle * > THSFinalState::fVecPiPs protected
Definition at line 80 of file THSFinalState.h.
Referenced by IsMissing(), and THSFinalState().
vector< THSParticle * > THSFinalState::fVecPlus protected
Definition at line 88 of file THSFinalState.h.
Referenced by IsMissing(), and THSFinalState().
vector< THSParticle * > THSFinalState::fVecPos protected
Definition at line 85 of file THSFinalState.h.
Referenced by IsMissing(), and THSFinalState().
vector< THSParticle * > THSFinalState::fVecProtons protected
Definition at line 79 of file THSFinalState.h.
Referenced by IsMissing(), and THSFinalState().
The documentation for this class was generated from the following files:
HaSpect/THSFinalState.h
HaSpect/THSFinalState12.h
HaSpect/THSFinalState.C
HaSpect/THSFinalState12.C