HASPECT6: RooHSsPlotAndFitStudy Class Reference
RooHSsPlotAndFitStudy Class Reference
Definition at line 23 of file RooHSsPlotAndFitStudy.h.
#include <RooHSsPlotAndFitStudy.h>
Public Member Functions
RooHSsPlotAndFitStudy (const char *name=0, const char *title=0)
RooHSsPlotAndFitStudy (const RooHSsPlotAndFitStudy &other)
virtual ~RooHSsPlotAndFitStudy ()
virtual RooAbsStudy * clone (const char *newname="") const
virtual Bool_t attach (RooWorkspace &w)
virtual Bool_t initialize ()
virtual Bool_t execute ()
virtual Bool_t finalize ()
virtual Bool_t terminate ()
virtual void GenHSRooFit (THSRooFit *rf)
virtual void FitHSsPlot (THSsPlot *sp, TString species)
virtual void FitHSRooFit (THSRooFit *rf)
void SetPDFName (TString pdf)
void Print (Option_t *options=0) const
RooWorkspace * GetWorkSpace ()
THSRooFit * GetRooFit ()
void SetOutDir (TString dir)
TString GetOutDir ()
void SetPlot (Bool_t plot=kTRUE)
void UseAll (Bool_t all=kTRUE)
Protected Attributes
RooAbsPdf * _genPdf =0
RooArgSet _genObs
RooAbsPdf * _fitPdf =0
RooArgSet _fitObs
RooRealVar * _nllVar =0
RooRealVar * _ngenVar =0
RooArgSet * _params =0
RooArgSet * _initParams =0
THSRooFit * fGenRooFit =0
THSRooFit * fHSRooFit =0
TList * fsPlots =0
RooWorkspace * fWS =0
TString fOutDir
Bool_t fIsCloned =kFALSE
Bool_t fIsPlot =kFALSE
Bool_t fUseAll =kFALSE
TString fPDFName
Long64_t fGeni =0
Constructor & Destructor Documentation
RooHSsPlotAndFitStudy::RooHSsPlotAndFitStudy (const char * name = 0, const char * title = 0)
Referenced by clone().
RooHSsPlotAndFitStudy::RooHSsPlotAndFitStudy (const RooHSsPlotAndFitStudy & other)
Definition at line 38 of file RooHSsPlotAndFitStudy.C.
References fGenRooFit, fHSRooFit, fIsCloned, fIsPlot, fOutDir, fsPlots, fUseAll, fWS, and THSRooFit::GetWorkSpace().
RooHSsPlotAndFitStudy::~RooHSsPlotAndFitStudy () virtual
Definition at line 59 of file RooHSsPlotAndFitStudy.C.
References fGenRooFit, fHSRooFit, fIsCloned, and fsPlots.
Member Function Documentation
Bool_t RooHSsPlotAndFitStudy::attach (RooWorkspace & w) virtual
Definition at line 73 of file RooHSsPlotAndFitStudy.C.
References fGenRooFit, fHSRooFit, fIsPlot, fOutDir, fsPlots, fWS, THSRooFit::LoadWorkSpace(), THSRooFit::SetOutDir(), THSRooFit::SetPlot(), and THSRooFit::TotalPDF().
Referenced by clone().
virtual RooAbsStudy* RooHSsPlotAndFitStudy::clone (const char * newname = "") const inline virtual
Definition at line 29 of file RooHSsPlotAndFitStudy.h.
References attach(), execute(), finalize(), initialize(), RooHSsPlotAndFitStudy(), and terminate().
Bool_t RooHSsPlotAndFitStudy::execute () virtual
Definition at line 118 of file RooHSsPlotAndFitStudy.C.
References _ngenVar, _nllVar, _params, THSRooFit::CleanWSDataSets(), THSsPlot::DeleteWeights(), fGenRooFit, fHSRooFit, THSRooFit::Fit(), fsPlots, fWS, THSRooFit::GetModel(), THSRooFit::GetResult(), THSRooFit::GetVariables(), THSsPlot::GetWeights(), THSRooFit::LoadDataSet(), THSRooFit::LoadWeights(), THSRooFit::RemoveDataSet(), THSRooFit::SetDataWeightFast(), THSRooFit::SetPlot(), THSsPlot::SetSaveWeights(), THSRooFit::SetWeightName(), and THSsPlot::sPlot().
Referenced by clone().
Bool_t RooHSsPlotAndFitStudy::finalize () virtual
Definition at line 198 of file RooHSsPlotAndFitStudy.C.
References _initParams, _ngenVar, _nllVar, _params, and fWS.
Referenced by clone().
virtual void RooHSsPlotAndFitStudy::FitHSRooFit (THSRooFit * rf) inline virtual
Definition at line 39 of file RooHSsPlotAndFitStudy.h.
References fHSRooFit.
virtual void RooHSsPlotAndFitStudy::FitHSsPlot (THSsPlot * sp, TString species) inline virtual
Definition at line 38 of file RooHSsPlotAndFitStudy.h.
References fsPlots.
virtual void RooHSsPlotAndFitStudy::GenHSRooFit (THSRooFit * rf) inline virtual
Definition at line 37 of file RooHSsPlotAndFitStudy.h.
References fGenRooFit.
TString RooHSsPlotAndFitStudy::GetOutDir () inline
Definition at line 46 of file RooHSsPlotAndFitStudy.h.
References fOutDir.
THSRooFit* RooHSsPlotAndFitStudy::GetRooFit () inline
Definition at line 44 of file RooHSsPlotAndFitStudy.h.
References fHSRooFit.
RooWorkspace* RooHSsPlotAndFitStudy::GetWorkSpace () inline
Definition at line 43 of file RooHSsPlotAndFitStudy.h.
References fWS.
Bool_t RooHSsPlotAndFitStudy::initialize () virtual
Definition at line 95 of file RooHSsPlotAndFitStudy.C.
References _initParams, _ngenVar, _nllVar, _params, THSRooFit::AddFitOption(), fHSRooFit, fWS, THSRooFit::GetParameters(), and THSRooFit::GetYields().
Referenced by clone().
void RooHSsPlotAndFitStudy::Print (Option_t * options = 0) const
Definition at line 221 of file RooHSsPlotAndFitStudy.C.
Referenced by SetPDFName().
void RooHSsPlotAndFitStudy::SetOutDir (TString dir) inline
Definition at line 45 of file RooHSsPlotAndFitStudy.h.
References fOutDir.
void RooHSsPlotAndFitStudy::SetPDFName (TString pdf) inline
Definition at line 41 of file RooHSsPlotAndFitStudy.h.
References fPDFName, and Print().
void RooHSsPlotAndFitStudy::SetPlot (Bool_t plot = kTRUE) inline
Definition at line 47 of file RooHSsPlotAndFitStudy.h.
References fIsPlot.
Bool_t RooHSsPlotAndFitStudy::terminate () virtual
Definition at line 224 of file RooHSsPlotAndFitStudy.C.
References fGenRooFit, fHSRooFit, fOutDir, fWS, THSRooFit::GetParameters(), and THSRooFit::GetWorkSpace().
Referenced by clone().
void RooHSsPlotAndFitStudy::UseAll (Bool_t all = kTRUE) inline
Definition at line 48 of file RooHSsPlotAndFitStudy.h.
References fUseAll.
Member Data Documentation
RooArgSet RooHSsPlotAndFitStudy::_fitObs protected
Definition at line 55 of file RooHSsPlotAndFitStudy.h.
RooAbsPdf* RooHSsPlotAndFitStudy::_fitPdf =0 protected
Definition at line 54 of file RooHSsPlotAndFitStudy.h.
RooArgSet RooHSsPlotAndFitStudy::_genObs protected
Definition at line 53 of file RooHSsPlotAndFitStudy.h.
RooAbsPdf* RooHSsPlotAndFitStudy::_genPdf =0 protected
Definition at line 52 of file RooHSsPlotAndFitStudy.h.
RooArgSet* RooHSsPlotAndFitStudy::_initParams =0 protected
Definition at line 60 of file RooHSsPlotAndFitStudy.h.
Referenced by finalize(), and initialize().
RooRealVar* RooHSsPlotAndFitStudy::_ngenVar =0 protected
Definition at line 58 of file RooHSsPlotAndFitStudy.h.
Referenced by execute(), finalize(), and initialize().
RooRealVar* RooHSsPlotAndFitStudy::_nllVar =0 protected
Definition at line 57 of file RooHSsPlotAndFitStudy.h.
Referenced by execute(), finalize(), and initialize().
RooArgSet* RooHSsPlotAndFitStudy::_params =0 protected
Definition at line 59 of file RooHSsPlotAndFitStudy.h.
Referenced by execute(), finalize(), and initialize().
Long64_t RooHSsPlotAndFitStudy::fGeni =0 protected
Definition at line 72 of file RooHSsPlotAndFitStudy.h.
THSRooFit* RooHSsPlotAndFitStudy::fGenRooFit =0 protected
Definition at line 62 of file RooHSsPlotAndFitStudy.h.
Referenced by attach(), execute(), GenHSRooFit(), RooHSsPlotAndFitStudy(), terminate(), and ~RooHSsPlotAndFitStudy().
THSRooFit* RooHSsPlotAndFitStudy::fHSRooFit =0 protected
Definition at line 63 of file RooHSsPlotAndFitStudy.h.
Referenced by attach(), execute(), FitHSRooFit(), GetRooFit(), initialize(), RooHSsPlotAndFitStudy(), terminate(), and ~RooHSsPlotAndFitStudy().
Bool_t RooHSsPlotAndFitStudy::fIsCloned =kFALSE protected
Definition at line 68 of file RooHSsPlotAndFitStudy.h.
Referenced by RooHSsPlotAndFitStudy(), and ~RooHSsPlotAndFitStudy().
Bool_t RooHSsPlotAndFitStudy::fIsPlot =kFALSE protected
Definition at line 69 of file RooHSsPlotAndFitStudy.h.
Referenced by attach(), RooHSsPlotAndFitStudy(), and SetPlot().
TString RooHSsPlotAndFitStudy::fOutDir protected
Definition at line 66 of file RooHSsPlotAndFitStudy.h.
Referenced by attach(), GetOutDir(), RooHSsPlotAndFitStudy(), SetOutDir(), and terminate().
TString RooHSsPlotAndFitStudy::fPDFName protected
Definition at line 71 of file RooHSsPlotAndFitStudy.h.
Referenced by SetPDFName().
TList* RooHSsPlotAndFitStudy::fsPlots =0 protected
Definition at line 64 of file RooHSsPlotAndFitStudy.h.
Referenced by attach(), execute(), FitHSsPlot(), RooHSsPlotAndFitStudy(), and ~RooHSsPlotAndFitStudy().
Bool_t RooHSsPlotAndFitStudy::fUseAll =kFALSE protected
Definition at line 70 of file RooHSsPlotAndFitStudy.h.
Referenced by RooHSsPlotAndFitStudy(), and UseAll().
RooWorkspace* RooHSsPlotAndFitStudy::fWS =0 protected
Definition at line 65 of file RooHSsPlotAndFitStudy.h.
Referenced by attach(), execute(), finalize(), GetWorkSpace(), initialize(), RooHSsPlotAndFitStudy(), and terminate().
The documentation for this class was generated from the following files:
HaSpect/RooHSsPlotAndFitStudy.h
HaSpect/RooHSsPlotAndFitStudy.C