HASPECT6: RooHSEventsPDF Class Reference
RooHSEventsPDF Class Reference
Definition at line 16 of file RooHSEventsPDF.h.
#include <RooHSEventsPDF.h>
Public Member Functions
RooHSEventsPDF (const char *name, const char *title)
RooHSEventsPDF (const RooHSEventsPDF &other, const char *name=0)
RooHSEventsPDF ()
virtual ~RooHSEventsPDF ()
virtual Int_t getAnalyticalIntegral (RooArgSet &allVars, RooArgSet &analVars, const char *rangeName) const
virtual Double_t analyticalIntegral (Int_t code, const char *rangeName) const
virtual void generateEvent (Int_t code)
virtual Int_t getGenerator (const RooArgSet &directVars, RooArgSet &generateVars, Bool_t staticInitOK) const
virtual void initGenerator (Int_t code)
virtual void initIntegrator ()
virtual Double_t evaluateMC () const
virtual Bool_t CheckChange () const
Bool_t CheckRange (const char *rangeName) const
void SetNInt (Long64_t n)
virtual Bool_t SetEvTree (TChain *tree, Long64_t ngen=0)
virtual Bool_t SetEvTree (TTree *tree, Long64_t ngen=0)
void SetNMCGen (Long64_t N)
TTree * GetEvTree ()
TVectorD GetMCVar ()
TTree * GetGenTree ()
TEntryList * GetEntryList ()
void SetEntryList (TEntryList *elist)
void SetWeights (THSWeights *wgts)
void SetUseWeightsGen (Bool_t use=kTRUE)
Bool_t UseWeightsGen ()
THSWeights * GetWeights ()
void SetGeni (Long64_t gi)
Long64_t GetGeni ()
void SetConstInt (Bool_t force=kTRUE)
void SetNumInt (Bool_t force=kTRUE)
void CheckIntegralParDep (Int_t Ntests)
virtual void ResetTree ()
virtual Double_t GetIntegralWeight () const
Bool_t AddProtoData (RooDataSet *data)
Protected Member Functions
void InitSets ()
RooArgSet VarSet (Int_t iset) const
Protected Attributes
RooHSEventsPDF * fParent =nullptr
TTree * fEvTree =nullptr
TEntryList * fEntryList =nullptr
Double_t * fLast =nullptr
Long64_t fNInt =-1
Long64_t fNMCGen =0
Int_t fNpars =0
Int_t fNvars =0
Int_t fNcats =0
Bool_t fBranchStatus =kTRUE
Bool_t fIsIntegrating =kFALSE
Bool_t fIsClone =kFALSE
Bool_t fForceConstInt =kFALSE
Bool_t fForceNumInt =kFALSE
Bool_t fUseWeightsGen =kTRUE
Int_t fCheckInt =0
Double_t fConstInt =1
THSWeights * fWeights =nullptr
THSWeights * fInWeights =nullptr
vector< RooArgSet * > fVarSet
vector< RooRealProxy * > fProxSet
vector< RooCategoryProxy * > fCatSet
TVectorD fMCVar
vector< Int_t > fMCCat
vector< RooRealProxy * > fParSet
vector< Bool_t > fIsCat
Double_t fMaxValue =0
Long64_t fGeni =0
TString fgenStr ="gen"
Constructor & Destructor Documentation
RooHSEventsPDF::RooHSEventsPDF (const char * name, const char * title) inline
Definition at line 18 of file RooHSEventsPDF.h.
References RooHSEventsPDF().
RooHSEventsPDF::RooHSEventsPDF (const RooHSEventsPDF & other, const char * name = 0)
RooHSEventsPDF::RooHSEventsPDF () inline
Definition at line 23 of file RooHSEventsPDF.h.
References ~RooHSEventsPDF().
Referenced by RooHSEventsPDF().
RooHSEventsPDF::~RooHSEventsPDF () virtual
Definition at line 37 of file RooHSEventsPDF.C.
References fEntryList, fEvTree, fGeni, fIsClone, fLast, fMaxValue, fParent, fVarSet, fWeights, THSWeights::Save(), SetEntryList(), and SetGeni().
Referenced by RooHSEventsPDF().
Member Function Documentation
Bool_t RooHSEventsPDF::AddProtoData (RooDataSet * data)
Definition at line 446 of file RooHSEventsPDF.C.
References fBranchStatus, fEvTree, SetEvTree(), and VarSet().
Referenced by THSRooFit::FitBatchBin(), THSRooFit::FitSavedBins(), and GetIntegralWeight().
Double_t RooHSEventsPDF::analyticalIntegral (Int_t code, const char * rangeName) const virtual
Reimplemented in RooHSEventsHistPDF.
Definition at line 227 of file RooHSEventsPDF.C.
References CheckChange(), CheckRange(), evaluateMC(), fEvTree, fForceConstInt, fLast, fMCVar, fNInt, fNMCGen, fProxSet, and GetIntegralWeight().
Referenced by CheckIntegralParDep().
Bool_t RooHSEventsPDF::CheckChange () const virtual
Definition at line 299 of file RooHSEventsPDF.C.
References fLast, fNpars, and fParSet.
Referenced by analyticalIntegral(), RooHSEventsHistPDF::analyticalIntegral(), and evaluateMC().
void RooHSEventsPDF::CheckIntegralParDep (Int_t Ntests)
Definition at line 367 of file RooHSEventsPDF.C.
References analyticalIntegral(), fBranchStatus, fCheckInt, fConstInt, fEvTree, fNInt, fParSet, and SetConstInt().
Referenced by SetEvTree(), and SetNumInt().
Bool_t RooHSEventsPDF::CheckRange (const char * rangeName) const
Definition at line 291 of file RooHSEventsPDF.C.
References fMCVar, and fProxSet.
Referenced by analyticalIntegral(), evaluateMC(), and generateEvent().
virtual Double_t RooHSEventsPDF::evaluateMC () const inline virtual
Reimplemented in RooHSEventsHistPDF.
Definition at line 74 of file RooHSEventsPDF.h.
References CheckChange(), and CheckRange().
Referenced by analyticalIntegral(), generateEvent(), and initGenerator().
void RooHSEventsPDF::generateEvent (Int_t code) virtual
Definition at line 170 of file RooHSEventsPDF.C.
References CheckRange(), evaluateMC(), fCatSet, fEntryList, fEvTree, fGeni, THSWeights::FillWeight(), fMaxValue, fMCCat, fMCVar, fNcats, fNvars, fProxSet, fUseWeightsGen, fWeights, and GetIntegralWeight().
Int_t RooHSEventsPDF::getAnalyticalIntegral (RooArgSet & allVars, RooArgSet & analVars, const char * rangeName) const virtual
Reimplemented in RooHSEventsHistPDF.
Definition at line 207 of file RooHSEventsPDF.C.
References fEvTree, fForceConstInt, fForceNumInt, fProxSet, and VarSet().
Referenced by RooHSEventsHistPDF::getAnalyticalIntegral().
TEntryList* RooHSEventsPDF::GetEntryList () inline
Definition at line 87 of file RooHSEventsPDF.h.
References fEntryList.
TTree* RooHSEventsPDF::GetEvTree () inline
Definition at line 84 of file RooHSEventsPDF.h.
References fEvTree.
Int_t RooHSEventsPDF::getGenerator (const RooArgSet & directVars, RooArgSet & generateVars, Bool_t staticInitOK) const virtual
Definition at line 88 of file RooHSEventsPDF.C.
References fEvTree, and VarSet().
Long64_t RooHSEventsPDF::GetGeni () inline
Definition at line 94 of file RooHSEventsPDF.h.
References fGeni.
Referenced by RooHS1StepStudy::execute().
TTree* RooHSEventsPDF::GetGenTree () inline
Definition at line 86 of file RooHSEventsPDF.h.
Referenced by RooHS1StepStudy::execute().
virtual Double_t RooHSEventsPDF::GetIntegralWeight () const inline virtual
Definition at line 99 of file RooHSEventsPDF.h.
References AddProtoData().
Referenced by analyticalIntegral(), RooHSEventsHistPDF::analyticalIntegral(), generateEvent(), and initGenerator().
TVectorD RooHSEventsPDF::GetMCVar () inline
Definition at line 85 of file RooHSEventsPDF.h.
References fMCVar.
THSWeights* RooHSEventsPDF::GetWeights () inline
Definition at line 92 of file RooHSEventsPDF.h.
References fWeights.
void RooHSEventsPDF::initGenerator (Int_t code) virtual
Definition at line 114 of file RooHSEventsPDF.C.
References evaluateMC(), fCatSet, fEntryList, fEvTree, fGeni, fgenStr, fMaxValue, fMCCat, fMCVar, fProxSet, fUseWeightsGen, fWeights, GetIntegralWeight(), THSWeights::SetFile(), and THSWeights::SetSpecies().
void RooHSEventsPDF::initIntegrator () virtual
Definition at line 97 of file RooHSEventsPDF.C.
References fCatSet, fEvTree, fMCCat, fMCVar, and fProxSet.
Referenced by RooHS1StepStudy::execute().
void RooHSEventsPDF::InitSets () protected
Definition at line 60 of file RooHSEventsPDF.C.
References fCatSet, fLast, fNcats, fNpars, fNvars, fParSet, and fProxSet.
Referenced by RooHSEventsHistPDF::MakeSets().
void RooHSEventsPDF::ResetTree () virtual
Reimplemented in RooHSEventsHistPDF.
Definition at line 529 of file RooHSEventsPDF.C.
References fEvTree.
Referenced by THSRooFit::FitSavedBins(), RooHSEventsHistPDF::ResetTree(), and SetNumInt().
void RooHSEventsPDF::SetConstInt (Bool_t force = kTRUE) inline
Definition at line 95 of file RooHSEventsPDF.h.
Referenced by CheckIntegralParDep().
void RooHSEventsPDF::SetEntryList (TEntryList * elist) inline
Definition at line 88 of file RooHSEventsPDF.h.
Referenced by ~RooHSEventsPDF().
Bool_t RooHSEventsPDF::SetEvTree (TChain * tree, Long64_t ngen = 0) virtual
Reimplemented in RooHSEventsHistPDF.
Definition at line 313 of file RooHSEventsPDF.C.
Referenced by AddProtoData(), THSRooFit::FitBatchBin(), THSRooFit::FitSavedBins(), RooHSEventsHistPDF::SetEvTree(), and SetNInt().
Bool_t RooHSEventsPDF::SetEvTree (TTree * tree, Long64_t ngen = 0) virtual
Reimplemented in RooHSEventsHistPDF.
Definition at line 317 of file RooHSEventsPDF.C.
References CheckIntegralParDep(), fBranchStatus, fCatSet, fCheckInt, fConstInt, fEvTree, fMCCat, fMCVar, fNMCGen, and fProxSet.
void RooHSEventsPDF::SetGeni (Long64_t gi) inline
Definition at line 93 of file RooHSEventsPDF.h.
Referenced by RooHS1StepStudy::execute(), and ~RooHSEventsPDF().
void RooHSEventsPDF::SetNInt (Long64_t n) inline
Definition at line 80 of file RooHSEventsPDF.h.
References SetEvTree().
void RooHSEventsPDF::SetNMCGen (Long64_t N) inline
Definition at line 83 of file RooHSEventsPDF.h.
void RooHSEventsPDF::SetNumInt (Bool_t force = kTRUE) inline
Definition at line 96 of file RooHSEventsPDF.h.
References CheckIntegralParDep(), and ResetTree().
void RooHSEventsPDF::SetUseWeightsGen (Bool_t use = kTRUE) inline
Definition at line 90 of file RooHSEventsPDF.h.
Referenced by RooHS1StepStudy::execute().
void RooHSEventsPDF::SetWeights (THSWeights * wgts) inline
Definition at line 89 of file RooHSEventsPDF.h.
Bool_t RooHSEventsPDF::UseWeightsGen () inline
Definition at line 91 of file RooHSEventsPDF.h.
References fUseWeightsGen.
Referenced by RooHS1StepStudy::execute().
RooArgSet RooHSEventsPDF::VarSet (Int_t iset) const protected
Definition at line 68 of file RooHSEventsPDF.C.
References fCatSet, and fProxSet.
Referenced by AddProtoData(), getAnalyticalIntegral(), and getGenerator().
Member Data Documentation
Bool_t RooHSEventsPDF::fBranchStatus =kTRUE protected
Definition at line 37 of file RooHSEventsPDF.h.
Referenced by AddProtoData(), CheckIntegralParDep(), and SetEvTree().
vector< RooCategoryProxy* > RooHSEventsPDF::fCatSet protected
Definition at line 50 of file RooHSEventsPDF.h.
Referenced by generateEvent(), initGenerator(), initIntegrator(), InitSets(), SetEvTree(), and VarSet().
Int_t RooHSEventsPDF::fCheckInt =0 protected
Definition at line 43 of file RooHSEventsPDF.h.
Referenced by CheckIntegralParDep(), and SetEvTree().
Double_t RooHSEventsPDF::fConstInt =1 protected
Definition at line 44 of file RooHSEventsPDF.h.
Referenced by CheckIntegralParDep(), RooHSEventsHistPDF::CreateHistPdf(), and SetEvTree().
TEntryList* RooHSEventsPDF::fEntryList =nullptr protected
Definition at line 30 of file RooHSEventsPDF.h.
Referenced by generateEvent(), GetEntryList(), initGenerator(), and ~RooHSEventsPDF().
TTree* RooHSEventsPDF::fEvTree =nullptr protected
Definition at line 29 of file RooHSEventsPDF.h.
Referenced by AddProtoData(), analyticalIntegral(), CheckIntegralParDep(), ClassImp(), RooHSEventsHistPDF::CreateHistPdf(), generateEvent(), getAnalyticalIntegral(), GetEvTree(), getGenerator(), initGenerator(), initIntegrator(), ResetTree(), RooHSEventsHistPDF::RooHSEventsHistPDF(), SetEvTree(), and ~RooHSEventsPDF().
Bool_t RooHSEventsPDF::fForceConstInt =kFALSE protected
Definition at line 40 of file RooHSEventsPDF.h.
Referenced by analyticalIntegral(), and getAnalyticalIntegral().
Bool_t RooHSEventsPDF::fForceNumInt =kFALSE protected
Definition at line 41 of file RooHSEventsPDF.h.
Referenced by getAnalyticalIntegral().
Long64_t RooHSEventsPDF::fGeni =0 protected
Definition at line 60 of file RooHSEventsPDF.h.
Referenced by generateEvent(), GetGeni(), initGenerator(), and ~RooHSEventsPDF().
TString RooHSEventsPDF::fgenStr ="gen" protected
Definition at line 61 of file RooHSEventsPDF.h.
Referenced by initGenerator().
THSWeights* RooHSEventsPDF::fInWeights =nullptr protected
Definition at line 46 of file RooHSEventsPDF.h.
vector<Bool_t> RooHSEventsPDF::fIsCat protected
Definition at line 55 of file RooHSEventsPDF.h.
Bool_t RooHSEventsPDF::fIsClone =kFALSE protected
Definition at line 39 of file RooHSEventsPDF.h.
Referenced by ~RooHSEventsPDF().
Bool_t RooHSEventsPDF::fIsIntegrating =kFALSE protected
Definition at line 38 of file RooHSEventsPDF.h.
Double_t* RooHSEventsPDF::fLast =nullptr protected
Definition at line 31 of file RooHSEventsPDF.h.
Referenced by analyticalIntegral(), RooHSEventsHistPDF::analyticalIntegral(), CheckChange(), InitSets(), and ~RooHSEventsPDF().
Double_t RooHSEventsPDF::fMaxValue =0 protected
Definition at line 59 of file RooHSEventsPDF.h.
Referenced by generateEvent(), initGenerator(), and ~RooHSEventsPDF().
vector<Int_t> RooHSEventsPDF::fMCCat protected
Definition at line 53 of file RooHSEventsPDF.h.
Referenced by generateEvent(), initGenerator(), initIntegrator(), and SetEvTree().
TVectorD RooHSEventsPDF::fMCVar protected
Definition at line 51 of file RooHSEventsPDF.h.
Referenced by analyticalIntegral(), CheckRange(), RooHSEventsHistPDF::CreateHistPdf(), RooHSEventsHistPDF::evaluateMC(), generateEvent(), GetMCVar(), initGenerator(), initIntegrator(), and SetEvTree().
Int_t RooHSEventsPDF::fNcats =0 protected
Definition at line 36 of file RooHSEventsPDF.h.
Referenced by generateEvent(), and InitSets().
Long64_t RooHSEventsPDF::fNInt =-1 protected
Definition at line 32 of file RooHSEventsPDF.h.
Referenced by analyticalIntegral(), and CheckIntegralParDep().
Long64_t RooHSEventsPDF::fNMCGen =0 protected
Definition at line 33 of file RooHSEventsPDF.h.
Referenced by analyticalIntegral(), and SetEvTree().
Int_t RooHSEventsPDF::fNpars =0 protected
Definition at line 34 of file RooHSEventsPDF.h.
Referenced by CheckChange(), and InitSets().
Int_t RooHSEventsPDF::fNvars =0 protected
Definition at line 35 of file RooHSEventsPDF.h.
Referenced by generateEvent(), and InitSets().
RooHSEventsPDF* RooHSEventsPDF::fParent =nullptr protected
Definition at line 27 of file RooHSEventsPDF.h.
Referenced by ~RooHSEventsPDF().
vector< RooRealProxy* > RooHSEventsPDF::fParSet protected
Definition at line 54 of file RooHSEventsPDF.h.
Referenced by CheckChange(), CheckIntegralParDep(), InitSets(), and RooHSEventsHistPDF::MakeSets().
vector< RooRealProxy* > RooHSEventsPDF::fProxSet protected
Definition at line 49 of file RooHSEventsPDF.h.
Referenced by analyticalIntegral(), CheckRange(), generateEvent(), getAnalyticalIntegral(), initGenerator(), initIntegrator(), InitSets(), RooHSEventsHistPDF::MakeSets(), SetEvTree(), and VarSet().
Bool_t RooHSEventsPDF::fUseWeightsGen =kTRUE protected
Definition at line 42 of file RooHSEventsPDF.h.
Referenced by generateEvent(), initGenerator(), and UseWeightsGen().
vector< RooArgSet* > RooHSEventsPDF::fVarSet protected
Definition at line 48 of file RooHSEventsPDF.h.
Referenced by RooHSEventsHistPDF::MakeSets(), and ~RooHSEventsPDF().
THSWeights* RooHSEventsPDF::fWeights =nullptr protected
Definition at line 45 of file RooHSEventsPDF.h.
Referenced by generateEvent(), GetWeights(), initGenerator(), and ~RooHSEventsPDF().
The documentation for this class was generated from the following files:
HaSpect/RooHSEventsPDF.h
HaSpect/RooHSEventsPDF.C