HASPECT6: THSParticle Class Reference
THSParticle Class Reference
Definition at line 21 of file THSParticle.h.
#include <THSParticle.h>
Public Member Functions
THSParticle ()
THSParticle (int code)
THSParticle (TString pdgname)
virtual ~THSParticle ()
void SetPDGcode (Int_t code)
void SetP4 (TLorentzVector v)
void SetVectPDG (TLorentzVector v)
void SetP4 (TLorentzVector *v)
void SetXYZT (Double_t X, Double_t Y, Double_t Z, Double_t T)
void SetXYZM (Double_t X, Double_t Y, Double_t Z, Double_t M)
void SetVertex (TVector3 v)
void SetVertex (Double_t X, Double_t Y, Double_t Z)
void SetTime (Double_t time)
void SetPath (Double_t path)
void SetDoca (Double_t doca)
void SetEdep (Double_t edep)
void SetDetector (Int_t det)
void SetMeasMass (Double_t mass)
void TakePDGMass ()
void TakePDGMassFromE ()
void SetTruth (THSParticle *part)
void SetTruth (THSParticle part)
void SetTruth (TLorentzVector part, TVector3 ver, Int_t pdg)
void SetTruthOnly (Bool_t tr=kTRUE)
TLorentzVector P4 ()
TLorentzVector * P4p ()
TVector3 Vertex ()
Int_t PDG ()
Double_t PDGMass ()
Double_t MeasMass ()
Double_t Time ()
Double_t MassDiff ()
Double_t Edep ()
Double_t Doca ()
Double_t Path ()
Double_t Beta ()
Double_t HypBeta ()
Double_t HypTime ()
Double_t DeltaTime ()
Int_t Charge ()
Int_t Detector ()
TLorentzVector * TruthP4p ()
TLorentzVector TruthP4 ()
TVector3 * TruthVer ()
Int_t TruthPDG ()
Bool_t TruthOnly ()
void CopyParticle (THSParticle *part, Bool_t andPDG)
virtual void Print (Option_t *option="") const
void Add (THSParticle *hsp1, THSParticle *hsp2, Int_t pdg=0)
Double_t MakeVirtualVertex (THSParticle *p1, THSParticle *p2)
Double_t Calc_dtfDOCA (TVector3 locVertex1, TVector3 locUnitDir1, TVector3 locVertex2, TVector3 locUnitDir2, TVector3 *result)
void Calc_dtfInterDOCA (TVector3 locUnitDir1, TVector3 locUnitDir2, TVector3 locVertex1, TVector3 locVertex2, TVector3 *locInterDOCA1, TVector3 *locInterDOCA2)
Double_t p3Distance (TVector3 vec)
Double_t ResTheta ()
Double_t ResPhi ()
Double_t ResRho ()
Double_t ResE ()
Protected Attributes
TLorentzVector fP4
TVector3 fVertex
Int_t fPDGCode
Float_t fPDGMass
Float_t fMeasMass
Float_t fTime
Float_t fPath
Float_t fDoca
Float_t fEdep
Int_t fDetector =0
vector< Float_t > fCovaMatEntries
TMatrixD fCovarianceMatrix
TLorentzVector fTruthP4
TVector3 fTruthV
Int_t fTruthPDG
Bool_t fTruthOnly =kFALSE
Friends
bool operator< (const THSParticle &lhs, const THSParticle &rhs)
Constructor & Destructor Documentation
THSParticle::THSParticle ()
Definition at line 15 of file THSParticle.C.
THSParticle::THSParticle (int code)
Definition at line 17 of file THSParticle.C.
References SetPDGcode().
THSParticle::THSParticle (TString pdgname)
Definition at line 20 of file THSParticle.C.
References SetPDGcode().
virtual THSParticle::~THSParticle () inline virtual
Definition at line 54 of file THSParticle.h.
Member Function Documentation
void THSParticle::Add (THSParticle * hsp1, THSParticle * hsp2, Int_t pdg = 0)
Definition at line 40 of file THSParticle.C.
References Calc_dtfDOCA(), fDoca, fP4, P4(), SetMeasMass(), SetP4(), SetPDGcode(), SetTime(), SetTruth(), SetVertex(), TakePDGMass(), Time(), TruthP4(), TruthP4p(), TruthVer(), and Vertex().
Double_t THSParticle::Beta () inline
Definition at line 98 of file THSParticle.h.
Double_t THSParticle::Calc_dtfDOCA (TVector3 locVertex1, TVector3 locUnitDir1, TVector3 locVertex2, TVector3 locUnitDir2, TVector3 * result)
Definition at line 65 of file THSParticle.C.
References Calc_dtfInterDOCA().
Referenced by Add().
void THSParticle::Calc_dtfInterDOCA (TVector3 locUnitDir1, TVector3 locUnitDir2, TVector3 locVertex1, TVector3 locVertex2, TVector3 * locInterDOCA1, TVector3 * locInterDOCA2)
scalar product of directions
Definition at line 79 of file THSParticle.C.
Referenced by Calc_dtfDOCA().
Int_t THSParticle::Charge () inline
Definition at line 140 of file THSParticle.h.
Referenced by THSFinalState::InitDetPartsCharge().
void THSParticle::CopyParticle (THSParticle * part, Bool_t andPDG)
Definition at line 29 of file THSParticle.C.
References Detector(), Doca(), Edep(), MeasMass(), P4(), Path(), PDG(), SetDetector(), SetDoca(), SetEdep(), SetMeasMass(), SetP4(), SetPath(), SetPDGcode(), SetTime(), SetVertex(), Time(), and Vertex().
Double_t THSParticle::DeltaTime () inline
Definition at line 101 of file THSParticle.h.
Int_t THSParticle::Detector () inline
Definition at line 103 of file THSParticle.h.
Referenced by CopyParticle(), and THSParticleIter::Testing().
Double_t THSParticle::Doca () inline
Definition at line 96 of file THSParticle.h.
Referenced by CopyParticle().
Double_t THSParticle::Edep () inline
Definition at line 95 of file THSParticle.h.
Referenced by CopyParticle().
Double_t THSParticle::HypBeta () inline
Definition at line 99 of file THSParticle.h.
Double_t THSParticle::HypTime () inline
Definition at line 100 of file THSParticle.h.
Double_t THSParticle::MakeVirtualVertex (THSParticle * p1, THSParticle * p2)
Double_t THSParticle::MassDiff () inline
Definition at line 94 of file THSParticle.h.
Double_t THSParticle::MeasMass () inline
Definition at line 92 of file THSParticle.h.
Referenced by CopyParticle().
Double_t THSParticle::p3Distance (TVector3 vec) inline
Definition at line 132 of file THSParticle.h.
Referenced by THSFinalState::IsCorrectTruth(), and THSFinalState::MatchWithGen().
TLorentzVector THSParticle::P4 () inline
Definition at line 86 of file THSParticle.h.
Referenced by Add(), CopyParticle(), and SetTruth().
TLorentzVector* THSParticle::P4p () inline
Definition at line 87 of file THSParticle.h.
Referenced by THSFinalState::IsCorrectTruth(), THSFinalState::IsMissing(), THSFinalState::MatchWithGen(), THSTxtTreeReader::ReadEvent(), and THSHipoReader::ReadEvent().
Double_t THSParticle::Path () inline
Definition at line 97 of file THSParticle.h.
Referenced by CopyParticle().
Int_t THSParticle::PDG () inline
Definition at line 90 of file THSParticle.h.
Referenced by CopyParticle(), THSFinalState::InitDetParts(), and SetTruth().
Double_t THSParticle::PDGMass () inline
Definition at line 91 of file THSParticle.h.
void THSParticle::Print (Option_t * option = "") const virtual
Definition at line 23 of file THSParticle.C.
References fP4, fPDGCode, and fVertex.
Double_t THSParticle::ResE () inline
Definition at line 137 of file THSParticle.h.
Double_t THSParticle::ResPhi () inline
Definition at line 135 of file THSParticle.h.
Double_t THSParticle::ResRho () inline
Definition at line 136 of file THSParticle.h.
Double_t THSParticle::ResTheta () inline
Definition at line 134 of file THSParticle.h.
void THSParticle::SetDetector (Int_t det) inline
Definition at line 76 of file THSParticle.h.
Referenced by CopyParticle(), and THSHipoReader::ReadEvent().
void THSParticle::SetDoca (Double_t doca) inline
Definition at line 74 of file THSParticle.h.
Referenced by CopyParticle().
void THSParticle::SetEdep (Double_t edep) inline
Definition at line 75 of file THSParticle.h.
Referenced by CopyParticle(), and THSHipoReader::ReadEvent().
void THSParticle::SetMeasMass (Double_t mass) inline
Definition at line 77 of file THSParticle.h.
Referenced by Add(), CopyParticle(), THSTxtTreeReader::ReadEvent(), and THSHipoReader::ReadEvent().
void THSParticle::SetP4 (TLorentzVector v) inline
Definition at line 63 of file THSParticle.h.
Referenced by Add(), and CopyParticle().
void THSParticle::SetP4 (TLorentzVector * v) inline
Definition at line 65 of file THSParticle.h.
void THSParticle::SetPath (Double_t path) inline
Definition at line 73 of file THSParticle.h.
Referenced by CopyParticle(), and THSHipoReader::ReadEvent().
void THSParticle::SetPDGcode (Int_t code) inline
Definition at line 58 of file THSParticle.h.
Referenced by Add(), CopyParticle(), THSTxtTreeReader::ReadEvent(), THSHipoReader::ReadEvent(), and THSParticle().
void THSParticle::SetTime (Double_t time) inline
Definition at line 72 of file THSParticle.h.
Referenced by Add(), CopyParticle(), THSTxtTreeReader::ReadEvent(), and THSHipoReader::ReadEvent().
void THSParticle::SetTruth (THSParticle * part) inline
Definition at line 81 of file THSParticle.h.
References P4(), PDG(), and Vertex().
Referenced by Add(), THSFinalState::MatchWithGen(), and THSTxtTreeReader::ReadEvent().
void THSParticle::SetTruth (THSParticle part) inline
Definition at line 82 of file THSParticle.h.
References P4(), PDG(), and Vertex().
void THSParticle::SetTruth (TLorentzVector part, TVector3 ver, Int_t pdg) inline
Definition at line 83 of file THSParticle.h.
void THSParticle::SetTruthOnly (Bool_t tr = kTRUE) inline
Definition at line 84 of file THSParticle.h.
void THSParticle::SetVectPDG (TLorentzVector v) inline
Definition at line 64 of file THSParticle.h.
void THSParticle::SetVertex (TVector3 v) inline
Definition at line 68 of file THSParticle.h.
Referenced by Add(), CopyParticle(), THSTxtTreeReader::ReadEvent(), and THSHipoReader::ReadEvent().
void THSParticle::SetVertex (Double_t X, Double_t Y, Double_t Z) inline
Definition at line 69 of file THSParticle.h.
void THSParticle::SetXYZM (Double_t X, Double_t Y, Double_t Z, Double_t M) inline
Definition at line 67 of file THSParticle.h.
void THSParticle::SetXYZT (Double_t X, Double_t Y, Double_t Z, Double_t T) inline
Definition at line 66 of file THSParticle.h.
Referenced by THSHipoReader::ReadEvent(), and THSTxtTreeReader::ReadEvent().
void THSParticle::TakePDGMass () inline
Definition at line 78 of file THSParticle.h.
Referenced by Add(), THSTxtTreeReader::ReadEvent(), and THSHipoReader::ReadEvent().
void THSParticle::TakePDGMassFromE () inline
Definition at line 79 of file THSParticle.h.
Referenced by THSHipoReader::ReadEvent().
Double_t THSParticle::Time () inline
Definition at line 93 of file THSParticle.h.
Referenced by Add(), and CopyParticle().
Bool_t THSParticle::TruthOnly () inline
Definition at line 110 of file THSParticle.h.
References Add().
TLorentzVector THSParticle::TruthP4 () inline
Definition at line 106 of file THSParticle.h.
Referenced by Add(), and THSFinalState::IsCorrectTruth().
TLorentzVector* THSParticle::TruthP4p () inline
Definition at line 105 of file THSParticle.h.
Referenced by Add().
Int_t THSParticle::TruthPDG () inline
Definition at line 108 of file THSParticle.h.
Referenced by THSFinalState::IsCorrectTruth().
TVector3* THSParticle::TruthVer () inline
Definition at line 107 of file THSParticle.h.
Referenced by Add().
TVector3 THSParticle::Vertex () inline
Definition at line 88 of file THSParticle.h.
Referenced by Add(), CopyParticle(), and SetTruth().
Friends And Related Function Documentation
bool operator< (const THSParticle & lhs, const THSParticle & rhs) friend
Definition at line 130 of file THSParticle.h.
Member Data Documentation
vector<Float_t> THSParticle::fCovaMatEntries protected
Definition at line 41 of file THSParticle.h.
TMatrixD THSParticle::fCovarianceMatrix protected
Definition at line 42 of file THSParticle.h.
Int_t THSParticle::fDetector =0 protected
Definition at line 39 of file THSParticle.h.
Float_t THSParticle::fDoca protected
Definition at line 37 of file THSParticle.h.
Referenced by Add().
Float_t THSParticle::fEdep protected
Definition at line 38 of file THSParticle.h.
Float_t THSParticle::fMeasMass protected
Definition at line 34 of file THSParticle.h.
TLorentzVector THSParticle::fP4 protected
Definition at line 24 of file THSParticle.h.
Referenced by Add(), and Print().
Float_t THSParticle::fPath protected
Definition at line 36 of file THSParticle.h.
Int_t THSParticle::fPDGCode protected
Definition at line 26 of file THSParticle.h.
Referenced by Print().
Float_t THSParticle::fPDGMass protected
Definition at line 33 of file THSParticle.h.
Float_t THSParticle::fTime protected
Definition at line 35 of file THSParticle.h.
Bool_t THSParticle::fTruthOnly =kFALSE protected
Definition at line 48 of file THSParticle.h.
TLorentzVector THSParticle::fTruthP4 protected
Definition at line 44 of file THSParticle.h.
Int_t THSParticle::fTruthPDG protected
Definition at line 46 of file THSParticle.h.
TVector3 THSParticle::fTruthV protected
Definition at line 45 of file THSParticle.h.
TVector3 THSParticle::fVertex protected
Definition at line 25 of file THSParticle.h.
Referenced by Print().
The documentation for this class was generated from the following files:
HaSpect/THSParticle.h
HaSpect/THSParticle.C