HASPECT6: THSsPlot Class Reference
THSsPlot Class Reference
RooFit interface fit class
Examples:
FitHSSimple.C.
Definition at line 8 of file THSsPlot.h.
#include <THSsPlot.h>
Public Member Functions
THSsPlot ()
THSsPlot (TString name)
THSsPlot (TString name, RooWorkspace *ws)
THSsPlot (THSsPlot *rf)
virtual ~THSsPlot ()
THSWeights * GetWeights ()
RooWorkspace * GetWorkSpace ()
void sPlot ()
Perform fit of yields to get sWeights.
void SetSPlotRange (Double_t min, Double_t max)
void MergeModelSpecies ()
void SetSingleSpecies (TString ssp)
void SetIDBranchName (TString str)
Double_t GetSWeight (Long64_t event, TString species)
void ExportWeights (TString wmname="WeightMap")
void ExportWeights1 (TString wmname="WeightMap")
void ExportTreeWeights (TString wmname="WeightMap")
void ExportWeightsToFile (TString filename)
void AddWeightMap (THSWeights *Wts)
Constructs new map if not existing.
void DrawTreeVar (TString VarName, Int_t nbins, Double_t hmin, Double_t hmax)
void AddSubWeights ()
virtual THSRooFit * CreateSubFitBins (TTree *ctree, TString rfname, Bool_t CopyTree)
void SaveHists (TString filename)
void SetWeights (THSWeights *wts)
void DeleteWeights ()
virtual void FitAndStudy (Int_t Nfits)
virtual void DefaultFitOptions ()
void SetSaveWeights (Bool_t save=kTRUE)
Public Member Functions inherited from THSRooFit
THSRooFit ()
THSRooFit (TString name)
THSRooFit (TString name, RooWorkspace *ws)
THSRooFit (THSRooFit *rf)
virtual ~THSRooFit ()
void LoadVariable (TString opt)
void LoadVariable (RooRealVar *var)
void LoadAuxVars (TString opt)
void LoadAuxVars (RooRealVar *var)
void LoadBinVars (TString opt, Int_t nbins, Double_t min, Double_t max)
void LoadBinVars (TString opt, Int_t nbins, Double_t *xbins)
void LoadSpeciesPDF (TString opt, Int_t Scale0=1)
void DefineSets ()
void LoadDataSet (TTree *tree, Bool_t toWS=kFALSE)
void LoadDataSet (RooAbsData *data, Bool_t toWS=kFALSE)
void LoadMCIntTree (TTree *tree)
void LoadMCGenTree (TTree *tree)
void LoadWeights (TString wfile, TString wname)
void LoadWeights (THSWeights *wts)
void SetDataWeight ()
void SetDataWeightFast ()
void LoadWorkSpace (RooWorkspace *ws, TString rfname="")
void LoadWorkSpaceData (RooWorkspace *ws, TString rfname="")
void TotalPDF ()
RooArgList GetVariables ()
RooRealVar * GetVariable (TString name)
RooRealVar * GetParameter (TString name)
RooArgList GetAuxVars ()
RooArgList GetBinVars ()
RooRealVar * GetAuxVar (TString name)
RooRealVar * GetBinVar (TString name)
RooRealVar * GetVar (TString name)
RooArgList GetYields ()
RooArgList * GetPDFsp ()
RooArgList * GetYieldsp ()
RooArgList GetPDFs ()
RooArgList GetParameters ()
RooArgList GetConstraints ()
RooAbsPdf * GetModel ()
RooAbsData * GetData ()
RooDataSet * GetDataSet ()
RooDataHist * GetDataHist ()
TList * GetFits ()
RooFitResult * GetResult ()
TList * GetPlots ()
void AddVariables (RooArgList list)
void AddAuxVars (RooArgList list)
void AddParameters (RooArgList list)
void AddYields (RooArgList list)
void AddGausConstraint (RooGaussian *pdf)
void AddFormulaConstraint (RooFormulaVar *formu)
void SetSingleSpecies (TString ssp)
void SetIDBranchName (TString str)
void CheckRange ()
void SetParVals (RooFitResult *res)
void SetParVals (RooArgList pars)
void RemoveDataSet ()
void CleanWSDataSets ()
void RemoveConstraints ()
TTree * GetTree ()
RooWorkspace * GetWorkSpace ()
void SetTree (TTree *tree)
void PlotDataModel ()
void PlotModel (TString varName, TString pdfName)
void Factory (TString opt)
void Fit (Bool_t randPar=kFALSE)
virtual Bool_t InitialiseFit ()
void SavePlots (TString filename)
virtual void FitMany (Int_t Nfits=1)
void FitSavedBins (Int_t Nfits)
void FitBatchBin (Int_t Nfits)
void RandomisePars ()
void MakeBins ()
void MakeBins (TTree *tree, TString name)
void MakeBinnedTrees (TTree *tree, TString name)
virtual void FitWithBins (Int_t Nfits=1)
THSBins * GetBins ()
void SetOutDir (TString name)
void SetBinDir (TString name)
void ConfigureSavedBins (TString dirname, TString pdfname="Data")
TString GetOutDir ()
TString GetBinDir ()
void WriteToFile (TString fname)
void SetBinnedFit (Bool_t bf=kTRUE)
void SetInWeights (THSWeights *wts)
void SetWeightName (TString WName)
void AddFitOption (RooCmdArg cmd)
RooLinkedList GetFitOptions ()
void SetPlot (Bool_t plot=kTRUE)
void StudyFit ()
void SetNStudyTrials (Int_t Nt)
void SetStudyPDF (TString pdfn)
void SetStudyPlot (Bool_t plot=kTRUE)
Protected Attributes
RooStats::SPlot * fSPlot =nullptr
THSWeights * fWeights =nullptr
//sPlot object
Double_t fSRange [2]
new weights calcualted in this fit
Bool_t fSaveWeights =kTRUE
Protected Attributes inherited from THSRooFit
RooWorkspace * fWS =nullptr
RooArgList fVariables
RooArgList fAuxVars
RooArgList fBinVars
RooArgList fYields
RooArgList fPDFs
RooArgList fParameters
RooArgList fConstraints
RooRealVar * fID =nullptr
RooAbsPdf * fModel =nullptr
RooAbsData * fData =nullptr
TList * fCanvases =nullptr
TList * fHists =nullptr
TList * fRooFits =nullptr
TTree * fTree =nullptr
TTree * fMCIntTree =nullptr
// tree to be imported, don't save as part of class!
TTree * fMCGenTree =nullptr
//tree for calculating MC based NormInt
TString fIDBranchName ="DontHaveOneYet"
//tree for calculating MC based NormInt
TString fYld ="Yld_"
TString fSingleSp
TString fOutDir
TString fBinDir
TString fWeightName
TString fStudyPDF
RooFitResult * fResult =nullptr
THSWeights * fInWeights =nullptr
THSBins * fDataBins =nullptr
//input weights for dataset to be fitted
Bool_t fGotID =kFALSE
Bool_t fIsPlot =kTRUE
Bool_t fBinnedFit =kFALSE
Bool_t ftoWS =kFALSE
Bool_t fStudyPlot =kFALSE
Bool_t fOwnWorkSpace =kFALSE
Double_t fChi2 =0
Int_t fFiti =0
Int_t fNStudyTrials =0
RooLinkedList fFitOptions
Constructor & Destructor Documentation
THSsPlot::THSsPlot ()
Definition at line 20 of file THSsPlot.C.
References fSRange.
Referenced by CreateSubFitBins().
THSsPlot::THSsPlot (TString name)
Definition at line 24 of file THSsPlot.C.
References fSRange.
THSsPlot::THSsPlot (TString name, RooWorkspace * ws)
Definition at line 28 of file THSsPlot.C.
References fSRange.
THSsPlot::THSsPlot (THSsPlot * rf)
Definition at line 32 of file THSsPlot.C.
References fSaveWeights, and THSRooFit::THSRooFit().
THSsPlot::~THSsPlot () virtual
Definition at line 38 of file THSsPlot.C.
References fWeights.
Member Function Documentation
void THSsPlot::AddSubWeights ()
Look through sub fits and add the maps to the total loop over subfits.
Definition at line 285 of file THSsPlot.C.
References THSWeights::Add(), THSRooFit::fRooFits, fWeights, and GetWeights().
void THSsPlot::AddWeightMap (THSWeights * Wts)
Constructs new map if not existing.
Definition at line 271 of file THSsPlot.C.
References THSWeights::Add(), THSRooFit::fOutDir, fWeights, THSWeights::SetFile(), and THSWeights::Size().
THSRooFit * THSsPlot::CreateSubFitBins (TTree * ctree, TString rfname, Bool_t CopyTree) virtual
Reimplemented from THSRooFit.
Definition at line 349 of file THSsPlot.C.
References THSRooFit::AddFitOption(), THSRooFit::fBinDir, THSRooFit::fBinnedFit, THSRooFit::fFitOptions, THSRooFit::fInWeights, THSRooFit::fNStudyTrials, THSRooFit::fOutDir, THSRooFit::fRooFits, THSRooFit::fSingleSp, fSRange, THSRooFit::fStudyPDF, THSRooFit::fWeightName, THSRooFit::fWS, THSRooFit::GetVariables(), THSRooFit::LoadDataSet(), THSRooFit::LoadWorkSpace(), THSRooFit::SetBinDir(), THSRooFit::SetBinnedFit(), THSRooFit::SetDataWeight(), THSRooFit::SetInWeights(), THSRooFit::SetNStudyTrials(), THSRooFit::SetOutDir(), SetSingleSpecies(), SetSPlotRange(), THSRooFit::SetStudyPDF(), THSRooFit::SetWeightName(), and THSsPlot().
void THSsPlot::DefaultFitOptions () virtual
Reimplemented from THSRooFit.
Definition at line 441 of file THSsPlot.C.
References THSRooFit::AddFitOption().
void THSsPlot::DeleteWeights () inline
Definition at line 49 of file THSsPlot.h.
Referenced by RooHSsPlotAndFitStudy::execute().
void THSsPlot::DrawTreeVar (TString VarName, Int_t nbins, Double_t hmin, Double_t hmax)
Examples:
FitHSSimple.C.
Definition at line 294 of file THSsPlot.C.
References THSRooFit::fCanvases, THSRooFit::fGotID, THSRooFit::fHists, THSRooFit::fIDBranchName, THSRooFit::fOutDir, THSRooFit::fTree, fWeights, THSWeights::GetEntryBinarySearch(), THSWeights::GetNSpecies(), THSWeights::GetSpeciesName(), THSWeights::GetTree(), THSWeights::GetWeight(), THSWeights::IsSorted(), THSWeights::LoadSaved(), THSWeights::SetCurrEntry(), and THSWeights::SortWeights().
void THSsPlot::ExportTreeWeights (TString wmname = "WeightMap")
This function gives a weight=0 for each entry in the tree if event not in fit (outside limits), as such the weight tree could be used with TTree::AddFriend.
Definition at line 227 of file THSsPlot.C.
References THSRooFit::fData, THSRooFit::fGotID, THSRooFit::fIDBranchName, THSWeights::FillWeights(), THSRooFit::fTree, fWeights, THSRooFit::fYields, GetSWeight(), and THSWeights::SetSpecies().
void THSsPlot::ExportWeights (TString wmname = "WeightMap")
Definition at line 188 of file THSsPlot.C.
References THSRooFit::fData, THSRooFit::fGotID, THSRooFit::fIDBranchName, THSWeights::FillWeights(), fWeights, THSRooFit::fYields, GetSWeight(), and THSWeights::SetSpecies().
Referenced by sPlot().
void THSsPlot::ExportWeights1 (TString wmname = "WeightMap")
Definition at line 206 of file THSsPlot.C.
References THSRooFit::fData, THSRooFit::fGotID, THSRooFit::fIDBranchName, THSWeights::FillWeights(), fWeights, THSRooFit::fYields, and THSWeights::SetSpecies().
Referenced by FitAndStudy().
void THSsPlot::ExportWeightsToFile (TString filename)
Definition at line 263 of file THSsPlot.C.
References fWeights, THSWeights::GetWeightList(), THSWeights::Save(), and THSWeights::SortWeights().
void THSsPlot::FitAndStudy (Int_t Nfits) virtual
Call this function to generate Nfits fits. Fit the model to data with only species yields as free pars, calculate weights and import to WeightMap. Remove any zero yield to be constant to help fit converge
Reimplemented from THSRooFit.
Examples:
FitHSSimple.C.
Definition at line 397 of file THSsPlot.C.
References THSRooFit::DefineSets(), ExportWeights1(), THSRooFit::FitMany(), THSRooFit::fModel, THSRooFit::fOutDir, fSaveWeights, fWeights, THSRooFit::fWS, THSRooFit::fYields, THSRooFit::GetPDFs(), THSRooFit::GetPDFsp(), GetWeights(), GetWorkSpace(), THSRooFit::GetYields(), THSRooFit::GetYieldsp(), THSWeights::PrintWeight(), THSWeights::Save(), THSRooFit::SavePlots(), THSWeights::SetFile(), THSWeights::SortWeights(), sPlot(), THSRooFit::StudyFit(), and THSRooFit::TotalPDF().
Double_t THSsPlot::GetSWeight (Long64_t event, TString species)
Definition at line 183 of file THSsPlot.C.
References fSPlot.
Referenced by ExportTreeWeights(), and ExportWeights().
THSWeights* THSsPlot::GetWeights () inline
Examples:
FitHSSimple.C.
Definition at line 22 of file THSsPlot.h.
Referenced by AddSubWeights(), RooHSsPlotAndFitStudy::execute(), and FitAndStudy().
RooWorkspace* THSsPlot::GetWorkSpace () inline
Definition at line 23 of file THSsPlot.h.
Referenced by FitAndStudy().
void THSsPlot::MergeModelSpecies ()
Function to combine best fit pdfs into single PDF. This allows sPlot fit to just be dependent on 2 yields where one is defined by fSingleSp and the other is the sum of the rest.
Definition at line 48 of file THSsPlot.C.
References THSRooFit::fModel, THSRooFit::fPDFs, THSRooFit::fSingleSp, fSRange, THSRooFit::fVariables, THSRooFit::fWS, THSRooFit::fYields, THSRooFit::fYld, and THSRooFit::TotalPDF().
Referenced by sPlot().
void THSsPlot::SaveHists (TString filename)
Definition at line 385 of file THSsPlot.C.
References THSRooFit::fHists.
void THSsPlot::SetIDBranchName (TString str) inline
Examples:
FitHSSimple.C.
Definition at line 30 of file THSsPlot.h.
void THSsPlot::SetSaveWeights (Bool_t save = kTRUE) inline
Definition at line 52 of file THSsPlot.h.
Referenced by RooHSsPlotAndFitStudy::execute().
void THSsPlot::SetSingleSpecies (TString ssp) inline
Definition at line 29 of file THSsPlot.h.
Referenced by CreateSubFitBins().
void THSsPlot::SetSPlotRange (Double_t min, Double_t max) inline
Definition at line 27 of file THSsPlot.h.
Referenced by CreateSubFitBins().
void THSsPlot::SetWeights (THSWeights * wts) inline
Definition at line 48 of file THSsPlot.h.
void THSsPlot::sPlot ()
Perform fit of yields to get sWeights.
Definition at line 121 of file THSsPlot.C.
References ExportWeights(), THSRooFit::fAuxVars, THSRooFit::fCanvases, THSRooFit::fChi2, THSRooFit::fData, THSRooFit::fFiti, THSRooFit::fGotID, THSRooFit::fID, THSRooFit::fIDBranchName, THSRooFit::fInWeights, THSRooFit::fIsPlot, THSRooFit::fModel, THSRooFit::fOutDir, THSRooFit::fParameters, THSRooFit::fSingleSp, fSPlot, fSRange, THSRooFit::fTree, THSRooFit::fVariables, fWeights, THSRooFit::fYields, MergeModelSpecies(), THSRooFit::PlotDataModel(), THSRooFit::SetDataWeight(), and THSWeights::SetFile().
Referenced by RooHSsPlotAndFitStudy::execute(), and FitAndStudy().
Member Data Documentation
Bool_t THSsPlot::fSaveWeights =kTRUE protected
Definition at line 13 of file THSsPlot.h.
Referenced by FitAndStudy(), and THSsPlot().
RooStats::SPlot* THSsPlot::fSPlot =nullptr protected
Definition at line 10 of file THSsPlot.h.
Referenced by GetSWeight(), and sPlot().
Double_t THSsPlot::fSRange[2] protected
new weights calcualted in this fit
Definition at line 12 of file THSsPlot.h.
Referenced by CreateSubFitBins(), MergeModelSpecies(), sPlot(), and THSsPlot().
THSWeights* THSsPlot::fWeights =nullptr protected
//sPlot object
Definition at line 11 of file THSsPlot.h.
Referenced by AddSubWeights(), AddWeightMap(), DrawTreeVar(), ExportTreeWeights(), ExportWeights(), ExportWeights1(), ExportWeightsToFile(), FitAndStudy(), sPlot(), and ~THSsPlot().
The documentation for this class was generated from the following files:
HaSpect/THSsPlot.h
HaSpect/THSsPlot.C