HASPECT6: THSWeights Class Reference
THSWeights Class Reference
Class to control weight structures in HaSpect. Consists of 1 tree with event IDs And 1 tree with the weights of the different species It relies on being able to read the trees into memory to sort the ordering, this may cause issues with order >10^7 events
Definition at line 14 of file THSWeights.h.
#include <THSWeights.h>
Public Member Functions
THSWeights ()
THSWeights (TString name)
~THSWeights ()
TTree * GetIDTree ()
void SetIDTree (TTree *tree)
TTree * GetTree ()
void SetTree (TTree *tree)
void FillWeights (Long64_t ev, TVectorD wgt)
void FillWeight (Long64_t ev, Double_t wgt)
void GetEntry (Long64_t ent)
Bool_t GetEntryFast (Long64_t id)
Bool_t GetEntrySlow (Long64_t id)
Bool_t GetEntryBinarySearch (Long64_t id)
Use a binary search to find the entry for an unsorted tree.
Double_t GetWeight (TString spe)
Double_t GetWeight (Int_t ispe)
Long64_t GetID ()
Long64_t * GetIDi ()
void SetCurrEntry (Long64_t ent)
Bool_t GotEntry ()
Bool_t IsSorted ()
Long64_t GetCurrEntry ()
Long64_t Size ()
void Add (THSWeights *wm)
void SetSpecies (TString name)
Int_t GetNSpecies ()
StrIntMap_t GetSpecies ()
StrIntMap_t * GetSpeciesp ()
TString GetSpeciesName (UInt_t isp)
Find the name for a given index.
void SetSpecies (StrIntMap_t species)
Int_t GetSpeciesID (TString name)
TList * GetWeightList ()
void PrintWeight ()
Long64_t Merge (TString tempName, TString outName="", TString wmName="WeightMap")
Function to merge weights from many root files.
void SortWeights ()
void BuildIndex ()
void SetFile (TString filename)
Set file for keeping weights on disk.
void Save ()
Finally save weights to disk.
void LoadSaved (TString fname, TString wname)
Constructor & Destructor Documentation
THSWeights::THSWeights () inline
Definition at line 31 of file THSWeights.h.
Referenced by Merge().
THSWeights::THSWeights (TString name)
Definition at line 22 of file THSWeights.C.
THSWeights::~THSWeights ()
Definition at line 33 of file THSWeights.C.
Member Function Documentation
void THSWeights::Add (THSWeights * Wts)
Add the tree
Zero weight values in case of missing species in new weights. These branches will then just be filled with zero weight for the new entries.
Definition at line 161 of file THSWeights.C.
References GetIDTree(), GetSpecies(), GetSpeciesp(), GetTree(), SetSpecies(), and Size().
Referenced by THSsPlot::AddSubWeights(), THSsPlot::AddWeightMap(), and Merge().
void THSWeights::BuildIndex ()
Definition at line 223 of file THSWeights.C.
Referenced by GetEntryBinarySearch(), GetEntryFast(), GetEntrySlow(), and SortWeights().
void THSWeights::FillWeight (Long64_t ev, Double_t wgt) inline
Definition at line 40 of file THSWeights.h.
Referenced by RooHSEventsPDF::generateEvent().
void THSWeights::FillWeights (Long64_t ev, TVectorD wgt) inline
Definition at line 39 of file THSWeights.h.
Referenced by THSsPlot::ExportTreeWeights(), THSsPlot::ExportWeights(), and THSsPlot::ExportWeights1().
Long64_t THSWeights::GetCurrEntry () inline
Definition at line 57 of file THSWeights.h.
void THSWeights::GetEntry (Long64_t ent) inline
Definition at line 42 of file THSWeights.h.
Referenced by PrintWeight().
Bool_t THSWeights::GetEntryBinarySearch (Long64_t id)
Use a binary search to find the entry for an unsorted tree.
Definition at line 88 of file THSWeights.C.
References BuildIndex().
Referenced by THSsPlot::DrawTreeVar(), THSHisto::GetWeightEvent(), THSDataManager::GetWeightEvent(), and THSRooFit::SetDataWeight().
Bool_t THSWeights::GetEntryFast (Long64_t id)
Move down the tree until you find an event with correct ID. This requires the trees are sorted in ID and fWTree is a subset of whatever tree requires the weight. Fastest if both trees have same events
Definition at line 55 of file THSWeights.C.
References BuildIndex().
Bool_t THSWeights::GetEntrySlow (Long64_t id)
for unsorted tree
Move down the tree until find event with correct ID. This is faster if trees are sorted in ID and ReStart not required (in which case use GetEntryFast) and fWTree is a subset of whatever tree requires the weight. Fastest if both trees have same events
Definition at line 71 of file THSWeights.C.
References BuildIndex().
Long64_t THSWeights::GetID () inline
Definition at line 52 of file THSWeights.h.
Long64_t* THSWeights::GetIDi () inline
Definition at line 53 of file THSWeights.h.
TTree* THSWeights::GetIDTree () inline
Definition at line 35 of file THSWeights.h.
Referenced by Add().
Int_t THSWeights::GetNSpecies () inline
Definition at line 62 of file THSWeights.h.
Referenced by THSsPlot::DrawTreeVar().
StrIntMap_t THSWeights::GetSpecies () inline
Definition at line 63 of file THSWeights.h.
Referenced by Add(), THSHisto::FillCutsForWeights(), THSHisto::LoadCutsForWeights(), and LoadSaved().
Int_t THSWeights::GetSpeciesID (TString name) inline
Definition at line 67 of file THSWeights.h.
Referenced by THSRooFit::SetDataWeight(), THSRooFit::SetDataWeightFast(), and THSRooFit::SetWeightName().
TString THSWeights::GetSpeciesName (UInt_t isp)
Find the name for a given index.
Definition at line 148 of file THSWeights.C.
Referenced by THSsPlot::DrawTreeVar(), and LoadSaved().
StrIntMap_t* THSWeights::GetSpeciesp () inline
Definition at line 64 of file THSWeights.h.
Referenced by Add().
TTree* THSWeights::GetTree () inline
Definition at line 37 of file THSWeights.h.
Referenced by Add(), THSsPlot::DrawTreeVar(), and THSRooFit::SetDataWeightFast().
Double_t THSWeights::GetWeight (TString spe) inline
Definition at line 46 of file THSWeights.h.
References GetWeight().
Referenced by THSsPlot::DrawTreeVar(), GetWeight(), THSDataManager::GetWeight(), THSRooFit::SetDataWeight(), and THSHisto::SetWeight().
Double_t THSWeights::GetWeight (Int_t ispe) inline
Definition at line 47 of file THSWeights.h.
TList* THSWeights::GetWeightList () inline
Definition at line 68 of file THSWeights.h.
Referenced by THSsPlot::ExportWeightsToFile().
Bool_t THSWeights::GotEntry () inline
Definition at line 55 of file THSWeights.h.
Bool_t THSWeights::IsSorted () inline
Definition at line 56 of file THSWeights.h.
Referenced by THSsPlot::DrawTreeVar().
void THSWeights::LoadSaved (TString fname, TString wname)
Give file name and name (in .root file) of weights object to load weights into and empty weights object e.g. THSWeights* wts=new THSWeights(); wts->LoadSaved("path_to_/Weight_File.root","HSWeight");
Definition at line 311 of file THSWeights.C.
References GetSpecies(), and GetSpeciesName().
Referenced by THSsPlot::DrawTreeVar(), THSRooFit::LoadWeights(), and Merge().
Long64_t THSWeights::Merge (TString tempName, TString outName = "", TString wmName = "WeightMap")
Function to merge weights from many root files.
Definition at line 99 of file THSWeights.C.
References Add(), LoadSaved(), PrintWeight(), SetFile(), Size(), SortWeights(), and THSWeights().
void THSWeights::PrintWeight ()
Definition at line 197 of file THSWeights.C.
References GetEntry(), and Size().
Referenced by THSsPlot::FitAndStudy(), THSRooFit::LoadWeights(), Merge(), and SortWeights().
void THSWeights::Save ()
Finally save weights to disk.
Examples:
FitHSSimple.C.
Definition at line 288 of file THSWeights.C.
Referenced by THSsPlot::ExportWeightsToFile(), THSsPlot::FitAndStudy(), and RooHSEventsPDF::~RooHSEventsPDF().
void THSWeights::SetCurrEntry (Long64_t ent) inline
Definition at line 54 of file THSWeights.h.
Referenced by THSsPlot::DrawTreeVar().
void THSWeights::SetFile (TString filename)
Set file for keeping weights on disk.
Definition at line 278 of file THSWeights.C.
Referenced by THSsPlot::AddWeightMap(), THSsPlot::FitAndStudy(), RooHSEventsPDF::initGenerator(), Merge(), and THSsPlot::sPlot().
void THSWeights::SetIDTree (TTree * tree) inline
Definition at line 36 of file THSWeights.h.
void THSWeights::SetSpecies (TString name)
Definition at line 40 of file THSWeights.C.
Referenced by Add(), THSsPlot::ExportTreeWeights(), THSsPlot::ExportWeights(), THSsPlot::ExportWeights1(), and RooHSEventsPDF::initGenerator().
void THSWeights::SetSpecies (StrIntMap_t species) inline
Definition at line 66 of file THSWeights.h.
void THSWeights::SetTree (TTree * tree) inline
Definition at line 38 of file THSWeights.h.
Long64_t THSWeights::Size () inline
Definition at line 58 of file THSWeights.h.
References Add().
Referenced by Add(), THSsPlot::AddWeightMap(), Merge(), and PrintWeight().
void THSWeights::SortWeights ()
GetEntryFast only works properly on trees where the ID is in order
This is not guaranteed particualrly if weights are merged from different bins, reorder here
Definition at line 236 of file THSWeights.C.
References BuildIndex(), and PrintWeight().
Referenced by THSsPlot::DrawTreeVar(), THSsPlot::ExportWeightsToFile(), THSsPlot::FitAndStudy(), and Merge().
The documentation for this class was generated from the following files:
HaSpect/THSWeights.h
HaSpect/THSWeights.C