HASPECT6: HaSpect/Control_Template.C File Reference
Control_Template.C File Reference
Functions
tree Add (HSin()+"FILENAMES")
if (gProof)
tree Process ("SELECTOR")
Function Documentation
tree Add (HSin()+"FILENAMES")
Referenced by THSWeights::Size(), and THSParticle::TruthOnly().
if (gProof)
Definition at line 15 of file Control_Template.C.
References HSout().
tree Process ("SELECTOR")