HASPECT6: HaSpect/hslogon.C File Reference
hslogon.C File Reference
Sets up HaSpect environment when included in .rootrc file.
Usage
Use flags when starting root to load needed functions
&ndash;hsfit : Classes for sWeight fits etc
&ndash;hssel : Classes for hselector
&ndash;hsdata : Classes for hsdata
&ndash;hsfinal=MyFinalState : Classes for hsfinalstate where
MyFinalState is the users own derived class
e.g.
root -l --hsfit FitHSSimple.C
to start FitHSSimple.C macro which uses sWeights to fit data.
root --cleanall
to remove all .so .d and .pcm files
root RunSomeScript.C --proof=N
to initialise a proof session with N workers
root --MyClass.C
to load your own class from current directory, or a class from HSANA or HSUSER
Definition in file hslogon.C.
#include <TProof.h>
Functions
void HSfit ()
void HSdata ()
void HSselector ()
void HSFinal (TString pname)
void startproof (Int_t Nw)
Start proof with Nw workers.
void LoadMacro (TString macro)
TString HSin ()
Checks for and returns HSIN variable.
TString HSout ()
Checks for and returns HSOUT variable.
TString HSfinal ()
Checks for and returns HSPROJ variable.
void HSin (TString hsin)
void HSout (TString hsout)
void HSfinal (TString hsfinal)
void CleanAll ()
void HSMacPath (TString opt)
Adds opt to MACPATH (macro path)
void HSUserPath (TString opt)
TString THSPARTICLE ("THSParticle.C")
void hslogon ()
Initialises functions demanded by the user.
Variables
TString MACPATH
Bool_t gISFARM =kFALSE
Function Documentation
void CleanAll ()
Definition at line 135 of file hslogon.C.
Referenced by HSfinal(), and hslogon().
void HSdata ()
Function is called with &ndash;hsdata
It loads the following functions:
THSWeights.C THSParticle.C THSDataManager.C THSLundReader.C THSHipoReader.C (if RHIPO set)
Definition at line 242 of file hslogon.C.
References LoadMacro(), and THSPARTICLE().
Referenced by hslogon().
void HSFinal (TString pname)
Function is called with &ndash;hsfinal
It loads the following functions:
[pname].C THSWeights.C THSDataManager.C THSFinalState.C THSKinematics.C THSParticle.C
Definition at line 220 of file hslogon.C.
References HSfinal(), LoadMacro(), and THSPARTICLE().
Referenced by hslogon().
TString HSfinal ()
Checks for and returns HSPROJ variable.
Definition at line 296 of file hslogon.C.
Referenced by HSFinal().
void HSfinal (TString hsfinal)
Definition at line 37 of file hslogon.C.
References CleanAll(), HSMacPath(), and HSUserPath().
void HSfit ()
Function is called with &ndash;hsfit
It loads necessary functions to perform RooFit/RooStats fits:
THSBins.C THSWeights.C RooHSEventsPDF.C RooHSEventsHistPDF.C THSRooFit.C THSsPlot.C RooHS1StepStudy.C RooHSsPlotAndFitStudy.C RooHSStudyManager.C
Definition at line 170 of file hslogon.C.
References LoadMacro().
Referenced by hslogon().
TString HSin ()
Checks for and returns HSIN variable.
Definition at line 303 of file hslogon.C.
Referenced by hslogon().
void HSin (TString hsin)
Definition at line 35 of file hslogon.C.
void hslogon ()
Initialises functions demanded by the user.
Definition at line 47 of file hslogon.C.
References CleanAll(), gISFARM, HSdata(), HSFinal(), HSfit(), HSin(), HSMacPath(), HSout(), HSselector(), LoadMacro(), and startproof().
void HSMacPath (TString opt)
Adds opt to MACPATH (macro path)
Definition at line 318 of file hslogon.C.
References MACPATH.
Referenced by HSfinal(), and hslogon().
TString HSout ()
Checks for and returns HSOUT variable.
Definition at line 310 of file hslogon.C.
Referenced by hslogon(), and if().
void HSout (TString hsout)
Definition at line 36 of file hslogon.C.
void HSselector ()
Function is called with &ndash;hssel
It loads the following functions:
THSBins.C THSWeights.C THSHisto.C THSOutput.C THSSkeleton.C THSKinematics.C THSParticle.C (unless explicitly replaced)
Definition at line 196 of file hslogon.C.
References LoadMacro(), and THSPARTICLE().
Referenced by hslogon().
void HSUserPath (TString opt)
Referenced by HSfinal().
void LoadMacro (TString macro)
Definition at line 268 of file hslogon.C.
References MACPATH.
Referenced by HSdata(), HSFinal(), HSfit(), hslogon(), and HSselector().
void startproof (Int_t Nw)
Start proof with Nw workers.
Definition at line 259 of file hslogon.C.
Referenced by hslogon().
TString THSPARTICLE ("THSParticle.C")
Referenced by HSdata(), HSFinal(), and HSselector().
Variable Documentation
Bool_t gISFARM =kFALSE
Definition at line 42 of file hslogon.C.
Referenced by hslogon().
TString MACPATH
Definition at line 41 of file hslogon.C.
Referenced by HSMacPath(), and LoadMacro().